################################################################################
#               ROUTING GROUPES
################################################################################


################################################################################
#               CONNECTED
################################################################################
MenuCircle:
    pattern:  /-w/mes-groupes
    defaults: { _controller: PolitizrFrontBundle:Circle:menu }
    requirements:
        _method:        GET

CircleDetail:
    pattern:  /groupes/{slug}
    defaults: { _controller: PolitizrFrontBundle:Circle:detail }
    requirements:
        _method:        GET

TopicDetail:
    pattern:  /groupes/{circleSlug}/{slug}
    defaults: { _controller: PolitizrFrontBundle:Circle:topicDetail }
    requirements:
        _method:        GET
