################################################################################
#               ROUTING GROUPES
################################################################################
HomeCircle:
    pattern:  /mes-groupes/{slug}
    defaults: { _controller: PolitizrFrontBundle:Circle:home }
    requirements:
        _method:        GET

TopicDetail:
    pattern:  /mes-groupes/{circleSlug}/{slug}
    defaults: { _controller: PolitizrFrontBundle:Circle:topicDetail }
    requirements:
        _method:        GET

