################################################################################
#               ROUTING CITOYEN
################################################################################
HomepageC:
    pattern:  /citoyen
    defaults: { _controller: PolitizrFrontBundle:Citizen:homepage }

TimelineC:
    pattern:  /citoyen/timeline
    defaults: { _controller: PolitizrFrontBundle:Citizen:timeline }

FindDebatesC:
    pattern:  /citoyen/debats-du-jour
    defaults: { _controller: PolitizrFrontBundle:Citizen:findDebates }

FindUsersC:
    pattern:  /citoyen/debatteurs-du-jour
    defaults: { _controller: PolitizrFrontBundle:Citizen:findUsers }


ContribDashboardC:
    pattern:  /citoyen/mes-contributions
    defaults: { _controller: PolitizrFrontBundle:Citizen:contribDashboard }

MyDraftsC:
    pattern:  /citoyen/mes-contributions/brouillons
    defaults: { _controller: PolitizrFrontBundle:Citizen:myDrafts }


MyDebatesC:
    pattern:  /citoyen/mes-contributions/debats
    defaults: { _controller: PolitizrFrontBundle:Citizen:myDebates }

MyCommentsC:
    pattern:  /citoyen/mes-contributions/commentaires
    defaults: { _controller: PolitizrFrontBundle:Citizen:myComments }


MyTagsC:
    pattern:  /citoyen/mon-compte/mes-tags
    defaults: { _controller: PolitizrFrontBundle:Citizen:myTags }

MyReputationC:
    pattern:  /citoyen/mon-compte/ma-reputation
    defaults: { _controller: PolitizrFrontBundle:Citizen:myReputation }

MyProfileC:
    pattern:  /citoyen/mon-compte/mon-profil
    defaults: { _controller: PolitizrFrontBundle:Citizen:myProfile }

MyPersoC:
    pattern:  /citoyen/mon-compte/mes-informations-personnelles
    defaults: { _controller: PolitizrFrontBundle:Citizen:myPerso }

MyNotificationsC:
    pattern:  /citoyen/mon-compte/mes-notifications
    defaults: { _controller: PolitizrFrontBundle:Citizen:myNotifications }

MyFollowedDebatesC:
    pattern:  /citoyen/mon-compte/mes-debats-suivis
    defaults: { _controller: PolitizrFrontBundle:Citizen:myFollowedDebates }

MyFollowedUsersC:
    pattern:  /citoyen/mon-compte/mes-profils-suivis
    defaults: { _controller: PolitizrFrontBundle:Citizen:myFollowedUsers }

