################################################################################
#               PUBLIC
################################################################################
DebateFeed:
    pattern:  /fil-du-debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateFeed }
    requirements:
        _method:        GET

DebateDetail:
    pattern:  /debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateDetail }
    requirements:
        _method:        GET

ReactionDetail:
    pattern:  /reaction/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDetail }
    requirements:
        _method:        GET

################################################################################
#               CITIZEN
################################################################################
DebateDraftNewC:
    pattern:  /citoyen/mes-contributions/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

DebateDraftEditC:
    pattern:  /citoyen/mes-contributions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        id:             \d+

ReactionDraftNewC:
    pattern:  /citoyen/{debateId}/{parentId}/mes-reactions/nouvelle
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateId:       \d+
        parentId:       \d*

ReactionDraftEditC:
    pattern:  /citoyen/mes-reactions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        id:             \d+

DraftsC:
    pattern:  /citoyen/mes-brouillons
    defaults: { _controller: PolitizrFrontBundle:Document:drafts }

MyPublicationsC:
    pattern:  /citoyen/mes-publications
    defaults: { _controller: PolitizrFrontBundle:Document:myPublications }

################################################################################
#               ELECTED
################################################################################
DebateDraftNewE:
    pattern:  /elu/mes-contributions/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

DebateDraftEditE:
    pattern:  /elu/mes-contributions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        id:             \d+

ReactionDraftNewE:
    pattern:  /elu/{debateId}/{parentId}/mes-reactions/nouvelle
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateId:       \d+
        parentId:       \d*

ReactionDraftEditE:
    pattern:  /elu/mes-reactions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        id:             \d+

DraftsE:
    pattern:  /elu/mes-contributions/brouillons
    defaults: { _controller: PolitizrFrontBundle:Document:drafts }

MyPublicationsE:
    pattern:  /citoyen/mes-publications
    defaults: { _controller: PolitizrFrontBundle:Document:myPublications }

