################################################################################
#               ROUTING DOCUMENT
################################################################################
DebateFeed:
    pattern:  /fil-du-debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateFeed }
    requirements:
        _method:        GET

DebateDetail:
    pattern:  /debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateDetail }
    requirements:
        _method:        GET

ReactionDetail:
    pattern:  /reaction/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDetail }
    requirements:
        _method:        GET

UserDetail:
    pattern:  /auteur/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:userDetail }
    requirements:
        _method:        GET

DebateDraftNew:
    pattern:  /profil/mes-contributions/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

DebateDraftEdit:
    pattern:  /profil/mes-contributions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        id:             \d+

ReactionDraftNew:
    pattern:  /elu/{debateId}/{parentId}/mes-reactions/nouvelle
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateId:       \d+
        parentId:       \d*

ReactionDraftEdit:
    pattern:  /elu/mes-reactions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        id:             \d+

