################################################################################
#               ROUTING DOCUMENT
################################################################################
DebateFeed:
    pattern:  /fil-du-debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateFeed }
    requirements:
        _method:        GET

DebateDetail:
    pattern:  /debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateDetail }
    requirements:
        _method:        GET

ReactionDetail:
    pattern:  /reaction/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDetail }
    requirements:
        _method:        GET

UserDetail:
    pattern:  /auteur/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:userDetail }
    requirements:
        _method:        GET


DebateDraftNewC:
    pattern:  /citoyen/mes-contributions/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

DebateDraftEditC:
    pattern:  /citoyen/mes-contributions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        id:             \d+

DebateDraftNewE:
    pattern:  /elu/mes-contributions/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

DebateDraftEditE:
    pattern:  /elu/mes-contributions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        id:             \d+

ReactionDraftNewC:
    pattern:  /citoyen/{debateId}/{parentId}/mes-reactions/nouvelle
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateId:       \d+
        parentId:       \d*

ReactionDraftEditC:
    pattern:  /citoyen/mes-reactions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        id:             \d+

ReactionDraftNewE:
    pattern:  /elu/{debateId}/{parentId}/mes-reactions/nouvelle
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateId:       \d+
        parentId:       \d*

ReactionDraftEditE:
    pattern:  /elu/mes-reactions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        id:             \d+



Organization:
    pattern:  /parti-politique/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:organization }
    requirements:
        _method:        GET

Tag:
    pattern:  /tag/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:tag }
    requirements:
        _method:        GET

