################################################################################
#               PUBLIC
################################################################################
DebateFeed:
    pattern:  /debat/{slug}/fil
    defaults: { _controller: PolitizrFrontBundle:Document:debateFeed }
    requirements:
        _method:        GET

DebateDetail:
    pattern:  /debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateDetail }
    requirements:
        _method:        GET

ReactionDetail:
    pattern:  /reaction/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDetail }
    requirements:
        _method:        GET

################################################################################
#               CITIZEN
################################################################################
DebateDraftNewC:
    pattern:  /citoyen/mes-brouillons/debat/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

DebateDraftEditC:
    pattern:  /citoyen/mes-brouillons/debat/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

DebateDraftPublishC:
    pattern:  /citoyen/mes-brouillons/debat/publier/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:debatePublish }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

ReactionDraftNewC:
    pattern:  /citoyen/mes-brouillons/reaction/nouveau/{debateUuid}/{parentUuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateUuid:     ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})
        parentUuid:     ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})|()

ReactionDraftEditC:
    pattern:  /citoyen/mes-brouillons/reaction/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

ReactionDraftPublishC:
    pattern:  /citoyen/mes-brouillons/reaction/publier/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionPublish }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

DraftsC:
    pattern:  /citoyen/mes-brouillons
    defaults: { _controller: PolitizrFrontBundle:Document:drafts }

BookmarksC:
    pattern:  /citoyen/mes-favoris
    defaults: { _controller: PolitizrFrontBundle:Document:bookmarks }

################################################################################
#               ELECTED
################################################################################
DebateDraftNewE:
    pattern:  /elu/mes-brouillons/debat/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

DebateDraftEditE:
    pattern:  /elu/mes-brouillons/debat/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

DebateDraftPublishE:
    pattern:  /elu/mes-brouillons/debat/publier/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:debatePublish }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

ReactionDraftNewE:
    pattern:  /elu/mes-brouillons/reaction/nouveau/{debateUuid}/{parentUuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateUuid:     ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})
        parentUuid:     ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})|()

ReactionDraftEditE:
    pattern:  /elu/mes-brouillons/reaction/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

ReactionDraftPublishE:
    pattern:  /elu/mes-brouillons/reaction/publier/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionPublish }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

DraftsE:
    pattern:  /elu/mes-brouillons
    defaults: { _controller: PolitizrFrontBundle:Document:drafts }

BookmarksE:
    pattern:  /elu/mes-favoris
    defaults: { _controller: PolitizrFrontBundle:Document:bookmarks }

