################################################################################
#               PUBLIC
################################################################################
DebateFeed:
    pattern:  /debat/{slug}/fil
    defaults: { _controller: PolitizrFrontBundle:Document:debateFeed }
    requirements:
        _method:        GET

DebateDetail:
    pattern:  /debat/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateDetail }
    requirements:
        _method:        GET

ReactionDetail:
    pattern:  /reaction/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDetail }
    requirements:
        _method:        GET

DebateDraftNew:
    pattern:  /-w/sujet/nouveau
    defaults: { _controller: PolitizrFrontBundle:Document:debateNew }

ReactionDraftNew:
    pattern:  /-w/reaction/nouveau/{debateUuid}/{parentUuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionNew }
    requirements:
        _method:        GET
        debateUuid:     ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})
        parentUuid:     ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})|()


################################################################################
#               CITIZEN
################################################################################
DebateDraftEditC:
    pattern:  /espace/citoyen/mes-brouillons/debat/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

ReactionDraftEditC:
    pattern:  /espace/citoyen/mes-brouillons/reaction/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

DraftsC:
    pattern:  /espace/citoyen/mes-brouillons
    defaults: { _controller: PolitizrFrontBundle:Document:drafts }

BookmarksC:
    pattern:  /espace/citoyen/mes-favoris
    defaults: { _controller: PolitizrFrontBundle:Document:bookmarks }

################################################################################
#               ELECTED
################################################################################
DebateDraftEditE:
    pattern:  /espace/elu/mes-brouillons/debat/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:debateEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

ReactionDraftEditE:
    pattern:  /espace/elu/mes-brouillons/reaction/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionEdit }
    requirements:
        _method:        GET
        uuid:           ([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})

DraftsE:
    pattern:  /espace/elu/mes-brouillons
    defaults: { _controller: PolitizrFrontBundle:Document:drafts }

BookmarksE:
    pattern:  /espace/elu/mes-favoris
    defaults: { _controller: PolitizrFrontBundle:Document:bookmarks }

