################################################################################
#               ROUTING ELU
################################################################################
HomepageE:
    pattern:  /elu
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:homepage }

TimelineE:
    pattern:  /elu/timeline
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:timeline }

FindDebatesE:
    pattern:  /elu/debats-du-jour
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:findDebates }

FindUsersE:
    pattern:  /elu/debatteurs-du-jour
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:findUsers }

ContribDashboardE:
    pattern:  /elu/mes-contributions
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:contribDashboard }

MyDraftsE:
    pattern:  /elu/mes-contributions/brouillons
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myDrafts }

MyDebatesE:
    pattern:  /elu/mes-contributions/debats
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myDebates }

MyReactionsE:
    pattern:  /elu/mes-contributions/reactions
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myReactions }

MyCommentsE:
    pattern:  /elu/mes-contributions/commentaires
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myComments }

MyTagsE:
    pattern:  /elu/mon-compte/mes-tags
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myTags }

MyReputationE:
    pattern:  /elu/mon-compte/ma-reputation
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myReputation }

MyProfileE:
    pattern:  /elu/mon-compte/mon-profil
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myProfile }

MyPersoE:
    pattern:  /elu/mon-compte/mes-informations-personnelles
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myPerso }

MyNotificationsE:
    pattern:  /elu/mon-compte/mes-notifications
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myNotifications }

MyFollowedDebatesE:
    pattern:  /elu/mon-compte/mes-debats-suivis
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myFollowedDebates }

MyFollowedUsersE:
    pattern:  /elu/mon-compte/mes-profils-suivis
    defaults: { _controller: PolitizrFrontBundle:ConnectedElected:myFollowedUsers }
