################################################################################
#               ROUTING ELU
################################################################################
HomepageE:
    pattern:  /elu
    defaults: { _controller: PolitizrFrontBundle:Elected:homepage }

TimelineE:
    pattern:  /elu/timeline
    defaults: { _controller: PolitizrFrontBundle:Elected:timeline }

FindDebatesE:
    pattern:  /elu/debats-du-jour
    defaults: { _controller: PolitizrFrontBundle:Elected:findDebates }

FindUsersE:
    pattern:  /elu/debatteurs-du-jour
    defaults: { _controller: PolitizrFrontBundle:Elected:findUsers }

ContribDashboardE:
    pattern:  /elu/mes-contributions
    defaults: { _controller: PolitizrFrontBundle:Elected:contribDashboard }

MyDraftsE:
    pattern:  /elu/mes-contributions/brouillons
    defaults: { _controller: PolitizrFrontBundle:Elected:myDrafts }

MyDebatesE:
    pattern:  /elu/mes-contributions/debats
    defaults: { _controller: PolitizrFrontBundle:Elected:myDebates }

MyReactionsE:
    pattern:  /elu/mes-contributions/reactions
    defaults: { _controller: PolitizrFrontBundle:Elected:myReactions }

MyCommentsE:
    pattern:  /elu/mes-contributions/commentaires
    defaults: { _controller: PolitizrFrontBundle:Elected:myComments }

MyTagsE:
    pattern:  /elu/mon-compte/mes-tags
    defaults: { _controller: PolitizrFrontBundle:Elected:myTags }

MyReputationE:
    pattern:  /elu/mon-compte/ma-reputation
    defaults: { _controller: PolitizrFrontBundle:Elected:myReputation }

MyProfileE:
    pattern:  /elu/mon-compte/mon-profil
    defaults: { _controller: PolitizrFrontBundle:Elected:myProfile }

MyPersoE:
    pattern:  /elu/mon-compte/mes-informations-personnelles
    defaults: { _controller: PolitizrFrontBundle:Elected:myPerso }

MyNotificationsE:
    pattern:  /elu/mon-compte/mes-notifications
    defaults: { _controller: PolitizrFrontBundle:Elected:myNotifications }

MyFollowedDebatesE:
    pattern:  /elu/mon-compte/mes-debats-suivis
    defaults: { _controller: PolitizrFrontBundle:Elected:myFollowedDebates }

MyFollowedUsersE:
    pattern:  /elu/mon-compte/mes-profils-suivis
    defaults: { _controller: PolitizrFrontBundle:Elected:myFollowedUsers }
