################################################################################
#               ROUTING POST INSCRIPTION HELPER
################################################################################
GlobalHelper:
    pattern:  /comment-ca-marche
    defaults: { _controller: PolitizrFrontBundle:Helper:global }
