################################################################################
#               ROUTING CONNEXION
################################################################################
Logout:
    pattern:  /deconnexion
    defaults: { _controller: PolitizrFrontBundle:Security:logout }

CancelInscription:
    pattern:  /annuler-inscription
    defaults: { _controller: PolitizrFrontBundle:Security:cancelInscription }

Login:
    pattern:  /login
    defaults: { _controller: PolitizrFrontBundle:Security:login }

################################################################################
#               ROUTING CREATION PROFIL CITOYEN
################################################################################
Inscription:
    pattern:  /inscription
    defaults: { _controller: PolitizrFrontBundle:Security:inscription }

InscriptionCheck:
    pattern:  /inscription/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionCheck }
    requirements:
        _method:        POST

InscriptionContact:
    pattern:  /u/inscription-contact
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContact }

InscriptionContactCheck:
    pattern:  /u/inscription-contact/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContactCheck }
    requirements:
        _method:        POST

################################################################################
#               ROUTING CREATION PROFIL ÉLU
################################################################################
InscriptionElected:
    pattern:  /inscription-elu
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElected }

InscriptionElectedCheck:
    pattern:  /inscription-elu/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedCheck }
    requirements:
        _method:        POST

InscriptionElectedOrder:
    pattern:  /v/inscription-elu-commande
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedOrder }

InscriptionElectedOrderCheck:
    pattern:  /v/inscription-elu-commande/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedOrderCheck }
    requirements:
        _method:        POST

InscriptionElectedPayment:
    pattern:  /v/inscription-elu-paiement
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPayment }

InscriptionElectedPaymentCheck:
    pattern:  /v/inscription-elu-paiement/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentCheck }

InscriptionElectedPaymentFinished:
    pattern:  /v/inscription-elu-paiement-termine
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentFinished }

InscriptionElectedPaymentCanceled:
    pattern:  /v/inscription-elu-paiement-annule
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentCanceled }

InscriptionElectedThanking:
    pattern:  /v/inscription-elu-remerciement
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedThanking }

MigrationElected:
    pattern:  /citoyen/migration-elu
    defaults: { _controller: PolitizrFrontBundle:Security:migrationElected }

MigrationElectedCheck:
    pattern:  /citoyen/check
    defaults: { _controller: PolitizrFrontBundle:Security:migrationElectedCheck }
    requirements:
        _method:        POST

