################################################################################
#               PUBLIC
################################################################################
ListingByTag:
    pattern:  /thematiques/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:tag }
    requirements:
        _method:        GET

ListingByOrganization:
    pattern:  /famille-politique/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:organization }
    requirements:
        _method:        GET

