################################################################################
#               DOCUMENTS
################################################################################
ListingByRecommend:
    pattern:  /publications/top
    defaults: { _controller: PolitizrFrontBundle:Listing:recommend }
    requirements:
        _method:        GET

ListingByRecommendMonthYear:
    pattern:  /publications/top/{month}-{year}
    defaults: { _controller: PolitizrFrontBundle:Listing:recommendMonthYear }
    requirements:
        _method:        GET
        month:          (janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)
        year:           ([0-9]{4})

ListingByTagClassic:
    pattern:  /publications/thematique/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:tagClassic }
    requirements:
        _method:        GET

# ListingByTag catch all URLs > cf. routing.yml

ListingByOrganization:
    pattern:  /publications/organisation/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:organization }
    requirements:
        _method:        GET

ListingSearchPublications:
    pattern:  /publications/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:searchPublications, slug: null }
    requirements:
        _method:        GET

ListingSearchUsers:
    pattern:  /communaute/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:searchUsers, slug: null }
    requirements:
        _method:        GET


################################################################################
#               USERS
################################################################################
ListingDebateFollowers:
    pattern:  /debat/{slug}/abonnes
    defaults: { _controller: PolitizrFrontBundle:Listing:debateFollowers }
    requirements:
        _method:        GET

ListingUserFollowers:
    pattern:  /auteur/{slug}/abonnes
    defaults: { _controller: PolitizrFrontBundle:Listing:userFollowers }
    requirements:
        _method:        GET

ListingUserSubscribers:
    pattern:  /auteur/{slug}/abonnements
    defaults: { _controller: PolitizrFrontBundle:Listing:userSubscribers }
    requirements:
        _method:        GET

################################################################################
#               TAGS
################################################################################
ListingTagAlphabetical:
    pattern:  /thematiques
    defaults: { _controller: PolitizrFrontBundle:Listing:tagAlphabetical }
    requirements:
        _method:        GET

