################################################################################
#               DOCUMENTS
################################################################################
ListingByRecommend:
    pattern:  /debats/top
    defaults: { _controller: PolitizrFrontBundle:Listing:recommend }
    requirements:
        _method:        GET

ListingByRecommendMonthYear:
    pattern:  /debats/top/{month}-{year}
    defaults: { _controller: PolitizrFrontBundle:Listing:recommendMonthYear }
    requirements:
        _method:        GET
        month:          (janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)
        year:           ([0-9]{4})

ListingByTag:
    pattern:  /debats/thematique/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:tag }
    requirements:
        _method:        GET

ListingByOrganization:
    pattern:  /debats/famille-politique/{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:organization }
    requirements:
        _method:        GET



################################################################################
#               USERS
################################################################################
ListingDebateFollowers:
    pattern:  /debat/{slug}/abonnes
    defaults: { _controller: PolitizrFrontBundle:Listing:debateFollowers }
    requirements:
        _method:        GET

