################################################################################
#               ROUTING CITOYEN OU ELU
################################################################################
DebateDraftNew:
    pattern:  /profil/mes-contributions/nouveau
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateNew }

DebateDraftEdit:
    pattern:  /profil/mes-contributions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateEdit }
    requirements:
        _method:        GET
        id:             \d+

