################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

Help:
    pattern:  /assistance
    defaults: { _controller: PolitizrFrontBundle:Public:help }

InscriptionTmp:
    pattern:  /inscription/{type}
    defaults: { _controller: PolitizrFrontBundle:Public:inscription }
    requirements:
        _method:        GET

InscriptionTmpFinish:
    pattern:  /merci
    defaults: { _controller: PolitizrFrontBundle:Public:inscriptionTempFinish }
    requirements:
        _method:        GET

WhoWeAre:
    pattern:  /qui-sommes-nous
    defaults: { _controller: PolitizrFrontBundle:Public:whoWeAre }

About:
    pattern:  /a-propos
    defaults: { _controller: PolitizrFrontBundle:Public:about }
