################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

Presentation:
    pattern:  /presentation
    defaults: { _controller: PolitizrFrontBundle:Public:presentation }
