################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

WhoWeAre:
    pattern:  /qui-sommes-nous
    defaults: { _controller: PolitizrFrontBundle:Public:whoWeAre }

Concept:
    pattern:  /concept
    defaults: { _controller: PolitizrFrontBundle:Public:concept }

Cgu:
    pattern:  /cgu-politizr
    defaults: { _controller: PolitizrFrontBundle:Public:cgu }

LandingPage:
    pattern:  /lp/{theme}
    defaults: { _controller: PolitizrFrontBundle:Public:landingPage, theme: null }
    requirements:
        _method:        GET
