################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

WhoWeAre:
    pattern:  /qui-sommes-nous
    defaults: { _controller: PolitizrFrontBundle:Public:whoWeAre }

Concept:
    pattern:  /concept
    defaults: { _controller: PolitizrFrontBundle:Public:concept }

Cgu:
    pattern:  /cgu-generations-eric
    defaults: { _controller: PolitizrFrontBundle:Public:cgu }

Charte:
    pattern:  /charte-generations-eric
    defaults: { _controller: PolitizrFrontBundle:Public:charte }
