################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

WhoWeAre:
    pattern:  /qui-sommes-nous
    defaults: { _controller: PolitizrFrontBundle:Public:whoWeAre }

About:
    pattern:  /a-propos
    defaults: { _controller: PolitizrFrontBundle:Public:about }
