################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

WhoWeAre:
    pattern:  /qui-sommes-nous
    defaults: { _controller: PolitizrFrontBundle:Public:whoWeAre }

Concept:
    pattern:  /notre-concept
    defaults: { _controller: PolitizrFrontBundle:Public:concept }
