################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

Cgu:
    pattern:  /conditions-generales-d-utilisation
    defaults: { _controller: PolitizrFrontBundle:Public:cgu }

Policies:
    pattern:  /policies-politizr
    defaults: { _controller: PolitizrFrontBundle:Public:policies }

Charte:
    pattern:  /notre-charte
    defaults: { _controller: PolitizrFrontBundle:Public:charte }
