################################################################################
#               ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

Help:
    pattern:  /assistance
    defaults: { _controller: PolitizrFrontBundle:Public:help }

