################################################################################
#               ROUTING RECHERCHE
################################################################################
Search:
    pattern:  /s
    defaults: { _controller: PolitizrFrontBundle:Search:search }
