################################################################################
#               ROUTING RECHERCHE
################################################################################
Search:
    pattern:  /s
    defaults: { _controller: PolitizrFrontBundle:Navigation:search }
