################################################################################
#               ROUTING CONNEXION
################################################################################
Login:
    pattern:  /connexion
    defaults: { _controller: PolitizrFrontBundle:Security:login }

LoginCheck:
    pattern:  /connexion_check

Logout:
    pattern:  /deconnexion

DeleteAccount:
    pattern:  /-w/supprimer-mon-compte
    defaults: { _controller: PolitizrFrontBundle:Security:deleteAccount }


################################################################################
#               ROUTING CREATION PROFIL
################################################################################
Inscription:
    pattern:  /inscription
    defaults: { _controller: PolitizrFrontBundle:Security:inscription }

InscriptionCheck:
    pattern:  /inscription/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionCheck }
    requirements:
        _method:        POST

InscriptionContact:
    pattern:  /-u/inscription/contact
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContact }

InscriptionContactCheck:
    pattern:  /-u/inscription/contact/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContactCheck }
    requirements:
        _method:        POST


################################################################################
#               ROUTING EMAIL SECURITY
################################################################################
UnsubscribeNotifLink:
    pattern:  /desinscription/notifications/{email}/{uuid}
    defaults: { _controller: PolitizrFrontBundle:Security:unsubscribeNotifLink }

