################################################################################
#                           HWIOAUTHBUNDLE
################################################################################
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

twitter_login:
    pattern: /login/check-twitter

google_login:
    pattern: /login/check-google

oauth_target:
    pattern: /target
    defaults: { _controller: PolitizrFrontBundle:Security:oauthTarget }