################################################################################
#               ROUTING CONNEXION
################################################################################
Login:
    pattern:  /connexion
    defaults: { _controller: PolitizrFrontBundle:Security:login }

LoginCheck:
    pattern:  /connexion_check

Logout:
    pattern:  /deconnexion

InscriptionChoice:
    pattern:  /inscription
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionChoice }


################################################################################
#               ROUTING CREATION PROFIL CITOYEN
################################################################################
Inscription:
    pattern:  /inscription/citoyen
    defaults: { _controller: PolitizrFrontBundle:Security:inscription }

InscriptionCheck:
    pattern:  /inscription/citoyen/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionCheck }
    requirements:
        _method:        POST

InscriptionContact:
    pattern:  /u/inscription/citoyen/contact
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContact }

InscriptionContactCheck:
    pattern:  /u/inscription/citoyen/contact/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContactCheck }
    requirements:
        _method:        POST

################################################################################
#               ROUTING CREATION PROFIL ÉLU
################################################################################
InscriptionElected:
    pattern:  /inscription/elu
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElected }

InscriptionElectedCheck:
    pattern:  /inscription/elu/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedCheck }
    requirements:
        _method:        POST

InscriptionElectedContact:
    pattern:  /v/inscription/elu/contact
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedContact }

InscriptionElectedContactCheck:
    pattern:  /v/inscription/elu/contact/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedContactCheck }
    requirements:
        _method:        POST

InscriptionElectedMandate:
    pattern:  /v/inscription/elu/mandat{error}
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedMandate, error: 0  }

InscriptionElectedMandateCheck:
    pattern:  /v/inscription/elu/mandat/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedMandateCheck }

InscriptionElectedOrder:
    pattern:  /v/inscription/elu/commande
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedOrder }

InscriptionElectedOrderCheck:
    pattern:  /v/inscription/elu/commande/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedOrderCheck }
    requirements:
        _method:        POST

InscriptionElectedPayment:
    pattern:  /v/inscription/elu/paiement
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPayment }

InscriptionElectedPaymentCheck:
    pattern:  /v/inscription/elu/paiement/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentCheck }

InscriptionElectedPaymentFinished:
    pattern:  /v/inscription/elu/paiement-termine
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentFinished }

InscriptionElectedPaymentCanceled:
    pattern:  /v/inscription/elu/paiement-annule
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentCanceled }

InscriptionElectedFinishSuccess:
    pattern:  /v/inscription/elu/inscription-terminee
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedFinishSuccess }

