################################################################################
#               PUBLIC
################################################################################
UserDetailClassic:
    pattern:  /auteur/{slug}
    defaults: { _controller: PolitizrFrontBundle:User:detailClassic }
    requirements:
        _method:        GET

UserDetail:
    pattern:  /@{slug}
    defaults: { _controller: PolitizrFrontBundle:User:detail }
    requirements:
        _method:        GET

################################################################################
#               CITIZEN
################################################################################
HomepageC:
    pattern:  /espace/utilisateur
    defaults: { _controller: PolitizrFrontBundle:User:timeline }

EditProfileC:
    pattern:  /espace/utilisateur/mon-compte/mon-profil
    defaults: { _controller: PolitizrFrontBundle:User:editProfile }

EditPersoC:
    pattern:  /espace/utilisateur/mon-compte/mes-informations-personnelles
    defaults: { _controller: PolitizrFrontBundle:User:editPerso }

EditNotificationsC:
    pattern:  /espace/utilisateur/mon-compte/mes-notifications
    defaults: { _controller: PolitizrFrontBundle:User:editNotifications }

################################################################################
#               ELECTED
################################################################################
HomepageE:
    pattern:  /espace/animateur
    defaults: { _controller: PolitizrFrontBundle:User:timeline }

EditProfileE:
    pattern:  /espace/animateur/mon-compte/mon-profil
    defaults: { _controller: PolitizrFrontBundle:User:editProfile }

EditPersoE:
    pattern:  /espace/animateur/mon-compte/mes-informations-personnelles
    defaults: { _controller: PolitizrFrontBundle:User:editPerso }

EditNotificationsE:
    pattern:  /espace/animateur/mon-compte/mes-notifications
    defaults: { _controller: PolitizrFrontBundle:User:editNotifications }

################################################################################
#               ID CHECK
################################################################################

IdCheckDataReviewE:
    pattern:  /espace/animateur/mon-compte/verification-donnees
    defaults: { _controller: PolitizrFrontBundle:User:idCheckDataReview }

IdCheckDataReviewCheckE:
    pattern:  /espace/animateur/mon-compte/verification-donnees/check
    defaults: { _controller: PolitizrFrontBundle:User:idCheckDataReviewCheck }
    requirements:
        _method:        POST

IdCheckE:
    pattern:  /espace/animateur/mon-compte/validation-identite
    defaults: { _controller: PolitizrFrontBundle:User:idCheck }
