parameters:
#    politzr_admin.example.class: Politzr\AdminBundle\Example

services:
#    politzr_admin.example:
#        class: %politzr_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
