parameters:
#    politzr_front.example.class: Politzr\FrontBundle\Example

services:
#    politzr_front.example:
#        class: %politzr_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
