imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

swiftmailer:
    delivery_address: lionel.bouzonville@gmail.com

# Bazinga Faker
bazinga_faker:
    locale:                             fr_FR
    entities:
        Politizr\Model\PUser:
            custom_formatters:
                FileName:               { method: image, parameters: [ '/home/lionel/www/Politizr v2.0/web/uploads/users', '150', '150', 'people', false ] }

# Bazinga Geocoder
bazinga_geocoder:
    fake_ip:
        enabled:                        true
        ip:                             77.130.87.35
