imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing.yml" }
    profiler: { only_exceptions: false }

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

swiftmailer:
    delivery_address: lionel.bouzonville@gmail.com

# Bazinga Faker
bazinga_faker:
    locale:                             fr_FR
    entities:
        Politizr\Model\PUser:
            custom_formatters:
                FileName:               { method: image, parameters: [ '/var/www/politizr.v2.letitbug.com/web/uploads/users', '150', '150', 'people', false ] }
 #         Politizr\Model\PDDebate:
 #             custom_formatters:
 #                 FileName:               { method: image, parameters: [ '/var/www/politizr.v2.letitbug.com/web/uploads/documents', '640', '480', 'city', false ] }
