imports:
    - { resource: config_dev.yml }

# http://propelorm.org/Propel/cookbook/symfony2/testing.html
# DB Test
propel:
    dbal:
        dsn: %database_driver%:host=%database_host%;dbname=%database_name%_test;charset=UTF8
    #db connection
    dbal:
        connections:
            default:
               driver:             mysql
               user:               %database_user%
               password:           %database_password%
               dsn:                mysql:host=%database_host%;dbname=%database_name%_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
