imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    session.attribute_bag.class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enabled: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme

    default_locale:  %locale%
    # trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    # App variables
#    globals:
#      image_path_project:     %image_path_project%
#      image_path_diaporama:   %image_path_diaporama%
    globals:
        pagerfanta_opts:
            previous_message: '< page précédente'
            next_message:     'page suivante >'
            dots_message:     '...'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    auth_mode: "%mailer_auth_mode%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Security Configuration
security:
    acl: ~

# JMS Security Configuration
jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false
    expressions: true

# Propel Configuration
propel:
    # The next two lines are useless if you are using Composer
    # to manage your dependencies
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"

    #db connection
    dbal:
        connections:
            default:
               driver:             mysql
               user:               %database_user%
               password:           %database_password%
               dsn:                mysql:host=%database_host%;dbname=%database_name%
               options:
                   ATTR_PERSISTENT: false
               attributes:
                   ATTR_EMULATE_PREPARES: true
               settings:
                   charset:        { value: UTF8 }
                   queries:        { query: 'set names utf8' }

# FOSUser Configuration
fos_user:
#    service:
#        mailer:         fos_user.mailer.noop
    user_class:         FOS\UserBundle\Propel\User
    db_driver:          propel
    firewall_name:      main
    from_email:
        address:        ne-pas-repondre@politzr.com
        sender_name:    Administrateur Politzr

# KNPMenu Configuration
knp_menu:
    twig:               # use "twig: false" to disable the Twig extension and the TwigRenderer
        template:       knp_menu.html.twig
    templating:         false # if true, enables the helper for PHP templates
    default_renderer:   twig # The renderer to use, list is also available by default

# AdminGeneratorGenerator Configuration
admingenerator_generator:
    base_admin_template:  PolitzrAdminBundle::base_admin.html.twig
    dashboard_welcome_path: admin_homepage

#    templates_dirs:       [ %kernel.root_dir%/../vendor/cedriclombardot/admingenerator-oldtheme-bundle/Admingenerator/OldThemeBundle/Resources/templates ]
    use_propel:           true
    use_doctrine_orm:     false
    use_doctrine_odm:     false

    login_path:           fos_user_security_login
    logout_path:          fos_user_security_logout

    form_types:
        propel:
            TIMESTAMP:    datetime 
            BU_TIMESTAMP: datetime 
            DATE:         date 
            BU_DATE:      date 
            TIME:         time 
            FLOAT:        number 
            REAL:         number 
            DOUBLE:       number 
            DECIMAL:      number 
            TINYINT:      integer 
            SMALLINT:     integer 
            INTEGER:      integer 
            BIGINT:       integer 
            NUMERIC:      integer 
            CHAR:         text 
            VARCHAR:      text 
            LONGVARCHAR:  textarea 
            BLOB:         textarea 
            CLOB:         textarea 
            CLOB_EMU:     textarea 
            model:        model 
            collection:   collection 
            PHP_ARRAY:    collection 
            ENUM:         choice 
            BOOLEAN:      checkbox 
            BOOLEAN_EMU:  checkbox

    filter_types:
        propel:
          BOOLEAN:       choice
          BOOLEAN_EMU:   choice
          collection:    model
          DATE:          afe_daterange_picker
          BU_DATE:       afe_daterange_picker
          TIMESTAMP:     afe_daterange_picker 
          BU_TIMESTAMP:  afe_daterange_picker 

    twig:
        use_localized_date:           true
        # by default the localized date is disabled thats why default settings 
        # use PHP date()'s format if you enable localized date make sure to change 
        # these to ISO 8601 compatible format!
        date_format:                  'dd/MM/Y'         # for ISO 8601 "yyyy-MM-dd"
        datetime_format:              'dd/MM/Y H:mm'     # for ISO 8601 "yyyy-MM-dd HH:mm:ss"
        localized_date_format:        "medium"
        localized_datetime_format:    "medium"
        number_format:
          decimal:        2
          decimal_point:  ','
          thousand_separator: ' '


    stylesheets:
      - { path: bundles/politzradmin/css/backoffice.css }

# AdminGeneratorUser Configuration
admingenerator_user:
    login_template:      PolitzrAdminBundle::Login\login.html.twig

# Liip Imagine Configuration
liip_imagine:
#    driver:               gd
#    web_root:             %kernel.root_dir%/../web
#    data_root:            %kernel.root_dir%/../web
    cache_mkdir_mode:     0777
    cache_prefix:         /uploads/cache
#    cache:                web_path
#    cache_clearer:        true
#    data_loader:          filesystem
#    controller_action:    liip_imagine.controller:filterAction
#    formats:              []
    filter_sets:
        # Liste des produits
        listing_thumb:
#            path:                 ~
            quality:              100
#            format:               ~
#            cache:                ~
#            data_loader:          ~
#            controller_action:    ~
            filters:
#                thumbnail: { size: [186, 279], mode: outbound }
                relative_resize: { widen: 186 }
        basket_thumb:
            quality:              100
            filters:
                relative_resize: { widen: 55 }
        associated_thumb:
            quality:              100
            filters:
                relative_resize: { widen: 120 }
        postal_thumb:
            quality:              100
            filters:
                relative_resize: { heighten: 80 }
        page_gallery:
            quality:              100
            filters:
                relative_resize: { heighten: 500 }

# StudioEchoMediaBundle Configuration
studio_echo_media:
    medias:
        activity_images:
          type:               image
          extension_list:     [ jpg, jpeg, png ]
          max_files:          10
          max_size:           5
          category_id:        1
#        product_documents:
#          type:               document
#          extension_list:     [ doc, docx, odt, pdf ]
#          max_files:          10
#          max_size:           5
#          culture:            fr
#          category_id:        2
#          keep_file_name:     false

