imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    session.attribute_bag.class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag

framework:
    # config / bazingageocoder
    trusted_proxies: ['127.0.0.1']

    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enabled: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme

    default_locale:  %locale%
    # trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    # App variables
#    globals:
#      image_path_project:     %image_path_project%
#      image_path_diaporama:   %image_path_diaporama%
    globals:
        facebook:
            client_id:          %facebook_client_id%
            client_secret:      %facebook_client_secret%
            scope:              %facebook_scope%
        pagerfanta_opts:
            previous_message:   '< page précédente'
            next_message:       'page suivante >'
            dots_message:       '...'

# Assetic Configuration
assetic:
    filters:
        cssrewrite:         ~
        sass:
            bin:            /usr/local/bin/sass
            apply_to:       "\.scss$"
        less:
            node:           /usr/bin/nodejs
            node_paths:     [/usr/local/lib/node_modules]
            apply_to:       "\.less$"

# Twitter Bootstrap config
braincrafted_bootstrap:
    output_dir:             bootstrap
    assets_dir:             %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path:            %kernel.root_dir%/../web/bundles/politizrfront/js/jquery-1.11.1.min.js
    less_filter:            sass # "less", "lessphp", "sass" or "none"
    fonts_dir:              %kernel.root_dir%/../web/fonts
    icon_prefix:            fa
    fontawesome_dir:        %kernel.root_dir%/../vendor/fortawesome/font-awesome
    auto_configure:
        assetic:            true
        twig:               true
        knp_menu:           true
        knp_paginator:      true
    customize:
        variables_file:     ~
        bootstrap_output:   %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    auth_mode: "%mailer_auth_mode%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Security Configuration
security:
    acl: ~

# JMS Security Configuration
jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false
    expressions: true

# Propel Configuration
propel:
    # The next two lines are useless if you are using Composer
    # to manage your dependencies
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"

    #db connection
    dbal:
        connections:
            default:
               driver:             mysql
               user:               %database_user%
               password:           %database_password%
               dsn:                mysql:host=%database_host%;dbname=%database_name%
               options:
                   ATTR_PERSISTENT: false
               attributes:
                   ATTR_EMULATE_PREPARES: true
               settings:
                   charset:        { value: UTF8 }
                   queries:        { query: 'set names utf8' }

# FOSUser Configuration
fos_user:
#    service:
#        mailer:         fos_user.mailer.noop
    user_class:         FOS\UserBundle\Propel\User
    db_driver:          propel
    firewall_name:      main
    from_email:
        address:        ne-pas-repondre@politizr.fr
        sender_name:    Administrateur Politizr

# KNPMenu Configuration
knp_menu:
    twig:               # use "twig: false" to disable the Twig extension and the TwigRenderer
        template:       knp_menu.html.twig
    templating:         false # if true, enables the helper for PHP templates
    default_renderer:   twig # The renderer to use, list is also available by default

# AdminGeneratorGenerator Configuration
admingenerator_generator:
    base_admin_template:  PolitizrAdminBundle::base_admin.html.twig
    dashboard_welcome_path: admin_homepage

#    templates_dirs:       [ %kernel.root_dir%/../vendor/cedriclombardot/admingenerator-oldtheme-bundle/Admingenerator/OldThemeBundle/Resources/templates ]
    use_propel:           true
    use_doctrine_orm:     false
    use_doctrine_odm:     false

    login_path:           fos_user_security_login
    logout_path:          fos_user_security_logout

    form_types:
        propel:
            TIMESTAMP:    datetime 
            BU_TIMESTAMP: datetime 
            DATE:         date 
            BU_DATE:      date 
            TIME:         time 
            FLOAT:        number 
            REAL:         number 
            DOUBLE:       number 
            DECIMAL:      number 
            TINYINT:      integer 
            SMALLINT:     integer 
            INTEGER:      integer 
            BIGINT:       integer 
            NUMERIC:      integer 
            CHAR:         text 
            VARCHAR:      text 
            LONGVARCHAR:  textarea 
            BLOB:         textarea 
            CLOB:         textarea 
            CLOB_EMU:     textarea 
            model:        model 
            collection:   collection 
            PHP_ARRAY:    collection 
            ENUM:         choice 
            BOOLEAN:      checkbox 
            BOOLEAN_EMU:  checkbox

    filter_types:
        propel:
          BOOLEAN:       choice
          BOOLEAN_EMU:   choice
          collection:    model
          DATE:          afe_daterange_picker
          BU_DATE:       afe_daterange_picker
          TIMESTAMP:     afe_daterange_picker 
          BU_TIMESTAMP:  afe_daterange_picker 

    twig:
        use_localized_date:           true
        # by default the localized date is disabled thats why default settings 
        # use PHP date()'s format if you enable localized date make sure to change 
        # these to ISO 8601 compatible format!
        date_format:                  'dd/MM/Y'         # for ISO 8601 "yyyy-MM-dd"
        datetime_format:              'dd/MM/Y H:mm'     # for ISO 8601 "yyyy-MM-dd HH:mm:ss"
        localized_date_format:        "medium"
        localized_datetime_format:    "medium"
        number_format:
          decimal:        2
          decimal_point:  ','
          thousand_separator: ' '


    stylesheets:
      - { path: bundles/politizradmin/css/backoffice.css }

# AdminGeneratorUser Configuration
admingenerator_user:
    login_template:      PolitizrAdminBundle::Login\login.html.twig

# Liip Imagine Configuration
liip_imagine:
#    driver:               gd
#    web_root:             %kernel.root_dir%/../web
#    data_root:            %kernel.root_dir%/../web
    cache_mkdir_mode:     0777
    cache_prefix:         /uploads/cache
#    cache:                web_path
#    cache_clearer:        true
#    data_loader:          filesystem
#    controller_action:    liip_imagine.controller:filterAction
#    formats:              []
    filter_sets:
        # ADMIN
        admin_list_thumb:
            quality:              100
            filters:
                relative_resize:  { widen: 100 }
        admin_show_thumb:
            quality:              100
            filters:
                relative_resize:  { widen: 150 }
        admin_organization:
            quality:              100
            filters:
                relative_resize:  { widen: 50 }


        # FRONT / GENERAL
        facebook_share:
            quality:              100
            filters:
                thumbnail:         { size: [90, 90], mode: outbound }

        debate_header:
            quality:              100
            filters:
                thumbnail:         { size: [640, 480], mode: outbound }
        debate_list:
            quality:              100
            filters:
                thumbnail:         { size: [640, 200], mode: outbound }

        user_bio_back:
            quality:              100
            filters:
                thumbnail:         { size: [640, 480], mode: inbound }
        user_bio:
            quality:              100
            filters:
                thumbnail:         { size: [150, 150], mode: outbound }
        user_mini:
            quality:              100
            filters:
                thumbnail:         { size: [25, 25], mode: outbound }
        user_follower:
            quality:              100
            filters:
                thumbnail:         { size: [50, 50], mode: outbound }

        organization_mini:
            quality:              100
            filters:
                relative_resize:  { widen: 50 }


        # FRONT / ESPACE CITOYEN
        c_document_list_thumb:
            quality:              100
            filters:
                relative_resize:  { widen: 100 }


# Bazinga Faker
bazinga_faker:
    locale:                             fr_FR
    entities:
        #################################################################################################################
        #                                   UTILISATEUR
        #################################################################################################################
        Politizr\Model\PUser:
            number:                     50
            custom_formatters:
                PUStatusId:             { method: numberBetween, parameters: [ 1, 1 ] }

                Firstname:              { method: firstname }
                Name:                   { method: lastname }

                Subtitle:               { method: realText, parameters: [ 300 ] }
                Biography:              { method: paragraphs, parameters: [ 4, true ] }

                Website:                { method: url }
                Twitter:                { method: lexify, parameters: [ 'https://twitter.com/??????' ] }
                Facebook:               { method: lexify, parameters: [ 'https://facebook.com/??????' ] }
                Phone:                  { method: phoneNumber }

                Email:                  { method: email }

                Provider:               { method: null }
                ProviderId:             { method: null }
                Nickname:               { method: null }
                Realname:               { method: null }

                UsernameCanonical:      { method: null }
                EmailCanonical:         { method: null }
                Salt:                   { method: null }
                Password:               { method: null }
                ConfirmationToken:      { method: null }
                PasswordRequestedAt:    { method: null }

                NbViews:                { method: numberBetween, parameters: [ 150, 1500 ] }
                Qualified:              { method: boolean, parameters: [ 0 ] }
                Validated:              { method: boolean, parameters: [ 0 ] }

                Online:                 { method: boolean, parameters: [ 100 ] }
                Slug:                   { method: null }

        Politizr\Model\PUFollowT:
            number:                     150
            custom_formatters:
                PUserId:                { method: numberBetween, parameters: [ 1, 70 ] }
                PTagId:                 { method: numberBetween, parameters: [ 1, 35 ] }

        Politizr\Model\PUTaggedT:
            number:                     150
            custom_formatters:
                PUserId:                { method: numberBetween, parameters: [ 1, 70 ] }
                PTagId:                 { method: numberBetween, parameters: [ 1, 35 ] }

        Politizr\Model\PUAffinityQO:
            number:                     150
            custom_formatters:
                PUserId:                { method: numberBetween, parameters: [ 1, 70 ] }
                PQOrganizationId:       { method: numberBetween, parameters: [ 1, 16 ] }


        #################################################################################################################
        #                                   REPUTATION
        #################################################################################################################
        Politizr\Model\PUBadges:
            number:                     50
            custom_formatters:
                PUserId:                { method: numberBetween, parameters: [ 1, 70 ] }
                PRBadgeId:              { method: numberBetween, parameters: [ 1, 12 ] }

        Politizr\Model\PUReputation:
            number:                     150
            custom_formatters:
                PUserId:                { method: numberBetween, parameters: [ 1, 70 ] }
                PRActionId:             { method: numberBetween, parameters: [ 1, 12 ] }


      #################################################################################################################
        #                                   COMMANDE
        #################################################################################################################
        Politizr\Model\POrder:
            number:                     20
            custom_formatters:
                POOrderStateId:         { method: numberBetween, parameters: [ 1, 3 ] }
                POPaymentStateId:       { method: numberBetween, parameters: [ 1, 3 ] }
                POPaymentTypeId:        { method: numberBetween, parameters: [ 1, 4 ] }
                POSubscriptionId:       { method: numberBetween, parameters: [ 1, 1 ] }

                SubscriptionTitle:      { method: randomElement, parameters: [ [ 'Abonnement Annuel'] ] }
                SubscriptionDescription:  { method: randomElement, parameters: [ [ 'Abonnement Annuel'] ] }
                SubscriptionBeginAt:    { method: dateTimeThisYear }
                SubscriptionEndAt:      { method: dateTimeThisYear }

                Information:            { method: paragraphs, parameters: [ 2, true ] }

                Price:                  { method: randomFloat, parameters: [ 2, 0, 500 ] }
                Promotion:              { method: randomFloat, parameters: [ 2, 0, 500 ] }
                Total:                  { method: randomFloat, parameters: [ 2, 0, 500 ] }

                Firstname:              { method: firstname }
                Name:                   { method: lastname }

                InvoiceRef:             { method: bothify, parameters: [ '?####?#####' ], unique: true }
                InvoiceFilename:        { method: lexify, parameters: [ '?????????????.pdf' ], unique: true }

                SupportingDocument:     { method: null }
                ElectiveMandates:       { method: null }

        #################################################################################################################
        #                                   DOCUMENTS
        #################################################################################################################
        Politizr\Model\PDDebate:
            number:                     50
            custom_formatters:
                Title:                  { method: realText, parameters: [ 75 ] }

                Summary:                { method: lorem, parameters: [ 5, 2, 0, 0, 0, 0, 0, 0, 0 ] }
                Description:            { method: lorem, parameters: [ 50, 10, 5, 2, 2, 0, 0, 0, 0 ] }

                NotePos:                { method: numberBetween, parameters: [ 2, 50 ] }
                NoteNeg:                { method: numberBetween, parameters: [ 2, 50 ] }

                Favorite:               { method: boolean, parameters: [ 10 ] }

                Published:              { method: boolean, parameters: [ 90 ] }
                PublishedAt:            { method: dateTimeThisYear }
                PublishedBy:            { method: null }

                Online:                 { method: boolean, parameters: [ 100 ] }
                Slug:                   { method: null }

        Politizr\Model\PUFollowDD:
            number:                     50
            custom_formatters:
                PDDebateId:             { method: numberBetween, parameters: [ 1, 6 ] }
                PUserId:                { method: numberBetween, parameters: [ 1, 70 ] }

        Politizr\Model\PDDTaggedT:
            number:                     20
            custom_formatters:
                PDDebateId:             { method: numberBetween, parameters: [ 1, 6 ] }
                PTagId:                 { method: numberBetween, parameters: [ 1, 35 ] }

        Politizr\Model\PDComment:
            number:                     50
            custom_formatters:
                PUserId:                { method: numberBetween, parameters: [ 1, 70 ] }
                PDocumentId:            { method: numberBetween, parameters: [ 1, 6 ] }

                Description:            { method: realText, parameters: [ 250 ] }
                ParagraphNo:            { method: randomDigit }

                NotePos:                { method: numberBetween, parameters: [ 2, 50 ] }
                NoteNeg:                { method: numberBetween, parameters: [ 2, 50 ] }

                PublishedBy:            { method: null }
                PublishedAt:            { method: dateTimeThisYear }

                Online:                 { method: boolean, parameters: [ 100 ] }


# Géoloc
bazinga_geocoder:
    fake_ip:
        enabled:                        false
        ip:                             ~
    providers:
        geoip:                          []
        free_geo_ip:                    []
        google_maps:
            locale:                     ~
            region:                     FR
            use_ssl:                    false

# OAuth Instagram
hwi_oauth:
    firewall_name:                      oauth
    resource_owners:
        facebook:       
            type:                       facebook
            client_id:                  %facebook_client_id%
            client_secret:              %facebook_client_secret%
            scope:                      %facebook_scope%
            options:        
                display:                popup               #dialog is optimized for popup window
        twitter:
            type:                       twitter
            client_id:                  %twitter_api_key%
            client_secret:              %twitter_api_secret%

        google:
            type:                       google
            client_id:                  %google_client_id%
            client_secret:              %google_client_secret%
            scope:                      "%google_scope%"
