imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    session.attribute_bag.class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag

framework:
    # config / bazingageocoder
    trusted_proxies: ['127.0.0.1']

    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enabled: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme

    default_locale:  %locale%
    # trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    # App variables
#    globals:
#      image_path_project:     %image_path_project%
#      image_path_diaporama:   %image_path_diaporama%
    globals:
        facebook:
            client_id:          %facebook_client_id%
            client_secret:      %facebook_client_secret%
            scope:              %facebook_scope%
        pagerfanta_opts:
            previous_message:   '< page précédente'
            next_message:       'page suivante >'
            dots_message:       '...'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    auth_mode: "%mailer_auth_mode%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Security Configuration
security:
    acl: ~

# JMS Security Configuration
jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false
    expressions: true

# Propel Configuration
propel:
    # The next two lines are useless if you are using Composer
    # to manage your dependencies
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"

    #db connection
    dbal:
        connections:
            default:
               driver:             mysql
               user:               %database_user%
               password:           %database_password%
               dsn:                mysql:host=%database_host%;dbname=%database_name%
               options:
                   ATTR_PERSISTENT: false
               attributes:
                   ATTR_EMULATE_PREPARES: true
               settings:
                   charset:        { value: UTF8 }
                   queries:        { query: 'set names utf8' }

# FOSUser Configuration
fos_user:
#    service:
#        mailer:         fos_user.mailer.noop
    user_class:         FOS\UserBundle\Propel\User
    db_driver:          propel
    firewall_name:      main
    from_email:
        address:        ne-pas-repondre@politizr.fr
        sender_name:    Administrateur Politizr

# KNPMenu Configuration
knp_menu:
    twig:               # use "twig: false" to disable the Twig extension and the TwigRenderer
        template:       knp_menu.html.twig
    templating:         false # if true, enables the helper for PHP templates
    default_renderer:   twig # The renderer to use, list is also available by default

# AdminGeneratorGenerator Configuration
admingenerator_generator:
    base_admin_template:  PolitizrAdminBundle::base_admin.html.twig
    dashboard_welcome_path: admin_homepage

#    templates_dirs:       [ %kernel.root_dir%/../vendor/cedriclombardot/admingenerator-oldtheme-bundle/Admingenerator/OldThemeBundle/Resources/templates ]
    use_propel:           true
    use_doctrine_orm:     false
    use_doctrine_odm:     false

    login_path:           fos_user_security_login
    logout_path:          fos_user_security_logout

    form_types:
        propel:
            TIMESTAMP:    datetime 
            BU_TIMESTAMP: datetime 
            DATE:         date 
            BU_DATE:      date 
            TIME:         time 
            FLOAT:        number 
            REAL:         number 
            DOUBLE:       number 
            DECIMAL:      number 
            TINYINT:      integer 
            SMALLINT:     integer 
            INTEGER:      integer 
            BIGINT:       integer 
            NUMERIC:      integer 
            CHAR:         text 
            VARCHAR:      text 
            LONGVARCHAR:  textarea 
            BLOB:         textarea 
            CLOB:         textarea 
            CLOB_EMU:     textarea 
            model:        model 
            collection:   collection 
            PHP_ARRAY:    collection 
            ENUM:         choice 
            BOOLEAN:      checkbox 
            BOOLEAN_EMU:  checkbox

    filter_types:
        propel:
          BOOLEAN:       choice
          BOOLEAN_EMU:   choice
          collection:    model
          DATE:          afe_daterange_picker
          BU_DATE:       afe_daterange_picker
          TIMESTAMP:     afe_daterange_picker 
          BU_TIMESTAMP:  afe_daterange_picker 

    twig:
        use_localized_date:           true
        # by default the localized date is disabled thats why default settings 
        # use PHP date()'s format if you enable localized date make sure to change 
        # these to ISO 8601 compatible format!
        date_format:                  'dd/MM/Y'         # for ISO 8601 "yyyy-MM-dd"
        datetime_format:              'dd/MM/Y H:mm'     # for ISO 8601 "yyyy-MM-dd HH:mm:ss"
        localized_date_format:        "medium"
        localized_datetime_format:    "medium"
        number_format:
          decimal:        2
          decimal_point:  ','
          thousand_separator: ' '


    stylesheets:
      - { path: bundles/politizradmin/css/backoffice.css }

# AdminGeneratorUser Configuration
admingenerator_user:
    login_template:      PolitizrAdminBundle::Login\login.html.twig

# Liip Imagine Configuration
liip_imagine:
#    driver:               gd
#    web_root:             %kernel.root_dir%/../web
#    data_root:            %kernel.root_dir%/../web
    cache_mkdir_mode:     0777
    cache_prefix:         /uploads/cache
#    cache:                web_path
#    cache_clearer:        true
#    data_loader:          filesystem
#    controller_action:    liip_imagine.controller:filterAction
#    formats:              []
    filter_sets:
        # admin
        admin_list_thumb:
            quality:              100
            filters:
                relative_resize:  { widen: 100 }
        admin_show_thumb:
            quality:              100
            filters:
                relative_resize:  { widen: 150 }

        # front
        user_bio_mini_thumb:
            quality:              100
            filters:
                thumbnail:         { size: [50, 50], mode: outbound }
        user_bio_thumb:
            quality:              100
            filters:
                thumbnail:         { size: [150, 150], mode: outbound }
        facebook_share:
            quality:              100
            filters:
                thumbnail:         { size: [90, 90], mode: outbound }


# Bazinga Faker
bazinga_faker:
    locale:                             fr_FR
    entities:
        #################################################################################################################
        #                                   UTILISATEUR
        #################################################################################################################
        Politizr\Model\PUser:
            number:                     50
            custom_formatters:
                Type:                   { method: numberBetween, parameters: [ 1, 2 ] }
                Status:                 { method: numberBetween, parameters: [ 1, 1 ] }

                Firstname:              { method: firstname }
                Name:                   { method: lastname }

                Summary:                { method: paragraphs, parameters: [ 2, true ] }
                Biography:              { method: paragraphs, parameters: [ 4, true ] }

                Website:                { method: url }
                Twitter:                { method: lexify, parameters: [ 'https://twitter.com/??????' ] }
                Facebook:               { method: lexify, parameters: [ 'https://facebook.com/??????' ] }
                Phone:                  { method: phoneNumber }

                Email:                  { method: email }

                Provider:               { method: null }
                ProviderId:             { method: null }
                Nickname:               { method: null }
                Realname:               { method: null }

                UsernameCanonical:      { method: null }
                EmailCanonical:         { method: null }
                Salt:                   { method: null }
                Password:               { method: null }
                ConfirmationToken:      { method: null }
                PasswordRequestedAt:    { method: null }

                SupportingDocument:     { method: null }
                ElectiveMandates:       { method: null }

                Online:                 { method: boolean, parameters: [ 100 ] }
                Slug:                   { method: null }



        Politizr\Model\PUQualification:
            number:                     150
            custom_formatters:
                Title:                  { method: realText, parameters: [ 20 ] }
                Description:            { method: paragraphs, parameters: [ 4, true ] }

        Politizr\Model\PUFollowU:
            number:                     1

        Politizr\Model\PUFollowT:
            number:                     150
            custom_formatters:
                PTagId:                 { method: numberBetween, parameters: [ 1, 48 ] }

        Politizr\Model\PUTaggedT:
            number:                     150
            custom_formatters:
                PTagId:                 { method: numberBetween, parameters: [ 1, 48 ] }

        #################################################################################################################
        #                                   REPUTATION
        #################################################################################################################
        Politizr\Model\PUReputationRB:
            number:                     50
            custom_formatters:
                PRBadgeId:              { method: numberBetween, parameters: [ 1, 12 ] }

        Politizr\Model\PUReputationRA:
            number:                     150
            custom_formatters:
                PRActionId:             { method: numberBetween, parameters: [ 1, 12 ] }


        #################################################################################################################
        #                                   COMMANDE
        #################################################################################################################
        Politizr\Model\POrder:
            number:                     20
            custom_formatters:
                POOrderStateId:         { method: numberBetween, parameters: [ 1, 3 ] }
                POPaymentStateId:       { method: numberBetween, parameters: [ 1, 3 ] }
                POPaymentTypeId:        { method: numberBetween, parameters: [ 1, 4 ] }
                POSubscriptionId:       { method: numberBetween, parameters: [ 1, 1 ] }

                SubscriptionTitle:      { method: randomElement, parameters: [ [ 'Abonnement Annuel'] ] }
                SubscriptionDescription:  { method: randomElement, parameters: [ [ 'Abonnement Annuel'] ] }

                Information:            { method: paragraphs, parameters: [ 2, true ] }

                Price:                  { method: randomFloat, parameters: [ 2, 0, 500 ] }
                Promotion:              { method: randomFloat, parameters: [ 2, 0, 500 ] }
                Total:                  { method: randomFloat, parameters: [ 2, 0, 500 ] }

                Firstname:              { method: firstname }
                Name:                   { method: lastname }
                Address:                { method: streetAddress }
                Zip:                    { method: postcode }
                City:                   { method: city }

                InvoiceRef:             { method: bothify, parameters: [ '?####?#####' ], unique: true }
                InvoiceFilename:        { method: lexify, parameters: [ '?????????????.pdf' ], unique: true }

        #################################################################################################################
        #                                   DOCUMENTS
        #################################################################################################################
        Politizr\Model\PDDebate:
            number:                     300
            custom_formatters:
                Title:                  { method: realText, parameters: [ 150 ] }

                Summary:                { method: lorem, parameters: [ 5, 2, 0, 0, 0, 0, 0, 0, 0 ] }
                Description:            { method: lorem, parameters: [ 50, 10, 5, 2, 2, 0, 0, 0, 0 ] }
                MoreInfo:               { method: lorem, parameters: [ 5, 2, 0, 0, 0, 0, 0, 0, 0 ] }

                NotePos:                { method: numberBetween, parameters: [ 2, 50 ] }
                NoteNeg:                { method: numberBetween, parameters: [ 2, 50 ] }

                Published:              { method: boolean, parameters: [ 90 ] }
                PublishedAt:            { method: dateTimeThisYear }
                PublishedBy:            { method: null }

                Online:                 { method: boolean, parameters: [ 100 ] }
                Slug:                   { method: null }

        Politizr\Model\PUFollowDD:
            number:                     700

        Politizr\Model\PDDTaggedT:
            number:                     700
            custom_formatters:
                PTagId:                 { method: numberBetween, parameters: [ 1, 48 ] }

        Politizr\Model\PDReaction:
            number:                     700
            custom_formatters:
                Title:                  { method: realText, parameters: [ 150 ] }

                Summary:                { method: lorem, parameters: [ 5, 2, 0, 0, 0, 0, 0, 0, 0 ] }
                Description:            { method: lorem, parameters: [ 50, 10, 5, 2, 2, 0, 0, 0, 0 ] }
                MoreInfo:               { method: lorem, parameters: [ 5, 2, 0, 0, 0, 0, 0, 0, 0 ] }

                NotePos:                { method: numberBetween, parameters: [ 2, 50 ] }
                NoteNeg:                { method: numberBetween, parameters: [ 2, 50 ] }

                Published:              { method: boolean, parameters: [ 90 ] }
                PublishedAt:            { method: dateTimeThisYear }
                PublishedBy:            { method: null }

                Online:                 { method: boolean, parameters: [ 100 ] }
                Slug:                   { method: null }

        Politizr\Model\PDDComment:
            number:                     700
            custom_formatters:
                Description:            { method: realText, parameters: [ 250 ] }
                ParagraphNo:            { method: randomDigit }

                NotePos:                { method: numberBetween, parameters: [ 2, 50 ] }
                NoteNeg:                { method: numberBetween, parameters: [ 2, 50 ] }

                PublishedBy:            { method: null }
                PublishedAt:            { method: dateTimeThisYear }

                Online:                 { method: boolean, parameters: [ 100 ] }

        Politizr\Model\PDRComment:
            number:                     900
            custom_formatters:
                Description:            { method: realText, parameters: [ 150 ] }
                ParagraphNo:            { method: randomDigit }

                NotePos:                { method: numberBetween, parameters: [ 2, 50 ] }
                NoteNeg:                { method: numberBetween, parameters: [ 2, 50 ] }

                PublishedBy:            { method: null }
                PublishedAt:            { method: dateTimeThisYear }

                Online:                 { method: boolean, parameters: [ 100 ] }


        #################################################################################################################
        #                                   TAGS
        #################################################################################################################
        # Politizr\Model\PTag:
        #     number:                     1000
        #     custom_formatters:
        #         PTTagTypeId:            { method: numberBetween, parameters: [ 3, 3 ] }
        #         
        #         # Title:                  { method: realText, parameters: [ 20 ] }
        #         Title:                  { method: lexify, parameters: [ '???????????????' ], unique: true }
        # 
        #         Online:                 { method: boolean, parameters: [ 100 ] }
        #         Slug:                   { method: null }


# Géoloc
bazinga_geocoder:
    fake_ip:
        enabled:                        false
        ip:                             ~
    providers:
        geoip:                          []
        free_geo_ip:                    []
        google_maps:
            locale:                     ~
            region:                     FR
            use_ssl:                    false

# OAuth Instagram
hwi_oauth:
    firewall_name:                      oauth
    resource_owners:
        facebook:       
            type:                       facebook
            client_id:                  %facebook_client_id%
            client_secret:              %facebook_client_secret%
            scope:                      %facebook_scope%
            options:        
                display:                popup               #dialog is optimized for popup window
        twitter:
            type:                       twitter
            client_id:                  %twitter_api_key%
            client_secret:              %twitter_api_secret%

        google:
            type:                       google
            client_id:                  %google_client_id%
            client_secret:              %google_client_secret%
            scope:                      "%google_scope%"
