politizr_admin:
    resource: "@PolitizrAdminBundle/Resources/config/routing.yml"
    host:     "%host.admin%"
    prefix:   /

politizr_front:
    resource: "@PolitizrFrontBundle/Resources/config/routing.yml"
    host:     "%host.public%"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

oneup_uploader:
    resource: .
    type: uploader

nelmio_security:
    path:     /nelmio/csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods:  [POST]

# foshttpcache
user_context_hash:
    path: /_fos_user_context_hash