politizr_admin:
    resource: "@PolitizrAdminBundle/Resources/config/routing.yml"
    host:     %host.admin%
    prefix:   /

politizr_front:
    resource: "@PolitizrFrontBundle/Resources/config/routing.yml"
    host:     %host.public%
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
