# http://symfony.com/doc/master/reference/configuration/security.html
jms_security_extra:
    secure_all_services:    false
    expressions:            true

security:
    access_denied_url:    ~ # Example: /foo/error403
    access_decision_manager:
        strategy: unanimous

    always_authenticate_before_granting:  true
    acl:
        provider:           propel.security.acl.provider

    providers:
        fos_userbundle:
            id:             fos_user.user_provider.username
        oauth:
            id:             politizr.oauth_user_provider
        puser:
            propel:
                class:      Politizr\Model\PUser
                property:   username


    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Politizr\Model\PUser:               sha512

    role_hierarchy:
        ROLE_CITIZEN:     ROLE_PROFILE_COMPLETED
        ROLE_ELECTED:     [ ROLE_PROFILE_COMPLETED, ROLE_CITIZEN ]
        ROLE_ADMIN:       ROLE_USER
        ROLE_CLIENT:      ROLE_ADMIN
        ROLE_SYSTEM:      ROLE_ADMIN

    firewalls:
        # Firewall zone admin
        admin_area:
            provider:                       fos_userbundle
            pattern:                        ^/
            host:                           "%host.admin%"
            form_login:     
                provider:                   fos_userbundle
                csrf_provider:              form.csrf_provider
                login_path:                 /login
                check_path:                 /login_check
                default_target_path:        /
            logout:             
                path:                       /logout
                target:                     /login
            anonymous:                      true

        # Firewall OAuth
        oauth:
            provider:                       oauth
            pattern:                        ^/oauth/.*
            host:                           "%host.public%"
            anonymous:                      ~
            provider:                       oauth
            oauth:
                resource_owners:
                    facebook:               "/oauth/login/check-facebook"
                    twitter:                "/oauth/login/check-twitter"
                    google:                 "/oauth/login/check-google"
                # login_path:                 /oauth/login
                # failure_path:               /oauth/login
                login_path:                 /connexion
                failure_path:               /connexion
                check_path:                 /oauth/login_check
                default_target_path:        /oauth/target
                oauth_user_provider:
                    service:                politizr.oauth_user_provider

        # Firewall login classique
        user_area:
            provider:                       puser
            pattern:                        ^/
            host:                           "%host.public%"
            form_login:
                login_path:                 /connexion
                failure_path:               /connexion
                check_path:                 /connexion_check
                csrf_token_generator:       security.csrf.token_manager
                remember_me:                true
            remember_me:
                key:                        "%secret%"
                name:                       POLITIZRME
                secure:                     false
                httponly:                   true
                always_remember_me:         true
            logout:
                invalidate_session:         true
                delete_cookies:
                    POLITIZRME:             { path: null, domain: null}
                path:                       /deconnexion
                target:                     /
            anonymous:                      true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, host: "%host.admin%" }
        - { path: ^/_fos_user_context_hash, host: "%host.admin%", roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/, role: ROLE_ADMIN, host: "%host.admin%" }                               # Espace ADMIN
        - { path: ^/-u, role: ROLE_CITIZEN_INSCRIPTION, host: "%host.public%" }               # Process d'inscription citoyen
        - { path: ^/-v, role: ROLE_ELECTED_INSCRIPTION, host: "%host.public%" }               # Process d'inscription elu
        - { path: ^/espace/utilisateur, role: ROLE_CITIZEN, host: "%host.public%" }           # Espace utilisateur
        - { path: ^/espace/animateur, role: ROLE_ELECTED, host: "%host.public%" }             # Espace animateur
        - { path: ^/-w, role: ROLE_PROFILE_COMPLETED, host: "%host.public%" }                 # Profil citoyen ou élu complet
        - { path: ^/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: "%host.public%" }
        - { path: ^/oauth/target, roles: ROLE_OAUTH_USER , host: "%host.public%"}             # Process d'inscription OAuth
