# http://symfony.com/doc/master/reference/configuration/security.html
jms_security_extra:
    secure_all_services:    false
    expressions:            true

security:
    acl:
        provider:           propel.security.acl.provider

    providers:
        fos_userbundle:
            id:             fos_user.user_provider.username
        oauth:
            id:             politizr.oauth_user_provider
        main:
            propel:
                class:      Politizr\Model\PUser
                property:   username


    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Politizr\Model\PUser:               sha512

    firewalls:
        # Firewall zone admin
        admin_area:
            pattern:                        ^/admin
            form_login:     
                provider:                   fos_userbundle
                csrf_provider:              form.csrf_provider
                login_path:                 /admin/login
                check_path:                 /admin/login_check
                default_target_path:        /admin/
            logout:             
                path:                       /admin/logout
                target:                     /admin/login
            anonymous:                      true

        # Firewall OAuth
        oauth:
            pattern:                        ^/oauth/.*
            anonymous:                      ~
            provider:                       oauth
            oauth:
                resource_owners:
                    facebook:               "/oauth/login/check-facebook"
                    twitter:                "/oauth/login/check-twitter"
                    google:                 "/oauth/login/check-google"
                login_path:                 /oauth/login
                failure_path:               /oauth/login
                check_path:                 /oauth/login_check
                default_target_path:        /oauth/target
                oauth_user_provider:
                    service:                politizr.oauth_user_provider

        # Firewall login classique
        public:
            pattern:                        ^/
            form_login:
                login_path:                 /
                # check_path:                 /inscription/check
            remember_me:
                key:                        "%secret%"
                lifetime:                   31536000                # 365 jours en secondes
                path:                       /
                domain:                     ~
            logout:
                path:                       /logout
                target:                     /
                invalidate_session:         true
            anonymous:                      true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }                              # Espace ADMIN
        - { path: ^/u/, role: ROLE_USER }                                   # Process d'inscription citoyen
        - { path: ^/citoyen/, role: ROLE_CITIZEN }                          # Espace citoyen
        - { path: ^/elu/, role: ROLE_ELECTED }                              # Espace élu
        - { path: ^/oauth/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/target, roles: ROLE_OAUTH_USER }                  # Process d'inscription OAuth
