# http://symfony.com/doc/master/reference/configuration/security.html
# https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/index.md

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        provider: propel.security.acl.provider

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        # Firewall pour les pages de connexion, inscription, et récupération de mot de passe
#        login:
#            pattern:                  ^/admin/(login$|register|resetting)  # Les adresses de ces pages sont login, register et resetting
#            anonymous:                true

        # Firewall zone admin
        admin_area:
            pattern:                  ^/admin
            form_login:
                provider:             fos_userbundle
                csrf_provider:        form.csrf_provider
                login_path:           /admin/login
                check_path:           /admin/login_check
                default_target_path:  /admin/
            logout:        
                path:                 /admin/logout
                target:               /admin/login
            anonymous:                true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
