################################################################################
# 							HWIOAUTHBUNDLE
################################################################################
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

OAuth:
    resource: "@PolitizrFrontBundle/Resources/config/routingSecurityOAuth.yml"
    prefix:   /oauth/


################################################################################
#				ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

Presentation:
    pattern:  /presentation
    defaults: { _controller: PolitizrFrontBundle:Public:presentation }

EluActivationProcess:
    pattern:  /profil-elu-en-cours-de-validation
    defaults: { _controller: PolitizrFrontBundle:Public:eluActivationProcess }


################################################################################
#               ROUTING CONNEXION
################################################################################
Login:
    pattern:  /login
    defaults: { _controller: PolitizrFrontBundle:Security:login }

Logout:
    pattern:  /logout

################################################################################
#               ROUTING CREATION PROFIL CITOYEN
################################################################################
Inscription:
    pattern:  /inscription
    defaults: { _controller: PolitizrFrontBundle:Security:inscription }

InscriptionCheck:
    pattern:  /inscription/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionCheck }

InscriptionStep2:
    pattern:  /u/inscription-etape2
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionStep2 }

InscriptionStep2Check:
    pattern:  /u/inscription-etape2/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionStep2Check }

InscriptionStep3:
    pattern:  /u/inscription-etape3
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionStep3 }

InscriptionStep3Check:
    pattern:  /u/inscription-etape3/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionStep3Check }

################################################################################
#               ROUTING CREATION PROFIL ÉLU
################################################################################
InscriptionElected:
    pattern:  /inscription-elu
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElected }

InscriptionElectedCheck:
    pattern:  /inscription-elu/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedCheck }

InscriptionElectedStep2:
    pattern:  /v/inscription-elu-etape2
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedStep2 }

InscriptionElectedStep2Check:
    pattern:  /v/inscription-elu-etape2/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedStep2Check }

InscriptionElectedStep3:
    pattern:  /v/inscription-elu-etape3
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedStep3 }

InscriptionElectedStep3Check:
    pattern:  /v/inscription-elu-etape3/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedStep3Check }

InscriptionElectedStep4:
    pattern:  /v/inscription-elu-etape4
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedStep4 }

InscriptionElectedStep4Check:
    pattern:  /v/inscription-elu-etape4/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedStep4Check }


################################################################################
#				ROUTING DOCUMENT
################################################################################
DebateFeed:
    pattern:  /{id}/debat/fil/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateFeed }
    requirements:
        _method:        GET
        id:             \d+

DebateDetail:
    pattern:  /{id}/debat/detail/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateDetail }
    requirements:
        _method:        GET
        id:             \d+

ReactionDetail:
    pattern:  /{id}/reaction/detail/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDetail }
    requirements:
        _method:        GET
        id:             \d+

UserDetail:
    pattern:  /{id}/auteur/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:userDetail }
    requirements:
        _method:        GET
        id:             \d+


################################################################################
#               ROUTING CITOYEN
################################################################################
HomepageC:
    pattern:  /citoyen-{page}
    defaults: { _controller: PolitizrFrontBundle:Profile:homepageC }
    requirements:
        _method:        GET
        page:           \d+

SuggestionsC:
    pattern:  /citoyen/suggestions
    defaults: { _controller: PolitizrFrontBundle:Profile:suggestionsC }

PopularsC:
    pattern:  /citoyen/populaires
    defaults: { _controller: PolitizrFrontBundle:Profile:popularsC }


################################################################################
#               ROUTING ELU
################################################################################
HomepageE:
    pattern:  /elu
    defaults: { _controller: PolitizrFrontBundle:Profile:homepageE }



################################################################################
################################################################################
#				ROUTING AJAX
################################################################################
################################################################################


################################################################################
# LOGIN
################################################################################
LoginCheck:
    pattern:  /connexion/login.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:loginCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

LostPasswordCheck:
    pattern:  /connexion/mot-de-passe-perdu.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:lostPasswordCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }


################################################################################
# INSCRIPTION CITOYEN STEP 3 / TAGS PROFIL
################################################################################
GetPTags:
    pattern:  /u/getPTags.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:getPTags, _format: json }
    requirements: { _format: (xml|json), _method: POST }

GetPUTaggedTPTags:
    pattern:  /u/getPUTaggedTPTags.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:getPUTaggedTPTags, _format: json }
    requirements: { _format: (xml|json), _method: POST }

AddPUTaggedTPTag:
    pattern:  /u/addPUTaggedTPTag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:addPUTaggedTPTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

RemovePUTaggedTPTag:
    pattern:  /u/removePUTaggedTPTag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:removePUTaggedTPTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

GetPUFollowTPTags:
    pattern:  /u/getPUFollowTPTags.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:getPUFollowTPTags, _format: json }
    requirements: { _format: (xml|json), _method: POST }

AddPUFollowTPTag:
    pattern:  /u/addPUFollowTPTag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:addPUFollowTPTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

RemovePUFollowTPTag:
    pattern:  /u/removePUFollowTPTag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:removePUFollowTPTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

AddNewPTag:
    pattern:  /u/addNewPTag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:addNewPTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# INSCRIPTION ELU / PAIEMENT
################################################################################
PaymentProcess:
    pattern:  /v/paymentProcess.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:paymentProcess, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# CONSULTATION DEBAT / REACTION
################################################################################
GetDescriptionPDocument:
    pattern:  /getDescriptionPDocument.{_format}
    defaults: { _controller: PolitizrFrontBundle:Document:getDescriptionPDocument, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# SUIVI DEBAT / USER
################################################################################
Follow:
    pattern:  /u/follow.{_format}
    defaults: { _controller: PolitizrFrontBundle:Document:follow, _format: json }
    requirements: { _format: (xml|json), _method: POST }

Unfollow:
    pattern:  /u/unfollow.{_format}
    defaults: { _controller: PolitizrFrontBundle:Document:unfollow, _format: json }
    requirements: { _format: (xml|json), _method: POST }
