# HWIOAUTHBUNDLE
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

OAuth:
    resource: "./routing/SecurityOAuth.yml"
    prefix:   /oauth/

# Security
Security:
    resource: "./routing/Security.yml"

# Helper
Helper:
    resource: "./routing/Helper.yml"

# Public
Public:
    resource: "./routing/Public.yml"

# Document
Document:
    resource: "./routing/Document.yml"

# User
User:
    resource: "./routing/User.yml"

# Listing
Listing:
    resource: "./routing/Listing.yml"

# Feed RSS
RssFeed:
    pattern:  /rss
    defaults: { _controller: PolitizrFrontBundle:Public:rssFeed }

# Sitemap xml
SitemapXml:
    pattern:  /sitemap.xml
    defaults: { _controller: PolitizrFrontBundle:Public:sitemapXml }

# Robots.txt
RobotsTxt:
    pattern:  /robots.txt
    defaults: { _controller: PolitizrFrontBundle:Public:robotsTxt }


# GENERIC XHR
XhrGeneric:
    pattern:  /xhr/{xhrRoute}/{xhrService}/{xhrMethod}.{xhrType}.json
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrGeneric:xhr }
    requirements:
        _method:        POST
        xhrRoute:       ".+"
        xhrType:        \d

# Catch all URLs to tag listing
ListingByTagRaw:
    pattern:  /{slug}
    defaults: { _controller: PolitizrFrontBundle:Listing:tagRaw }
    requirements:
        _method:        GET

