################################################################################
# 							HWIOAUTHBUNDLE
################################################################################
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

OAuth:
    resource: "@PolitizrFrontBundle/Resources/config/routingSecurityOAuth.yml"
    prefix:   /oauth/


################################################################################
#				ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

Presentation:
    pattern:  /presentation
    defaults: { _controller: PolitizrFrontBundle:Public:presentation }


################################################################################
#               ROUTING CONNEXION / CREATION PROFIL
################################################################################
Login:
    pattern:  /login
    defaults: { _controller: PolitizrFrontBundle:Security:login }

Logout:
    pattern:  /logout

Inscription:
    pattern:  /inscription
    defaults: { _controller: PolitizrFrontBundle:Security:inscription }

InscriptionCheck:
    pattern:  /inscription/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionCheck }

InscriptionStep2:
    pattern:  /u/inscription-etape2
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionStep2 }

InscriptionStep2Check:
    pattern:  /u/inscription-etape2/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionStep2Check }

InscriptionStep3:
    pattern:  /citoyen/inscription-etape3
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionStep3 }



################################################################################
#				ROUTING ESPACE PRIVE
################################################################################
Prive:
    pattern:  /mon-espace/action
    defaults: { _controller: PolitizrFrontBundle:Profile:photoChoice }


################################################################################
#				ROUTING AJAX
################################################################################

# LOGIN
LoginCheck:
    pattern:  /connexion/login.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:loginCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

LostPasswordCheck:
    pattern:  /connexion/mot-de-passe-perdu.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:lostPasswordCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

GetPTags:
    pattern:  /citoyen/getTags.{_format}
    defaults: { _controller: PolitizrFrontBundle:Profile:getPTags, _format: json }
    requirements: { _format: (xml|json), _method: POST }
