# HWIOAUTHBUNDLE
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

OAuth:
    resource: "./routing/SecurityOAuth.yml"
    prefix:   /oauth/

# Security
Security:
    resource: "./routing/Security.yml"

# PUBLIQUE
Public:
    resource: "./routing/Public.yml"

# RECHERCHE
Search:
    resource: "./routing/Search.yml"

# DOCUMENT
Document:
    resource: "./routing/Document.yml"

# DOCUMENT
User:
    resource: "./routing/User.yml"

################################################################################
#				ROUTING XHR 
################################################################################

# GENERIC
XhrGeneric:
    pattern:  /{xhrRoute}/{xhrService}/{xhrMethod}.{xhrType}.json
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrGeneric:xhr }
    requirements:
        _method:        POST
        xhrRoute:       ".+"
        xhrType:        \d

# LOGIN & INSCRIPTION & ACCOUNT
XhrInscription:
    resource: "./routing/xhr/Inscription.yml"

# GESTION TAGS
XhrTag:
    resource: "./routing/xhr/Tag.yml"

# GESTION USER
XhrUser:
    resource: "./routing/xhr/User.yml"

# GESTION MODAL
XhrModal:
    resource: "./routing/xhr/Modal.yml"
