# HWIOAUTHBUNDLE
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

OAuth:
    resource: "./routing/SecurityOAuth.yml"
    prefix:   /oauth/

# Security
Security:
    resource: "./routing/Security.yml"

# PUBLIQUE
Public:
    resource: "./routing/Public.yml"

# RECHERCHE
Search:
    resource: "./routing/Search.yml"

# DOCUMENT
Document:
    resource: "./routing/Document.yml"

# DOCUMENT
User:
    resource: "./routing/User.yml"

# GENERIC XHR
XhrGeneric:
    pattern:  /xhr/{xhrRoute}/{xhrService}/{xhrMethod}.{xhrType}.json
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrGeneric:xhr }
    requirements:
        _method:        POST
        xhrRoute:       ".+"
        xhrType:        \d
