################################################################################
# 							HWIOAUTHBUNDLE
################################################################################
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

OAuth:
    resource: "@PolitizrFrontBundle/Resources/config/routingSecurityOAuth.yml"
    prefix:   /oauth/


################################################################################
#				ROUTING PUBLIQUE
################################################################################
Homepage:
    pattern:  /
    defaults: { _controller: PolitizrFrontBundle:Public:homepage }

Presentation:
    pattern:  /presentation
    defaults: { _controller: PolitizrFrontBundle:Public:presentation }

################################################################################
#               ROUTING CONNEXION
################################################################################
Login:
    pattern:  /login
    defaults: { _controller: PolitizrFrontBundle:Security:login }

Logout:
    pattern:  /logout

################################################################################
#               ROUTING CREATION PROFIL CITOYEN
################################################################################
Inscription:
    pattern:  /inscription
    defaults: { _controller: PolitizrFrontBundle:Security:inscription }

InscriptionCheck:
    pattern:  /inscription/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionCheck }

InscriptionContact:
    pattern:  /u/inscription-contact
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContact }

InscriptionContactCheck:
    pattern:  /u/inscription-contact/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionContactCheck }

################################################################################
#               ROUTING CREATION PROFIL ÉLU
################################################################################
InscriptionElected:
    pattern:  /inscription-elu
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElected }

InscriptionElectedCheck:
    pattern:  /inscription-elu/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedCheck }

InscriptionElectedOrder:
    pattern:  /v/inscription-elu-commande
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedOrder }

InscriptionElectedOrderCheck:
    pattern:  /v/inscription-elu-commande/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedOrderCheck }

InscriptionElectedPayment:
    pattern:  /v/inscription-elu-paiement
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPayment }

InscriptionElectedPaymentCheck:
    pattern:  /v/inscription-elu-paiement/check
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentCheck }

InscriptionElectedPaymentFinished:
    pattern:  /v/inscription-elu-paiement-termine
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentFinished }

InscriptionElectedPaymentCanceled:
    pattern:  /v/inscription-elu-paiement-annule
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedPaymentCanceled }

InscriptionElectedThanking:
    pattern:  /v/inscription-elu-remerciement
    defaults: { _controller: PolitizrFrontBundle:Security:inscriptionElectedThanking }

MigrationElected:
    pattern:  /citoyen/migration-elu
    defaults: { _controller: PolitizrFrontBundle:Security:migrationElected }

MigrationElectedCheck:
    pattern:  /citoyen/check
    defaults: { _controller: PolitizrFrontBundle:Security:migrationElectedCheck }



################################################################################
#				ROUTING DOCUMENT
################################################################################
DebateFeed:
    pattern:  /{id}/debat/fil/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateFeed }
    requirements:
        _method:        GET
        id:             \d+

DebateDetail:
    pattern:  /{id}/debat/detail/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:debateDetail }
    requirements:
        _method:        GET
        id:             \d+

ReactionDetail:
    pattern:  /{id}/reaction/detail/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDetail }
    requirements:
        _method:        GET
        id:             \d+

UserDetail:
    pattern:  /{id}/auteur/{slug}
    defaults: { _controller: PolitizrFrontBundle:Document:userDetail }
    requirements:
        _method:        GET
        id:             \d+


################################################################################
#               ROUTING CITOYEN
################################################################################
HomepageC:
    pattern:  /citoyen
    defaults: { _controller: PolitizrFrontBundle:ProfileC:homepage }

TimelineC:
    pattern:  /citoyen/timeline
    defaults: { _controller: PolitizrFrontBundle:ProfileC:timeline }

SuggestionsC:
    pattern:  /citoyen/suggestions
    defaults: { _controller: PolitizrFrontBundle:ProfileC:suggestions }

PopularsC:
    pattern:  /citoyen/populaires
    defaults: { _controller: PolitizrFrontBundle:ProfileC:populars }

LastC:
    pattern:  /citoyen/derniers
    defaults: { _controller: PolitizrFrontBundle:ProfileC:last }


MyRatesC:
    pattern:  /citoyen/mes-contributions
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myRates }

MyDraftsC:
    pattern:  /citoyen/mes-contributions/brouillons
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myDrafts }


MyDebatesC:
    pattern:  /citoyen/mes-contributions/debats
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myDebates }

MyCommentsC:
    pattern:  /citoyen/mes-contributions/commentaires
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myComments }


MyAccountC:
    pattern:  /citoyen/mon-compte
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myAccount }

MyTagsC:
    pattern:  /citoyen/mon-compte/mes-tags
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myTags }

MyReputationC:
    pattern:  /citoyen/mon-compte/ma-reputation
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myReputation }

MyPersoC:
    pattern:  /citoyen/mon-compte/mes-informations-personnelles
    defaults: { _controller: PolitizrFrontBundle:ProfileC:myPerso }

################################################################################
#               ROUTING ELU
################################################################################
HomepageE:
    pattern:  /elu
    defaults: { _controller: PolitizrFrontBundle:ProfileE:homepage }

TimelineE:
    pattern:  /elu/timeline
    defaults: { _controller: PolitizrFrontBundle:ProfileE:timeline }

SuggestionsE:
    pattern:  /elu/suggestions
    defaults: { _controller: PolitizrFrontBundle:ProfileE:suggestions }

PopularsE:
    pattern:  /elu/populaires
    defaults: { _controller: PolitizrFrontBundle:ProfileE:populars }

LastE:
    pattern:  /elu/derniers
    defaults: { _controller: PolitizrFrontBundle:ProfileE:last }


MyRatesE:
    pattern:  /elu/mes-contributions
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myRates }

MyDraftsE:
    pattern:  /elu/mes-contributions/brouillons
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myDrafts }

MyDebatesE:
    pattern:  /elu/mes-contributions/debats
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myDebates }

MyReactionsE:
    pattern:  /elu/mes-contributions/reactions
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myReactions }

MyCommentsE:
    pattern:  /elu/mes-contributions/commentaires
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myComments }


MyAccountE:
    pattern:  /elu/mon-compte
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myAccount }

MyTagsE:
    pattern:  /elu/mon-compte/mes-tags
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myTags }

MyReputationE:
    pattern:  /elu/mon-compte/ma-reputation
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myReputation }

MyPersoE:
    pattern:  /elu/mon-compte/mes-informations-personnelles
    defaults: { _controller: PolitizrFrontBundle:ProfileE:myPerso }


ReactionDraftPreview:
    pattern:  /elu/{id}/brouillon/reaction/detail
    defaults: { _controller: PolitizrFrontBundle:Document:reactionDraft }
    requirements:
        _method:        GET
        id:             \d+

ReactionDraftNew:
    pattern:  /elu/{debateId}/{parentId}/mes-reactions/nouvelle
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionNew }
    requirements:
        _method:        GET
        debateId:       \d+
        parentId:       \d*

ReactionDraftEdit:
    pattern:  /elu/mes-reactions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionEdit }
    requirements:
        _method:        GET
        id:             \d+


################################################################################
#               ROUTING CITOYEN OU ELU
################################################################################
DebateDraftPreview:
    pattern:  /profil/{id}/brouillon/debat/detail
    defaults: { _controller: PolitizrFrontBundle:Document:debateDraft }
    requirements:
        _method:        GET
        id:             \d+

DebateDraftNew:
    pattern:  /profil/mes-contributions/nouveau
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateNew }

DebateDraftEdit:
    pattern:  /profil/mes-contributions/{id}/edition
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateEdit }
    requirements:
        _method:        GET
        id:             \d+



################################################################################
################################################################################
#				ROUTING AJAX
################################################################################
################################################################################


################################################################################
# LOGIN
################################################################################
LoginCheck:
    pattern:  /connexion/login.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:loginCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

LostPasswordCheck:
    pattern:  /connexion/mot-de-passe-perdu.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:lostPasswordCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# INSCRIPTION ELU / PAIEMENT
################################################################################
PaymentProcess:
    pattern:  /v/paymentProcess.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:paymentProcess, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# CONSULTATION DEBAT / REACTION
################################################################################
GetDescriptionPDocument:
    pattern:  /getDescriptionPDocument.{_format}
    defaults: { _controller: PolitizrFrontBundle:Document:getDescriptionPDocument, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# SUIVI DEBAT / USER
################################################################################
Follow:
    pattern:  /follow.{_format}
    defaults: { _controller: PolitizrFrontBundle:Document:follow, _format: json }
    requirements: { _format: (xml|json), _method: POST }

Unfollow:
    pattern:  /unfollow.{_format}
    defaults: { _controller: PolitizrFrontBundle:Document:unfollow, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# GESTION TAGS
################################################################################
GetTags:
    pattern:  /getTags.{_format}
    defaults: { _controller: PolitizrFrontBundle:Public:getTags, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateAddTag:
    pattern:  /debat/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateDeleteTag:
    pattern:  /debat/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserFollowAddTag:
    pattern:  /user/follow/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userFollowAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserFollowDeleteTag:
    pattern:  /user/follow/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userFollowDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserTaggedAddTag:
    pattern:  /user/tagged/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userTaggedAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserTaggedDeleteTag:
    pattern:  /user/tagged/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userTaggedDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# GESTION INFOS PERSOS
################################################################################
PersoCheck:
    pattern:  /profil/perso.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userPersoUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserPhotoUpload:
    pattern:  /profil/upload-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userPhotoUpload, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserPhotoDelete:
    pattern:  /profil/delete-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userPhotoDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# EDITION DEBAT
################################################################################
DebateUpdate:
    pattern:  /profil/debat/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebatePublish:
    pattern:  /profil/debat/publish.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debatePublish, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateDelete:
    pattern:  /profil/debat/delete.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebatePhotoUpload:
    pattern:  /profil/debat/upload-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debatePhotoUpload, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebatePhotoDelete:
    pattern:  /profil/debat/delete-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debatePhotoDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# EDITION REACTION
################################################################################
ReactionUpdate:
    pattern:  /elu/reaction/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

ReactionPublish:
    pattern:  /elu/reaction/publish.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionPublish, _format: json }
    requirements: { _format: (xml|json), _method: POST }

ReactionDelete:
    pattern:  /elu/reaction/delete.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }

