# HWIOAUTHBUNDLE
OAuthRegister:
    pattern:  /oauthRegister
    defaults: { _controller: PolitizrFrontBundle:Security:oauthRegister }

OAuth:
    resource: "./routing/SecurityOAuth.yml"
    prefix:   /oauth/

# PUBLIQUE
Public:
    resource: "./routing/Public.yml"

# RECHERCHE
Search:
    resource: "./routing/Search.yml"

# LOGIN & INSCRIPTION & ACCOUNT
User:
    resource: "./routing/Inscription.yml"

# DOCUMENT
Document:
    resource: "./routing/Document.yml"

# CITOYEN
Citizen:
    resource: "./routing/Citizen.yml"

# ELU
Elected:
    resource: "./routing/Elected.yml"

################################################################################
#				ROUTING XHR 
################################################################################

# RECHERCHE
XhrSearch:
    resource: "./routing/xhr/Search.yml"

# LOGIN & INSCRIPTION & ACCOUNT
XhrInscription:
    resource: "./routing/xhr/Inscription.yml"

# SUIVI DEBAT / USER
XhrFollow:
    resource: "./routing/xhr/Follow.yml"

# NOTATION DEBAT / REACTION / COMMENTAIRE
XhrNotation:
    resource: "./routing/xhr/Notation.yml"

# GESTION TAGS
XhrTag:
    resource: "./routing/xhr/Tag.yml"

# GESTION USER
XhrUser:
    resource: "./routing/xhr/User.yml"

# GESTION NOTIFICATIONS
XhrNotification:
    resource: "./routing/xhr/Notification.yml"

# GESTION MODAL
XhrModal:
    resource: "./routing/xhr/Modal.yml"

# DOCUMENT
XhrDocument:
    resource: "./routing/xhr/Document.yml"
