imports:
    - { resource: services/connection.yml }
    - { resource: services/tools.yml }
    - { resource: services/routing.yml }
    - { resource: services/functional.yml }
    - { resource: services/xhr.yml }
    - { resource: services/manager.yml }
    - { resource: services/listener.yml }
    - { resource: services/twig.yml }

parameters:
    fos_elastica.elastica_to_model_transformer.collection.class:  Politizr\FrontBundle\Lib\ElasticSearch\ElasticaToModelTransformerPropelCollection

services:
#     # FOS ELASTICA
#     politzr.provider.p_document:
#         class: Politizr\FrontBundle\Lib\ElasticSearch\Provider\PDocumentProvider
#         arguments:
#             - @fos_elastica.index.politizr.p_document
#             - @logger
#             - @fos_elastica.object_persister.politizr.p_document
#         tags:
#             - { name: fos_elastica.provider, index: politizr, type: p_document }
