parameters:
    politizr.oauth_user_provider.class:   	Politizr\Security\User\Provider\OAuthUserProvider

services:
    # CONNEXION
    hwi_oauth.user.provider.entity:
        class:                              HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    politizr.login_user_provider:
        class: 								Politizr\Security\User\Provider\PUserProvider

    politizr.oauth_user_provider:
        class: 								"%politizr.oauth_user_provider.class%"
        arguments: 							[ @service_container ]


    # LISTENERS
    politzr.listener.email:
        class:      Politizr\FrontBundle\Listener\EmailListener
        arguments:  [ @mailer, @templating, @logger, "%contact_email%", "%noreply_email%" ]
        tags:
            - { name: kernel.event_listener, event: lost_password_email }
            - { name: kernel.event_listener, event: upd_password_email }

    politzr.listener.reputation:
        class:      Politizr\FrontBundle\Listener\ReputationListener
        arguments:  [ @logger ]
        tags:
            - { name: kernel.event_listener, event: debate_publish }
            - { name: kernel.event_listener, event: reaction_publish }
            - { name: kernel.event_listener, event: comment_publish }
            - { name: kernel.event_listener, event: note_pos }
            - { name: kernel.event_listener, event: note_neg }
            - { name: kernel.event_listener, event: debate_follow }
            - { name: kernel.event_listener, event: debate_unfollow }
            - { name: kernel.event_listener, event: user_follow }
            - { name: kernel.event_listener, event: user_unfollow }


    # EXTENSIONS TWIG
    politzr.twig.politizr_extension:
        class: 								Politizr\FrontBundle\Twig\PolitizrExtension
        arguments: 							[ @service_container ]
        tags:
                                            - { name: twig.extension }
