parameters:
#    politizr_front.example.class: Politizr\FrontBundle\Example

services:
#    politizr_front.example:
#        class: %politizr_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
