parameters:
    politizr.oauth_user_provider.class:   	Politizr\Security\User\Provider\OAuthUserProvider

services:

    # CONNEXION
    hwi_oauth.user.provider.entity:
        class:                              HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    politizr.login_user_provider:
        class: 								Politizr\Security\User\Provider\PUserProvider

    politizr.oauth_user_provider:
        class: 								"%politizr.oauth_user_provider.class%"
        arguments: 							[ @service_container ]

    # EXTENSIONS TWIG
    politzr.twig.politizr_extension:
        class: 								Politizr\FrontBundle\Twig\PolitizrExtension
        arguments: 							[ @service_container ]
        tags:
                                            - { name: twig.extension }
