parameters:
    politizr.oauth_user_provider.class:   	Politizr\Security\User\Provider\OAuthUserProvider

services:
    # CONNEXION
    hwi_oauth.user.provider.entity:
        class:                              HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    politizr.login_user_provider:
        class: 								Politizr\Security\User\Provider\PUserProvider

    politizr.oauth_user_provider:
        class: 								"%politizr.oauth_user_provider.class%"
        arguments: 							[ @service_container ]


    # SERVICES ROUTING
    politizr.routing.ajax:
        class:                              Politizr\FrontBundle\Lib\Routing\AjaxCreateResponse
        arguments:                          [ @service_container ]


    # SERVICES METIERS
    politizr.service.security:
        class:                              Politizr\FrontBundle\Lib\Service\SecurityManager
        arguments:                          [ @service_container ]

    politizr.service.user:
        class:                              Politizr\FrontBundle\Lib\Service\UserManager
        arguments:                          [ @service_container ]

    politizr.service.document:
        class:                              Politizr\FrontBundle\Lib\Service\DocumentManager
        arguments:                          [ @service_container ]

    politizr.service.tag:
        class:                              Politizr\FrontBundle\Lib\Service\TagManager
        arguments:                          [ @service_container ]

    politizr.service.timeline:
        class:                              Politizr\FrontBundle\Lib\Service\TimelineManager
        arguments:                          [ @service_container ]


    # LISTENERS
    politzr.listener.email:
        class:      Politizr\FrontBundle\Listener\EmailListener
        arguments:  [ @mailer, @templating, @logger, "%contact_email%", "%noreply_email%" ]
        tags:
            - { name: kernel.event_listener, event: lost_password_email }
            - { name: kernel.event_listener, event: upd_password_email }

    politzr.listener.reputation:
        class:      Politizr\FrontBundle\Listener\ReputationListener
        arguments:  [ @logger ]
        tags:
            - { name: kernel.event_listener, event: debate_publish }
            - { name: kernel.event_listener, event: reaction_publish }
            - { name: kernel.event_listener, event: comment_publish }
            - { name: kernel.event_listener, event: note_pos }
            - { name: kernel.event_listener, event: note_neg }
            - { name: kernel.event_listener, event: debate_follow }
            - { name: kernel.event_listener, event: debate_unfollow }
            - { name: kernel.event_listener, event: user_follow }
            - { name: kernel.event_listener, event: user_unfollow }


    # EXTENSIONS TWIG
    politzr.twig.politizr_extension:
        class: 								Politizr\FrontBundle\Twig\PolitizrExtension
        arguments: 							[ @service_container ]
        tags:
                                            - { name: twig.extension }
