studio_echo_media_homepage:
#    pattern:  /{objectName}/{objectId}/{$mediaParameterConfigKey}
    pattern:  /
#    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:index, objectName: SlaviaVintage\Model\Product, objectId: 1, mediaParameterConfigKey: test }
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:index }
#    requirements:
#        objectName: \s+
#        objectId:   \d+
#        mediaParameterConfigKey:   \s+

# Upload / Display routes
studio_echo_media_display_zone:
    pattern:  /display/{mediaObjectId}/key/{mediaParameterConfigKey}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:displayZone }

# JSON routes
studio_echo_media_upload_file:
    pattern:  /upload-file/upload.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:upload, _format: json }
    requirements: { _format: (xml|json) }

studio_echo_media_delete_file:
    pattern: /delete-file/{mediaFileId}/{mediaParameterConfigKey}/delete.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:delete, _format: json }
    requirements: { _format: (xml|json), _method: GET }

studio_echo_media_online_file:
    pattern: /online-file/{mediaFileId}/online.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:online, _format: json }
    requirements: { _format: (xml|json), _method: GET }

studio_echo_media_edit_file:
    pattern: /edit-file/{mediaFileId}/edit.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:edit, _format: json }
    requirements: { _format: (xml|json), _method: POST }

studio_echo_media_sort:
    pattern: /sort-files/sort.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:sort, _format: json }
    requirements: { _format: (xml|json), _method: POST }
