services:
    politizr.form.type.document_localization:
        class: Politizr\FrontBundle\Form\Type\DocumentLocalizationType
        arguments:
            - @politizr.manager.localization
        tags:
            - { name: form.type }

    politizr.form.type.localization:
        class: Politizr\FrontBundle\Form\Type\LocalizationChoiceType
        arguments:
            - @politizr.manager.localization
        tags:
            - { name: form.type }

    politizr.form.type.localization.circonscription:
        class: Politizr\FrontBundle\Form\Type\LocalizationCirconscriptionChoiceType
        arguments:
            - @politizr.manager.localization
        tags:
            - { name: form.type }

    politizr.form.type.localization.region:
        class: Politizr\FrontBundle\Form\Type\LocalizationRegionChoiceType
        arguments:
            - @politizr.manager.localization
        tags:
            - { name: form.type }

    politizr.form.type.localization.department:
        class: Politizr\FrontBundle\Form\Type\LocalizationDepartmentChoiceType
        arguments:
            - @politizr.manager.localization
        tags:
            - { name: form.type }

    politizr.form.type.localization.city:
        class: Politizr\FrontBundle\Form\Type\LocalizationCityChoiceType
        arguments:
            - @politizr.manager.localization
        tags:
            - { name: form.type }

