services:
    politizr.form.type.localization:
        class: Politizr\FrontBundle\Form\Type\LocalizationChoiceType
        arguments:
            - @politizr.manager.localization
        tags:
            - { name: form.type }