services:
    politizr.functional.user:
        class: Politizr\FrontBundle\Lib\Functional\UserService
        arguments:
            - @politizr.manager.user
            - @logger

    politizr.functional.document:
        class: Politizr\FrontBundle\Lib\Functional\DocumentService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.document
            - @politizr.functional.tag
            - @router
            - @logger

    politizr.functional.reputation:
        class: Politizr\FrontBundle\Lib\Functional\ReputationService
        arguments:
            - @politizr.manager.reputation
            - @logger

    politizr.functional.security:
        class: Politizr\FrontBundle\Lib\Functional\SecurityService
        arguments:
            - @security.token_storage
            - @security.encoder_factory
            - @session
            - @kernel
            - @router
            - @event_dispatcher
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @politizr.manager.user
            - @politizr.manager.order
            - @politizr.tools.global
            - "%facebook_client_id%"
            - "%facebook_client_secret%"
            - "%twitter_api_key%"
            - "%twitter_api_secret%"
            - "%google_client_id%"
            - "%google_client_secret%"
            - @logger

    politizr.functional.timeline:
        class: Politizr\FrontBundle\Lib\Functional\TimelineService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @templating
            - @politizr.manager.user
            - @politizr.manager.document
            - @logger

    politizr.functional.tag:
        class: Politizr\FrontBundle\Lib\Functional\TagService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.tag
            - @logger

