services:
    politizr.functional.document:
        class: Politizr\FrontBundle\Lib\Functional\DocumentService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.document
            - @politizr.manager.tag
            - @politizr.functional.tag
            - @politizr.functional.localization
            - @router
            - @politizr.tools.global
            - @logger

    politizr.functional.user:
        class: Politizr\FrontBundle\Lib\Functional\UserService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.user
            - @politizr.functional.tag
            - @politizr.functional.localization
            - @router
            - @logger

    politizr.functional.security:
        class: Politizr\FrontBundle\Lib\Functional\SecurityService
        arguments:
            - @security.token_storage
            - @security.encoder_factory
            - @session
            - @kernel
            - @router
            - @event_dispatcher
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @politizr.manager.user
            - @politizr.manager.order
            - @politizr.tools.global
            - "%facebook_client_id%"
            - "%facebook_client_secret%"
            - "%twitter_api_key%"
            - "%twitter_api_secret%"
            - "%google_client_id%"
            - "%google_client_secret%"
            - @logger

    politizr.functional.timeline:
        class: Politizr\FrontBundle\Lib\Functional\TimelineService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.user
            - @politizr.manager.document
            - @logger

    politizr.functional.tag:
        class: Politizr\FrontBundle\Lib\Functional\TagService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.tag
            - @logger

    politizr.functional.localization:
        class: Politizr\FrontBundle\Lib\Functional\LocalizationService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.localization
            - @logger

    politizr.functional.facebook:
        class: Politizr\FrontBundle\Lib\Functional\FacebookService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - "%facebook_client_id%"
            - "%facebook_client_secret%"
            - "%facebook_page_id%"
            - "%facebook_graph_version%"
            - "%facebook_access_token%"
            - @router
            - @politizr.tools.global
            - @logger

    politizr.functional.notification:
        class: Politizr\FrontBundle\Lib\Functional\NotificationService
        arguments:
            - @politizr.manager.notification
            - @politizr.tools.global
            - @logger

    politizr.functional.circle:
        class: Politizr\FrontBundle\Lib\Functional\CircleService
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @politizr.manager.circle
            - @logger
