services:
    politizr.manager.user:
        class: Politizr\FrontBundle\Lib\Manager\UserManager
        arguments:
            - @kernel
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @politizr.tools.global
            - @logger

    politizr.manager.document:
        class: Politizr\FrontBundle\Lib\Manager\DocumentManager
        arguments:
            - @kernel
            - @politizr.manager.tag
            - @politizr.tools.global
            - @logger

    politizr.manager.tag:
        class: Politizr\FrontBundle\Lib\Manager\TagManager
        arguments: [ @logger ]

    politizr.manager.localization:
        class: Politizr\FrontBundle\Lib\Manager\LocalizationManager
        arguments: [ @logger ]

    politizr.manager.order:
        class: Politizr\FrontBundle\Lib\Manager\OrderManager
        arguments: [ @logger ]

    politizr.manager.notification:
        class: Politizr\FrontBundle\Lib\Manager\NotificationManager
        arguments:
            - @politizr.tools.global
            - @logger

    politizr.manager.monitoring:
        class: Politizr\FrontBundle\Lib\Manager\MonitoringManager
        arguments: [ @logger ]

    politizr.manager.event:
        class: Politizr\FrontBundle\Lib\Manager\EventManager
        arguments: [ @logger ]

    politizr.manager.circle:
        class: Politizr\FrontBundle\Lib\Manager\CircleManager
        arguments:
            - @politizr.tools.global
            - @logger

