services:
    # SERVICES UTILITAIRES
    politizr.tools.global:
        class: Politizr\FrontBundle\Lib\Tools\GlobalTools
        arguments:
            - @security.authorization_checker
            - @security.context
            - @request_stack
            - @session
            - @form.factory
            - @validator
            - @liip_imagine.controller
            - @liip_imagine.cache.manager
            - @logger

    # ID CHECK
    politizr.tools.idcheck:
        class: Politizr\FrontBundle\Lib\Tools\IdCheck
        arguments:
            - @security.token_storage
            - @event_dispatcher
            - "%idcheck_wsdl_url%"
            - "%idcheck_login%"
            - "%idcheck_password%"
            - @logger