services:
    # SERVICES UTILITAIRES
    politizr.tools.global:
        class: Politizr\FrontBundle\Lib\Tools\GlobalTools
        arguments:
            - @security.authorization_checker
            - @security.context
            - @form.factory
            - @validator
            - @liip_imagine.controller
            - @liip_imagine.cache.manager
            - @logger

