services:
    # SERVICES UTILITAIRES
    politizr.tools.global:
        class:                              Politizr\FrontBundle\Lib\Tools\GlobalTools
        arguments:                          [ @service_container ]

