services:
    twig.extension.text:
       class:           Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    politizr.twig.social:
        class:          Politizr\FrontBundle\Twig\PolitizrSocialExtension
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @router
            - @politizr.tools.global
            - @logger
        tags:
            - { name: twig.extension }

    politizr.twig.tag:
        class:          Politizr\FrontBundle\Twig\PolitizrTagExtension
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @router
            - @politizr.tools.global
            - @logger
        tags:
            - { name: twig.extension }

    politizr.twig.document:
        class:          Politizr\FrontBundle\Twig\PolitizrDocumentExtension
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @router
            - @politizr.functional.timeline
            - @form.factory
            - @politizr.tools.global
            - @logger
        tags:
            - { name: twig.extension }

    politizr.twig.user:
        class:          Politizr\FrontBundle\Twig\PolitizrUserExtension
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @router
            - @politizr.functional.document
            - @form.factory
            - @politizr.tools.global
            - @logger
        tags:
            - { name: twig.extension }

    politizr.twig.reputation:
        class:          Politizr\FrontBundle\Twig\PolitizrReputationExtension
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @router
            - @politizr.tools.global
            - @logger
        tags:
            - { name: twig.extension }

    politizr.twig.circle:
        class:          Politizr\FrontBundle\Twig\PolitizrCircleExtension
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @router
            - @politizr.functional.circle
            - @politizr.tools.global
            - @logger
        tags:
            - { name: twig.extension }

