services:
    politizr.xhr.general:
        class: Politizr\FrontBundle\Lib\Xhr\XhrGeneral
        arguments:
        arguments:
            - @security.token_storage
            - @event_dispatcher
            - @templating
            - @form.factory
            - @logger

    politizr.xhr.document:
        class: Politizr\FrontBundle\Lib\Xhr\XhrDocument
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @kernel
            - @session
            - @event_dispatcher
            - @templating
            - @form.factory
            - @router
            - @twig
            - @politizr.manager.user
            - @politizr.manager.document
            - @politizr.functional.document
            - @politizr.functional.localization
            - @politizr.functional.tag
            - @politizr.functional.facebook
            - @politizr.tools.global
            - @politizr.twig.document
            - @politizr.form.type.document_localization
            - @logger

    politizr.xhr.modal:
        class: Politizr\FrontBundle\Lib\Xhr\XhrModal
        arguments:
        arguments:
            - @security.token_storage
            - @templating
            - @logger

    politizr.xhr.bubble:
        class: Politizr\FrontBundle\Lib\Xhr\XhrBubble
        arguments:
        arguments:
            - @security.token_storage
            - @templating
            - @logger

    politizr.xhr.notification:
        class: Politizr\FrontBundle\Lib\Xhr\XhrNotification
        arguments:
            - @security.token_storage
            - @templating
            - @politizr.manager.user
            - @politizr.manager.notification
            - @logger

    politizr.xhr.security:
        class: Politizr\FrontBundle\Lib\Xhr\XhrSecurity
        arguments:
            - @security.token_storage
            - @security.encoder_factory
            - @kernel
            - @session
            - @event_dispatcher
            - @templating
            - @form.factory
            - @router
            - @politizr.functional.security
            - @politizr.manager.order
            - @politizr.tools.global
            - @politizr.tools.idcheck
            - @logger

    politizr.xhr.tag:
        class: Politizr\FrontBundle\Lib\Xhr\XhrTag
        arguments:
            - @security.token_storage
            - @router
            - @templating
            - @event_dispatcher
            - @politizr.functional.tag
            - @politizr.manager.tag
            - @logger

    politizr.xhr.localization:
        class: Politizr\FrontBundle\Lib\Xhr\XhrLocalization
        arguments:
            - @security.token_storage
            - @templating
            - @form.factory
            - @politizr.functional.localization
            - @politizr.manager.localization
            - @logger

    politizr.xhr.user:
        class: Politizr\FrontBundle\Lib\Xhr\XhrUser
        arguments:
            - @security.token_storage
            - @security.encoder_factory
            - @kernel
            - @event_dispatcher
            - @templating
            - @router
            - @twig
            - @form.factory
            - @fos_user.util.email_canonicalizer
            - @politizr.manager.user
            - @politizr.manager.localization
            - @politizr.functional.user
            - @politizr.functional.localization
            - @politizr.functional.timeline
            - @politizr.tools.global
            - @politizr.twig.user
            - @logger

    politizr.xhr.monitoring:
        class: Politizr\FrontBundle\Lib\Xhr\XhrMonitoring
        arguments:
            - @security.token_storage
            - @templating
            - @form.factory
            - @event_dispatcher
            - @logger

    politizr.xhr.organization:
        class: Politizr\FrontBundle\Lib\Xhr\XhrOrganization
        arguments:
        arguments:
            - @security.token_storage
            - @router
            - @templating
            - @logger
