################################################################################
#               EDITION DEBAT + REACTION
################################################################################
DocumentPhotoUpload:
    pattern:  /profil/document/upload-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:documentPhotoUpload, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DocumentPhotoDelete:
    pattern:  /profil/document/delete-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:documentPhotoDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }


################################################################################
#               EDITION DEBAT
################################################################################
DebateUpdate:
    pattern:  /profil/debat/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:debateUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebatePhotoInfoUpdate:
    pattern:  /profil/debat/photo-info/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:debatePhotoInfoUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebatePublish:
    pattern:  /profil/debat/publish.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:debatePublish, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateDelete:
    pattern:  /profil/debat/delete.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:debateDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               EDITION REACTION
################################################################################
ReactionUpdate:
    pattern:  /elu/reaction/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:reactionUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

ReactionPhotoInfoUpdate:
    pattern:  /profil/reaction/photo-info/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:reactionPhotoInfoUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

ReactionPublish:
    pattern:  /elu/reaction/publish.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:reactionPublish, _format: json }
    requirements: { _format: (xml|json), _method: POST }

ReactionDelete:
    pattern:  /elu/reaction/delete.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:reactionDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }


################################################################################
#               EDITION COMMENTAIRE
################################################################################
Comments:
    pattern:  /comments.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:comments, _format: json }
    requirements: { _format: (xml|json), _method: POST }

CommentNew:
    pattern:  /profil/commentaire/new.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrDocument:commentNew, _format: json }
    requirements: { _format: (xml|json), _method: POST }

