################################################################################
#               EDITION DEBAT + REACTION
################################################################################
DocumentPhotoUpload:
    pattern:  /profil/document/upload-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:documentPhotoUpload, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DocumentPhotoDelete:
    pattern:  /profil/document/delete-photo.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:documentPhotoDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }


################################################################################
#               EDITION DEBAT
################################################################################
DebateUpdate:
    pattern:  /profil/debat/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebatePublish:
    pattern:  /profil/debat/publish.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debatePublish, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateDelete:
    pattern:  /profil/debat/delete.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               EDITION REACTION
################################################################################
ReactionUpdate:
    pattern:  /elu/reaction/update.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionUpdate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

ReactionPublish:
    pattern:  /elu/reaction/publish.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionPublish, _format: json }
    requirements: { _format: (xml|json), _method: POST }

ReactionDelete:
    pattern:  /elu/reaction/delete.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:reactionDelete, _format: json }
    requirements: { _format: (xml|json), _method: POST }


################################################################################
#               EDITION COMMENTAIRE
################################################################################
Comments:
    pattern:  /comments.{_format}
    defaults: { _controller: PolitizrFrontBundle:Document:comments, _format: json }
    requirements: { _format: (xml|json), _method: POST }

CommentNew:
    pattern:  /profil/commentaire/new.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:commentNew, _format: json }
    requirements: { _format: (xml|json), _method: POST }

