################################################################################
# LOGIN
################################################################################
LoginCheck:
    pattern:  /connexion/login.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:loginCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

LostPasswordCheck:
    pattern:  /connexion/mot-de-passe-perdu.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:lostPasswordCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# INSCRIPTION ELU / PAIEMENT
################################################################################
PaymentProcess:
    pattern:  /v/paymentProcess.{_format}
    defaults: { _controller: PolitizrFrontBundle:Security:paymentProcess, _format: json }
    requirements: { _format: (xml|json), _method: POST }

