################################################################################
# LOGIN
################################################################################
Login:
    pattern:  /login.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrSecurity:login, _format: json }
    requirements: { _format: (xml|json), _method: POST }

LoginCheck:
    pattern:  /connexion/login.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrSecurity:loginCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

LostPasswordCheck:
    pattern:  /connexion/mot-de-passe-perdu.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrSecurity:lostPasswordCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
# INSCRIPTION ELU / PAIEMENT
################################################################################
PaymentProcess:
    pattern:  /v/paymentProcess.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrSecurity:paymentProcess, _format: json }
    requirements: { _format: (xml|json), _method: POST }

