################################################################################
#               TIMELINE
################################################################################
TimelinePaginated:
    pattern:  /profil/timeline/paginated.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrListing:timelinePaginated, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               PLUS DE DEBATS / DE DEBATTEURS
################################################################################
DailyDebateList:
    pattern:  /profil/debat/evenements.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrListing:dailyDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DailyUserList:
    pattern:  /profil/user/evenements.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrListing:dailyUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               REPUTATION
################################################################################
HistoryActionsList:
    pattern:  /profil/reputation/historique.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrListing:historyActionsList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               DEBATS SUIVIS / PROFILS SUIVIS
################################################################################
FollowedDebateList:
    pattern:  /profil/debat/suivis.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrListing:followedDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

FollowedUserList:
    pattern:  /profil/user/suivis.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrListing:followedUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               DEBATS SUIVIS / PROFILS SUIVIS
################################################################################
OrganizationUserList:
    pattern:  /organisation.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrListing:organizationUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }
