################################################################################
#               MODAL
################################################################################
ModalPaginatedList:
    pattern:  /modal/paginated.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:modalPaginatedList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

Filters:
    pattern:  /profil/classement/filtres.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:filters, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               CLASSEMENTS
################################################################################
RankingDebateList:
    pattern:  /profil/debat/classement.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:rankingDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

RankingUserList:
    pattern:  /profil/user/classement.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:rankingUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               SUGGESTIONS
################################################################################
SuggestionDebateList:
    pattern:  /profil/debat/suggestion.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:suggestionDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

SuggestionUserList:
    pattern:  /profil/user/suggestion.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:suggestionUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               TAGS
################################################################################
TagDebateList:
    pattern:  /debat/tag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:tagDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

TagUserList:
    pattern:  /user/tag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:tagUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               ORGANISATIONS
################################################################################
OrganizationUserList:
    pattern:  /organisation.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:organizationUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               DEBATS SUIVIS / PROFILS SUIVIS
################################################################################
FollowedDebateList:
    pattern:  /profil/debat/suivis.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:followedDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

FollowedUserList:
    pattern:  /profil/user/suivis.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:followedUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               REPUTATION
################################################################################
HistoryActionsList:
    pattern:  /profil/reputation/historique.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:historyActionsList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

