################################################################################
#               MODAL
################################################################################
ModalPaginatedList:
    pattern:  /modal/paginated.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:modalPaginatedList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               TIMELINE
################################################################################
TimelinePaginated:
    pattern:  /profil/timeline/paginated.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:timelinePaginated, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               PLUS DE DEBATS / DE DEBATTEURS
################################################################################
DailyDebateList:
    pattern:  /profil/debat/evenements.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:dailyDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DailyUserList:
    pattern:  /profil/user/evenements.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:dailyUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               REPUTATION
################################################################################
HistoryActionsList:
    pattern:  /profil/reputation/historique.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:historyActionsList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               DEBATS SUIVIS / PROFILS SUIVIS
################################################################################
FollowedDebateList:
    pattern:  /profil/debat/suivis.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:followedDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

FollowedUserList:
    pattern:  /profil/user/suivis.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:followedUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               ORGANISATIONS
################################################################################
OrganizationUserList:
    pattern:  /organisation.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:organizationUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

################################################################################
#               TAGS
################################################################################
TagDebateList:
    pattern:  /debat/tag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:tagDebateList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

TagUserList:
    pattern:  /user/tag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrModal:tagUserList, _format: json }
    requirements: { _format: (xml|json), _method: POST }

