################################################################################
#               ROUTING XHR GESTION TAGS
################################################################################
GetTags:
    pattern:  /getTags.{_format}
    defaults: { _controller: PolitizrFrontBundle:Public:getTags, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateAddTag:
    pattern:  /debat/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateDeleteTag:
    pattern:  /debat/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:debateDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserFollowAddTag:
    pattern:  /user/follow/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userFollowAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserFollowDeleteTag:
    pattern:  /user/follow/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userFollowDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserTaggedAddTag:
    pattern:  /user/tagged/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userTaggedAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserTaggedDeleteTag:
    pattern:  /user/tagged/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:CRUD:userTaggedDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

