################################################################################
#               ROUTING XHR GESTION TAGS
################################################################################
DebateAddTag:
    pattern:  /debat/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrTag:debateAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

DebateDeleteTag:
    pattern:  /debat/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrTag:debateDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserFollowAddTag:
    pattern:  /user/follow/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrTag:userFollowAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserFollowDeleteTag:
    pattern:  /user/follow/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrTag:userFollowDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserTaggedAddTag:
    pattern:  /user/tagged/addtag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrTag:userTaggedAddTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

UserTaggedDeleteTag:
    pattern:  /user/tagged/deletetag.{_format}
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrTag:userTaggedDeleteTag, _format: json }
    requirements: { _format: (xml|json), _method: POST }

