
# Insertion des discussions
INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (1, 1, 'Agriculture', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'agriculture');

INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (2, 1, 'Culture', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'culture');

INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (3, 1, 'Économie', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'economie');

INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (4, 1, 'Éducation', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'education');

INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (5, 1, 'Jeunesse', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'jeunesse');

INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (6, 1, 'Solidarité', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'solidarite');

INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (7, 1, 'Sport', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'sport');

INSERT INTO `p_c_topic` (`id`, `p_circle_id`, `title`, `summary`, `description`, `online`, `created_at`, `updated_at`, `slug`) 
VALUES (8, 1, 'Tranports', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', '<p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine Alamanna pontem suspendere navium conpage Romani vi nimia vetabantur ritu grandinis undique convolantibus telis, et cum id inpossibile videretur, imperator cogitationibus magnis attonitus, quid capesseret ambigebat.</p>', 1, '2017-09-08 14:38:56', '2017-09-08 14:38:56', 'transports');

# app/console politizr:uuids:populate PCTopic

# Insertion de sujets tests

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (1, 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (3, 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (4, 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (5, 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');


INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (6, 2, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (7, 2, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (8, 2, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (9, 2, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');


INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (10, 3, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (11, 3, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (13, 3, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (14, 3, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');



INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (15, 4, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (16, 4, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (17, 4, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (18, 4, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');



INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (19, 5, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (21, 5, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (22, 5, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (23, 5, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');



INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (24, 6, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (26, 6, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (27, 6, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (28, 6, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');



INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (29, 7, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (30, 7, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (31, 7, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (32, 7, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');



INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (33, 8, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (34, 8, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (36, 8, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `created_at`, `updated_at`) 
VALUES (37, 8, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula. Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu. Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.', 1, 'Lionel Bouzonville', 1, '2017-09-11 16:32:02', '2017-09-11 16:32:02');



# app/console politizr:uuids:populate PDDebate
