generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\CmsContentAdmin
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    credentials:            ROLE_SYSTEM
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        title:
            label:          Titre
        description:
            label:          Description
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des contenus admin
            max_per_page:                       10
            sort:                               [ id, ASC ]
            display:                            [ id, title, created_at, updated_at ]
            # filtersMode:                        modal
            filters:                            null
            object_actions:
                show:                           ~
                edit:                           ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    edit:
        params:
            title:                              "Edition de la page '{{ CmsContentAdmin.title }}'"
            tabs:
                "Contenu":
                    "En-tête":                  [ title ]
                    "Texte":                    [ description ]
                "Médias":
                    "Galerie":                  [ media_bundle ]
                    "Documents":                [ media_bundle_documents ]
                "Attributs":
                    "Dates":                    [ [ created_at, updated_at ] ]
            fields:
                media_bundle:
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                media_bundle_documents:
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { rows: 25 }
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save: ~
                list: ~
                delete: ~
    show:
        params:
            title:                              "Visualisation de la page '{{ CmsContentAdmin.title }}'"
            tabs:
                "Contenu":
                    "En-tête":                  [ title ]
                    "Texte":                    [ description ]
                "Attributs":
                    "Dates":                    [ [ created_at, updated_at ] ]
            actions:
                list:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete:                         ~
            batch_actions:
                delete:                         ~