generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\CmsInfo
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        title:
            label:          Titre
        description:
            label:          Description
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des flash actualités
            max_per_page:                       10
            sort:                               [ sortable_rank, ASC ]
            display:                            [ title, online ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
                moveUp:                         ~
                moveDown:                       ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'une actu flash"
            display:
                "Champs principaux":            [ title ]
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de l'actu '{{ CmsInfo.title }}'"
            tabs:
                "Contenu":
                    "En-tête":                  [ title ]
                    "Texte":                    [ description ]
                "Attributs":
                    "Caractéristiques":         [ online ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            fields:
                description:
                    addFormOptions:
                        attr:                   { class: tinymce }
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save: ~
                list: ~
                delete: ~
    show:
        params:
            title:                              "Visualisation de l'actu' '{{ CmsInfo.title }}'"
            tabs:
                "Contenu":
                    "En-tête":                  [ title ]
                    "Texte":                    [ description ]
                "Attributs":
                    "Caractéristiques":         [ online ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            actions:
                list:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moveUp:                         ~
                moveDown:                       ~
                delete:                         ~
            batch_actions:
                delete:                         ~