generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PCircle
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        title:
            label:          Titre
        summary:
            label:          Résumé
        description:
            label:          Description
        url:
            label:          URL
        online:
            label:          En ligne
        only_elected:
            label:          Élus seulement
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des groupes
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            display:                            [ title, id, online, created_at ]
            filtersMode:                        modal
            filters:                            [ id, uuid, title, online, created_at ]
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
            actions:
                new:                            ~
    new:
        params:
            title:                              "Création d'un groupe"
            display:
                "Champs principaux":            [ title ]
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du groupe '{{ PCircle.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ title, summary, description ]
                "Options":
                    "Adresse":                  [ url ]
                    "Restrictions":             [ only_elected ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "En ligne":                 [ online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                summary:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du groupe '{{ PCircle.getTitle }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ title, summary, description ]
                "Options":
                    "Adresse":                  [ url ]
                    "Restrictions":             [ only_elected ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "En ligne":                 [ online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_p_circle:
                    label:                      "Groupe"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                homepage:                       ~
                delete: ~
            batch_actions:
                homepage:                       ~
                delete: ~
