generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PCircleType
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    credentials:            ROLE_SYSTEM
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        title:
            label:          Titre
        summary:
            label:          Description
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des types de consultation
            max_per_page:                       50
            sort:                               [ id, ASC ]
            display:                            [ title, summary ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'un type de consultation"
            display:
                "Champs principaux":            [ [ title ] ]
                "Champs complémentaires":       [ [ summary ] ]
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du type de consultation '{{ PCircleType.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ], [ summary ] ]
                "Attributs":
                    "Dates":                 [ [ created_at, updated_at ] ]
            fields:
                created_at:
                    formType:                   datetime
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    formType:                   datetime
                    addFormOptions:
                      widget:                   single_text
            actions:
                save: ~
                list: ~
    show:
        params:
            title:                              "Visualisation du type de consultation '{{ PCircleType.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ], [ summary ] ]
                "Attributs":
                    "Dates":                 [ [ created_at, updated_at ] ]
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
