generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PCircle
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_c_owner_id:
            label:          ID Propriétaire
        p_c_owner:
            label:          Propriétaire
        p_circle_type_id:
            label:          ID Type
        p_circle_type:
            label:          Type
        uuid:
            label:          UUID
        slug:
            label:          Slug
        logo_file_name:
            label:          Logo
        title:
            label:          Titre
        summary:
            label:          Informations
        description:
            label:          Description
        url:
            label:          URL
        read_only:
            label:          Lecture seule
        online:
            label:          En ligne
        private_access:
            label:          Accès privé
        public_circle:
            label:          Accès public
        open_reaction:
            label:          Réactions ouvertes
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des consultations
            max_per_page:                       50
            sort:                               [ sortable_rank, ASC ]
            display:                            [ title, p_c_owner, p_circle_type, online, read_only, private_access, created_at ]
            filtersMode:                        modal
            filters:                            [ id, p_c_owner, p_circle_type, uuid, title, online, read_only, private_access ]
            fields:
                p_circle_type:
                    credentials:                ROLE_SYSTEM
            object_actions:
                show:                           ~
                edit:                           ~
                scope:
                    label:                      Autorisations
                    icon:                       fa-users
                delete:                         ~
                moveUp:                         ~
                moveDown:                       ~
            actions:
                new:                            ~
    new:
        params:
            title:                              "Création d'une consultation"
            display:
                "Champs principaux":            [ p_c_owner, p_circle_type, title ]
                "Portée":                       [ private_access ]
            fields:
                p_c_owner:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PCOwner
                        query:                  \Politizr\Model\PCOwnerQuery::create()->orderByTitle()
                p_circle_type:
                    credentials:                ROLE_SYSTEM
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de la consultation '{{ PCircle.title }}'"
            tabs:
                "Contenu":
                    "Logo":                     [ block_logo_file_name ]
                    "Texte":                    [ [ title, summary ], description ]
                "Contexte":
                    "Propriétaire":             [ p_c_owner ]
                    "Offre":                    [ p_circle_type ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "État":                     [ open_reaction, read_only, online ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            fields:
                block_logo_file_name:
                    credentials:                ROLE_SYSTEM
                    label:                      "Image"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                summary:
                    credentials:                ROLE_SYSTEM
                    grid_class:                 "col-md-8"
                description:
                    addFormOptions:
                        attr:                   { class : tinymce }
                p_circle_type:
                    credentials:                ROLE_SYSTEM
                url:
                    credentials:                ROLE_SYSTEM
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    formType:                   datetime
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    formType:                   datetime
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de la consultation '{{ PCircle.getTitle }}'"
            tabs:
                "Contenu":
                    "Logo":                     [ block_logo_file_name ]
                    "Texte":                    [ title, summary, description ]
                "Contexte":
                    "Propriétaire":                   [ block_p_c_owner ]
                    "Offre":                    [ p_circle_type ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "État":                     [ open_reaction, read_only, online ]
                    "Restrictions":             [ public_circle, private_access ]
                    "Dates":                    [ [ created_at, updated_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                block_logo_file_name:
                    credentials:                ROLE_SYSTEM
                    label:                      "Image"
                block_p_c_owner:
                    label:                      "Propriétaire"
                p_circle_type:
                    credentials:                ROLE_SYSTEM
                url:
                    credentials:                ROLE_SYSTEM
                block_front:
                    label:                      "Rendu front"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moveUp:                         ~
                moveDown:                       ~
                delete: ~
                scope:  ~
            batch_actions:
                delete: ~
