generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PCircle
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_c_owner_id:
            label:          ID Client
        p_c_owner:
            label:          Client
        uuid:
            label:          UUID
        slug:
            label:          Slug
        logo_file_name:
            label:          Logo
        title:
            label:          Titre
        summary:
            label:          Résumé
        description:
            label:          Description
        url:
            label:          URL
        read_only:
            label:          Lecture seule
        online:
            label:          En ligne
        only_elected:
            label:          Élus seulement
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des groupes
            max_per_page:                       50
            sort:                               [ sortable_rank, ASC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Ariège Département":
                        default:                1
                        filters:
                            p_c_owner_id:       1
                    "Hospi-09":
                        filters:
                            p_c_owner_id:       2
            display:                            [ logo_file_name, title, p_c_owner, online, created_at ]
            filtersMode:                        modal
            filters:                            [ id, p_c_owner, uuid, title, online, created_at ]
            object_actions:
                show:                           ~
                edit:                           ~
                scope:                          ~
                delete:                         ~
                moveUp:                         ~
                moveDown:                       ~
            actions:
                new:                            ~
    new:
        params:
            title:                              "Création d'un groupe"
            display:
                "Champs principaux":            [ p_c_owner, title ]
            fields:
                p_c_owner:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PCOwner
                        query:                  \Politizr\Model\PCOwnerQuery::create()->orderByTitle()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du groupe '{{ PCircle.title }}'"
            tabs:
                "Contenu":
                    "Bandeau":                  [ uploadedLogoFileName ]
                    "Texte":                    [ title, summary, description ]
                "Objets":
                    "Client":                   [ p_c_owner ]
                "Options":
                    "Adresse":                  [ url ]
                    "Restrictions":             [ only_elected ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "En ligne":                 [ read_only, online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                uploadedLogoFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\SingleUploadType
                    addFormOptions:
                        deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                summary:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                description:
                    grid_class:                 "col-md-12"
                    # addFormOptions:
                    #     attr:                   { class : tinymce }
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du groupe '{{ PCircle.getTitle }}'"
            tabs:
                "Contenu":
                    "Bandeau":                  [ logo_file_name ]
                    "Texte":                    [ title, summary, description ]
                "Objets":
                    "Client":                   [ block_p_c_owner ]
                "Options":
                    "Adresse":                  [ url ]
                    "Restrictions":             [ only_elected ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "En ligne":                 [ online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_p_c_owner:
                    label:                      "Client"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moveUp:                         ~
                moveDown:                       ~
                delete: ~
                scope:  ~
            batch_actions:
                delete: ~
