generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PCTopic
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        title:
            label:          Titre
        p_circle_id:
            label:          Groupe
        p_circle:
            label:          Groupe
            addFormOptions:
                query:      \Politizr\Model\PCircleQuery::create()->orderByTitle()
        file_name:
            label:          Bandeau
        summary:
            label:          Résumé
        description:
            label:          Description
        online:
            label:          En ligne
        force_geoloc_type:
            label:          Geoloc type
        force_geoloc_id:
            label:          Geoloc id
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des discussions
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            display:                            [ file_name, title, id, p_circle, online, created_at ]
            filtersMode:                        modal
            filters:                            [ p_circle, uuid, title, online, created_at ]
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
            actions:
                new:                            ~
    new:
        params:
            title:                              "Création d'une discussion"
            display:
                "Champs principaux":            [ p_circle, title ]
            fields:
                p_circle:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PCircle
                        query:                  \Politizr\Model\PCircleQuery::create()->orderByTitle()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de la discussion '{{ PCTopic.title }}'"
            tabs:
                "Contenu":
                    "Bandeau":                  [ uploadedFileName ]
                    "Texte":                    [ title, summary, description ]
                "Objets":
                    "Groupe":                   [ p_circle ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Géoloc":                   [ [ force_geoloc_type, force_geoloc_id ]]
                    "En ligne":                 [ online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                uploadedFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\SingleUploadType
                    addFormOptions:
                        deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                summary:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                force_geoloc_type:
                    dbType:                     VARCHAR
                    formType:                   Symfony\Component\Form\Extension\Core\Type\ChoiceType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        choices:                
                            city:               Ville
                            department:         Département
                            region:             Région
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de la discussion '{{ PCTopic.getTitle }}'"
            tabs:
                "Contenu":
                    "Bandeau":                  [ file_name ]
                    "Texte":                    [ title, summary, description ]
                "Objets":
                    "Groupe":                   [ block_p_circle ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Géoloc":                   [ [ force_geoloc_type, force_geoloc_id ]]
                    "En ligne":                 [ online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_p_circle:
                    label:                      "Groupe"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                homepage:                       ~
                delete: ~
            batch_actions:
                homepage:                       ~
                delete: ~
