generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PCTopic
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        title:
            label:          Titre
        p_circle_id:
            label:          Consultation
        p_circle:
            label:          Consultation
            addFormOptions:
                query:      \Politizr\Model\PCircleQuery::create()->orderByRank()
        file_name:
            label:          Bandeau
        summary:
            label:          Accroche
        description:
            label:          Description
        online:
            label:          En ligne
        force_geoloc_type:
            label:          Type du zonage
        force_geoloc_id:
            label:          ID zone
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des discussions
            max_per_page:                       50
            sort:                               [ sortable_rank, ASC ]
            display:                            [ file_name, title, p_circle, online, created_at ]
            filtersMode:                        modal
            filters:                            [ p_circle, uuid, title, online ]
            object_actions:
                show:                           ~
                edit:                           ~
                localization:
                    credentials:                ROLE_SYSTEM
                    label:                      Localisation
                    icon:                       fa-map-marker
                delete:                         ~
                moveUp:                         ~
                moveDown:                       ~
            actions:
                new:                            ~
    new:
        params:
            title:                              "Création d'une discussion"
            display:
                "Champs principaux":            [ p_circle, title ]
            fields:
                p_circle:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PCircle
                        query:                  \Politizr\Model\PCircleQuery::create()->orderByTitle()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de la discussion '{{ PCTopic.title }}'"
            tabs:
                "Contenu":
                    "Bandeau":                  [ block_file_name ]
                    "Texte":                    [ title, summary, description ]
                "Contexte":
                    "Consultation":             [ p_circle ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "État":                     [ online ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            fields:
                block_file_name:
                    label:                      "Image"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                summary:
                    grid_class:                 "col-md-8"
                description:
                    addFormOptions:
                        attr:                   { class: tinymce }
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    formType:                   datetime
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    formType:                   datetime
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de la discussion '{{ PCTopic.getTitle }}'"
            tabs:
                "Contenu":
                    "Bandeau":                  [ block_file_name ]
                    "Texte":                    [ title, summary, description ]
                "Contexte":
                    "Consultation":             [ block_p_circle ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Localisation":             [ [ force_geoloc_type, force_geoloc_id ]]
                    "État":                     [ online ]
                    "Dates":                    [ [ created_at, updated_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                block_file_name:
                    label:                      "Image"
                block_p_circle:
                    label:                      "Consultation"
                block_front:
                    label:                      "Rendu front"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moveUp:                         ~
                moveDown:                       ~
                localization:                   ~
                delete:                         ~
            batch_actions:
                delete: ~
