generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDComment
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
        p_document_id:
            label:          ID Document associé
        p_document:
            label:          Document associé
        description:
            label:          Description
        paragraph_no:
            label:          Num. paragraphe
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des commentaires
            max_per_page:                       50
            sort:                               [ published_at, DESC ]
            scopes:
            display:                            [ id, p_user, p_document, type, description, paragraph_no, note_pos, note_neg, online, published_at ]
            fields:
                type:
                    label:          Type
                    getter:         PDocument.Type
                    dbType:         VARCHAR
#             actions:
#                 new:                            ~
            object_actions:
# TODO: prévoir un object_action mise en ligne / hors ligne plutôt que "delete"? 
#                 show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display:                            [ id, p_user_id, p_document_id, published_at, online, created_at ]
            fields:
                p_user:
                    addFormOptions:
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
#     new:
#         params:
#             title:                              "Création d'un commentaire de débat"
#             display:
#                 "Champs principaux":            [ [ p_user, p_document ], [ description ] ]
#                 "Champs complémentaires":       [ [ paragraph_no ], [ note_pos, note_neg ] ]
#             fields:
#                 p_user:
#                     addFormOptions:
#                         empty_value:            ""
#                         required:               false
#                         query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
#                 description:
#                     addFormOptions:
#                         attr:                   { class : tinymce }
#             actions:
#               save:                             ~
#               list:                             ~
    edit:
        params:
            title:                              "Edition du commentaire id-{{ PDComment.id }} sur {{ PDComment.PDocument.Type }} '{{ PDComment.PDocument }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ description ] ]
                    "Paragraphe":               [ [ paragraph_no ] ]
                "Objets":
                    "Utilisateur":              [ [ p_user ] ]
                    "Document":                 [ [ p_document ] ]
                "Statut":
                    "Publication":              [ [ published_by ], [ published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                p_user:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                description:
                    addFormOptions:
                        attr:                   { class : tinymce }
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                      widget:                   single_text
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save: ~
                list: ~
#     show:
#         params:
#             title:                              "Visualisation du commentaire id-{{ PDComment.id }} du débat '{{ PDComment.PDocument }}'"
#             tabs:
#                 "Contenu":
#                     "Texte":                    [ [ description ] ]
#                     "Paragraphe":               [ [ paragraph_no ] ]
#                 "Objets":
#                     "Utilisateur":              [ [ p_user ] ]
#                     "Document":                    [ [ p_document ] ]
#                 "Statut":
#                     "Publication":              [ [ published_by ], [ published_at ] ]
#                     "Notes":                    [ [ note_pos, note_neg ] ]
#                 "Attributs":
#                     "Création":                 [ [ online ], [ created_at, updated_at ] ]
#             actions:
#               list:                             ~
#               delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
