generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDDebate
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
            addFormOptions:
                query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
        file_name:
            label:          Image
        copyright:
            label:          Copyright
        title:
            label:          Titre
        description:
            label:          Description
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        moderated:
            label:          Modéré
        moderated_partial:
            label:          Modéré partiellement
        moderated_at:
            label:          Mis à jour
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des débats
            max_per_page:                       50
            sort:                               [ published_at, DESC ]
            scopes:
                group_1: 
                    "Publiés":
                        default:                1
                        filters:
                            published:          1
                    "Brouillons":
                        filters:
                            published:          0
            display:                            [ file_name, id, p_user_id, title, count_reactions, online, published, published_at, created_at ]
            filtersMode:                        modal
            filters:                            [ id, uuid, p_user_id, title, online, published, published_at, created_at ]
            fields:
                count_reactions:
                    label:                      Réactions
                PDDTaggedT:
                    dbType:                     model
                    formType:                   model
                    label:                      Tags associés
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PTag
                        query:                  \Politizr\Model\PTagQuery::create()->filterByOnline(1)->orderByTitle()
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    edit:
        params:
            title:                              "Edition du contenu débat '{{ PDDebate.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ block_file_name, copyright, title, description ]
                "Objets":
                    "Utilisateur":              [ p_user ]
                "Tags":
                    "Tags associés":            [ block_tags ]
                "Statut":
                    "Publication":              [ [ published, published_by, published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_partial, moderated_at ] ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                block_file_name:
                    label:                      "Image"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                copyright:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                block_tags:
                    label:                      "Tags"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                        widget:                 single_text
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                archive:
                    label:                      Archiver
                    icon:                       fa-archive
                    params:
                        pk:                     "{{ PDDebate.id }}"
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du contenu débat '{{ PDDebate.getTitle }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ block_file_name, copyright, title, description ]
                "Objets":
                    "Utilisateur":              [ block_p_user ]
                "Réactions":
                    "Réactions associées":      [ block_reactions ]
                "Commentaires":
                    "Commentaires associés":    [ block_comments ]
                "Tags":
                    "Tags associés":            [ block_tags ]
                "Abonnés":
                    "Utilisateurs":             [ block_followers_q, block_followers_c ]
                "Statut":
                    "Publication":              [ [ published ], [ published_by ], [ published_at ] ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_partial, moderated_at ] ]
                    "Notification":             [ block_moderation_alert_new  ]
                    "Précédentes notifications": [ block_moderation_alert_listing  ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                block_file_name:
                    label:                      "Image"
                block_p_user:
                    label:                      "Auteur"
                block_reactions:
                    label:                      "Réactions"
                block_comments:
                    label:                      "Commentaires"
                block_tags:
                    label:                      "Tags"
                block_followers_q:
                    label:                      "élus"
                block_followers_c:
                    label:                      "Citoyens"
                block_moderation_alert_new:
                    label:                      "Alerte"
                block_moderation_alert_listing:
                    label:                      "Historique de l'utilisateur"
                block_front:
                    label:                      "Rendu front"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
