generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDDebate
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
            addFormOptions:
                query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
        p_e_operation_id:
            label:          OP
        p_e_operation:
            label:          OP
        p_l_city_id:
            label:          Ville
        p_l_city:
            label:          Ville
        p_l_department_id:
            label:          Dép
        p_l_department:
            label:          Dép
        p_l_region_id:
            label:          Région
        p_l_region:
            label:          Région
        p_l_country_id:
            label:          Pays
        p_l_country:
            label:          Pays
        p_c_topic_id:
            label:          Discussions (groupe)
        p_c_topic:
            label:          Discussions (groupe)
        fb_ad_id:
            label:          ID Pub Facebook
        file_name:
            label:          Image
        copyright:
            label:          Copyright
        title:
            label:          Titre
        description:
            label:          Description
        nb_views:
            label:          Nombre de vues
        want_boost:
            label:          Boost demandé
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        homepage:
            label:          Accueil
        moderated:
            label:          Modéré
        moderated_partial:
            label:          Modéré partiellement
        moderated_at:
            label:          Mis à jour
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
        indexed_at:
            label:          Indexé le
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des sujets
            max_per_page:                       50
            sort:                               [ published_at, DESC ]
            scopes:
                group_1: 
                    "Publiés":
                        default:                1
                        filters:
                            published:          1
                    "Brouillons":
                        filters:
                            published:          0
            display:                            [ file_name, id, p_user_id, p_c_topic, p_e_operation, p_l_city_id, p_l_department_id, p_l_region_id, title, count_reactions, homepage, published, published_at, created_at ]
            filtersMode:                        modal
            filters:                            [ id, uuid, p_user_id, p_c_topic, p_e_operation, p_l_department, p_l_region, p_l_country, title, online, homepage, published, published_at, created_at ]
            fields:
                count_reactions:
                    label:                      Réponses
                PDDebate.PDDTaggedT:
                    dbType:                     model
                    formType:                   model
                    label:                      Tags associés
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PTag
                        query:                  \Politizr\Model\PTagQuery::create()->filterByOnline(1)->orderByTitle()
            object_actions:
                homepage:
                    label:    En page d'accueil
                    icon:     fa-star-o
                show:                           ~
                edit:                           ~
                delete:                         ~
            actions:
                new:                            ~
                excel:                          ~
            batch_actions:
                homepage:
                    label:    En page d'accueil
    excel:
        params:
            display:                            [ title, p_user, slug, published_at ]
            filename:                           politizr-subjects
            filetype: ~
            datetime_format: ~
            fields: ~
            export: ~
    new:
        params:
            title:                              "Création d'un débat"
            display:
                "Champs principaux":            [ [ title ], [ p_user ], [ p_e_operation ], [ p_c_topic ] ]
            fields:
                p_user:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName()
                p_e_operation:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PEOperation
                        query:                  \Politizr\Model\PEOperationQuery::create()->orderByTitle()
                p_c_topic:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PCTopic
                        query:                  \Politizr\Model\PCTopicQuery::create()->orderByPCircleId()->orderByRank()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du contenu sujet '{{ PDDebate.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ block_file_name, copyright, title, description ]
                "Objets":
                    "Utilisateur":              [ p_user ]
                    "Discussions de groupe":    [ p_c_topic ]
                    "Opération":                [ p_e_operation ]
                "Thématiques":
                    "Tags associés":            [ block_tags ]
                    "Localisation":             [ block_loc ]
                "Statut":
                    "Publication":              [ [ published, published_by, published_at ] ]
                    "Vues":                     [ nb_views ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_partial, moderated_at ] ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "En ligne":                 [ online ]
                    "Notification":             [ block_notifications ]
                    "Mise en avant":            [ [ want_boost ], [ homepage, fb_ad_id ] ]
                    "Dates":                    [ [ created_at, updated_at ], [ indexed_at ] ]
            fields:
                block_file_name:
                    label:                      "Image"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                copyright:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                p_c_topic:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PCTopic
                        query:                  \Politizr\Model\PCTopicQuery::create()->orderByPCircleId()
                p_e_operation:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PEOperation
                        query:                  \Politizr\Model\PEOperationQuery::create()->orderByTitle()
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                block_tags:
                    label:                      "Tags"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_notifications:
                    label:                      "Génération des notifications"
                    grid_class:                 "col-md-12"
                    formType:                   checkbox
                    dbType:                     INTEGER
                    addFormOptions:
                        mapped:                 false
                block_loc:
                    label:                      "Tags"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                        widget:                 single_text
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                archive:
                    label:                      Archiver
                    icon:                       fa-archive
                    params:
                        pk:                     "{{ PDDebate.id }}"
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du contenu sujet '{{ PDDebate.getTitle }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ block_file_name, copyright, title, description ]
                "Objets":
                    "Utilisateur":              [ block_p_user ]
                    "Discussions de groupe":    [ block_p_c_topic ]
                    "Opération":                [ p_e_operation ]
                "Réactions":
                    "Réactions associées":      [ block_reactions ]
                "Commentaires":
                    "Commentaires associés":    [ block_comments ]
                "Thématiques":
                    "Tags associés":            [ block_tags ]
                    "Localisation":             [ block_loc ]
                "Abonnés":
                    "Utilisateurs":             [ block_followers_q, block_followers_c ]
                "Statut":
                    "Publication":              [ [ published ], [ published_by ], [ published_at ] ]
                    "Vues":                     [ nb_views ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_partial, moderated_at ] ]
                    "Notification":             [ block_moderation_alert_new  ]
                    "Précédentes notifications": [ block_moderation_alert_listing  ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "En ligne":                 [ online ]
                    "Mise en avant":            [ [ block_want_boost ], [ homepage, fb_ad_id ] ]
                    "Dates":                    [ [ created_at, updated_at ], [ indexed_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                block_want_boost:
                    label:                      "Boost demandé"
                block_file_name:
                    label:                      "Image"
                block_p_user:
                    label:                      "Auteur"
                block_p_c_topic:
                    label:                      "Discussions"
                block_reactions:
                    label:                      "Réactions"
                block_comments:
                    label:                      "Commentaires"
                block_tags:
                    label:                      "Tags"
                block_loc:
                    label:                      "Localisation"
                block_followers_q:
                    label:                      "élus"
                block_followers_c:
                    label:                      "Citoyens"
                block_moderation_alert_new:
                    label:                      "Alerte"
                block_moderation_alert_listing:
                    label:                      "Historique de l'utilisateur"
                block_front:
                    label:                      "Rendu front"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                homepage:                       ~
                delete: ~
            batch_actions:
                homepage:                       ~
                delete: ~
