generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDDirect
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        name:
            label:          Nom
        city:
            label:          Ville
        email:
            label:          Email
        description:
            label:          Description
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des messages directs
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            display:                            [ name, city, email, created_at ]
            filtersMode:                        modal
            filters:                            [ name, email, created_at ]
            object_actions:
                show:                           ~
                edit:
                    credentials:                ROLE_SYSTEM
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    edit:
        params:
            title:                              "Edition du message de '{{ PDDirect.name }}'"
            tabs:
                "Utilisateur":
                    "Auteur":                    [ name, city, email ]
                "Message":
                    "Description":               [ description ]
                "Attributs":
                    "Identifiants":             [ id ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            fields:
                id:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du message de '{{ PDDirect.name }}'"
            tabs:
                "Utilisateur":
                    "Auteur":                    [ name, city, email ]
                "Message":
                    "Description":               [ description ]
                "Attributs":
                    "Identifiants":             [ id ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
