generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDRComment
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID 
        uuid:
            label:          UUID
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
        p_d_reaction_id:
            label:          ID Réponse
        p_d_reaction:
            label:          Réponse
        description:
            label:          Description
        paragraph_no:
            label:          Num. paragraphe
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published_at:
            label:          Publication
        published_by:
            label:          Publicateur
        online:
            label:          En ligne
        moderated:
            label:          Modéré
        moderated_partial:
            label:          Modéré partiellement
        moderated_at:
            label:          Mis à jour
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
        active:
            label:          Actif
            sortable:       false
            dbType:         BOOLEAN
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des commentaires sur les réponses
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            display:                            [ description, p_user_id, p_d_reaction_id, published_at, active ]
            filtersMode:                        modal
            filters:                            [ id, uuid, p_user_id, p_d_reaction_id, moderated, moderated_partial, active ]
            object_actions:
                show:                           ~
                edit:                           ~
                moderation:
                    label:                      Modération
                    icon:                       fa-ban
                delete:                         ~
            actions:
                new:                            ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'un commentaire"
            display:
                "Champs principaux":            [ [ description, paragraph_no ], [ online ], [ p_user, p_d_reaction ] ]
            fields:
                description:
                    grid_class:                 "col-md-8"
                paragraph_no:
                    credentials:                ROLE_SYSTEM
                p_user:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName()
                p_d_reaction:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PDReaction
                        query:                  \Politizr\Model\PDReactionQuery::create()->online()->orderByTitle()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du commentaire de réponse id-{{ PDRComment.id }}"
            tabs:
                "Contenu":
                    "Auteur":                   [ [ p_user, published_by ] ]
                    "Texte":                    [ description ]
                "Contexte":
                    "Document":                 [ p_d_reaction ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid ] ]
                    "État":                     [ online, paragraph_no ]
                    "Popularité":               [ [ note_pos, note_neg ] ]
                    "Dates":                    [ [ created_at, updated_at, published_at ] ]
            fields:
                paragraph_no:
                    credentials:                ROLE_SYSTEM
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                p_d_reaction:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                description:
                    grid_class:                 "col-md-12"
                published_at:
                    addFormOptions:
                        widget:                 single_text
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                archive:
                    credentials:                ROLE_SYSTEM
                    label:                      Archiver
                    icon:                       fa-archive
                    params:
                        pk:                     "{{ PDRComment.id }}"
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du commentaire de sujet id-{{ PDRComment.id }}"
            tabs:
                "Contenu":
                    "Auteur":                   [ [ block_p_user, published_by ] ]
                    "Texte":                    [ description ]
                "Contexte":
                    "Document":                 [ block_p_d_reaction ]
                "Modération":
                    "Situation":                [ moderated, moderated_partial ]
                    "Historique de l utilisateur":  [ block_moderation_alert_listing ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid ] ]
                    "État":                     [ online, paragraph_no ]
                    "Popularité":               [ [ note_pos, note_neg ] ]
                    "Dates":                    [ [ created_at, updated_at, published_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                description:
                    grid_class:                 "col-md-12"
                block_p_user:
                    label:                      "Auteur"
                block_p_d_reaction:
                    label:                      "Réponse"
                block_moderation_alert_new:
                    label:                      "Alerte"
                block_moderation_alert_listing:
                    label:                      "Historique de l'utilisateur"
                block_front:
                    label:                      "Rendu front"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moderation:                     ~
                delete:                         ~
            batch_actions:
                delete:                         ~
