generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDRComment
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_user_id:
            label:          Utilisateur
        p_user:
            label:          Utilisateur
        p_d_reaction_id:
            label:          Réaction associée
        p_d_reaction:
            label:          Réaction associée
        description:
            label:          Description
        paragraph_no:
            label:          Num. paragraphe
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des commentaires de réaction
            max_per_page:                       50
            sort:                               [ published_at, DESC ]
            scopes:
            display:                            [ id, p_user, p_d_reaction, description, paragraph_no, note_pos, note_neg, online, published_at ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display:                            [ id, p_user, p_d_reaction, paragraph_no, published_at, online, created_at ]
            fields:
                p_user:
                    addFormOptions:
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
    new:
        params:
            title:                              "Création d'un commentaire de réaction"
            display:
                "Champs principaux":            [ [ p_user, p_d_reaction ], [ description ] ]
                "Champs complémentaires":       [ [ paragraph_no ], [ note_pos, note_neg ] ]
            fields:
                p_user:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                p_d_reaction:
                    addFormOptions:
                        empty_value:            ""
                description:
                    addFormOptions:
                        attr:                   { class : tinymce }
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du commentaire de réaction 'pk-{{ PDRComment.id }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ description ] ]
                    "Paragraphe":               [ [ paragraph_no ] ]
                "Objets":
                    "Utilisateur":              [ [ p_user ] ]
                    "Réaction":                    [ [ p_d_reaction ] ]
                "Statut":
                    "Publication":              [ [ published_by ], [ published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                p_user:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                p_d_reaction:
                    addFormOptions:
                        empty_value:            ""
                description:
                    addFormOptions:
                        attr:                   { class : tinymce }
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                      widget:                   single_text
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save: ~
                list: ~
    show:
        params:
            title:                              "Visualisation du commentaire du réaction 'pk-{{ PDRComment.id }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ description ] ]
                    "Paragraphe":               [ [ paragraph_no ] ]
                "Objets":
                    "Utilisateur":              [ [ p_user ] ]
                    "Réaction":                    [ [ p_d_reaction ] ]
                "Statut":
                    "Publication":              [ [ published_by ], [ published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
