generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDRComment
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID 
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
        p_d_reaction_id:
            label:          ID Réaction
        p_d_reaction:
            label:          Réaction
        description:
            label:          Description
        paragraph_no:
            label:          Num. paragraphe
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des commentaires sur les réactions
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            display:                            [ id, p_user_id, p_d_reaction_id, description, paragraph_no, published_at ]
            # filtersMode:                        top
            filters:                            [ id, p_user_id, p_d_reaction_id, published_at ]
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    edit:
        params:
            title:                              "Edition du commentaire de réaction id-{{ PDRComment.id }}"
            tabs:
                "Contenu":
                    "Texte":                    [ description, paragraph_no ]
                "Objets":
                    "Utilisateur":              [ p_user ]
                    "Document":                 [ p_d_reaction ]
                "Statut":
                    "Publication":              [ [ published_by ], [ published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                p_d_reaction:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                        widget:                 single_text
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du commentaire de réaction id-{{ PDRComment.id }}"
            tabs:
                "Contenu":
                    "Texte":                    [ description, paragraph_no ]
                "Objets":
                    "Utilisateur":              [ block_p_user ]
                    "Document":                 [ block_p_d_reaction ]
                "Statut":
                    "Publication":              [ [ published_by ], [ published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                description:
                    grid_class:                 "col-md-12"
                block_p_user:
                    label:                      "Auteur"
                block_p_d_reaction:
                    label:                      "Réaction"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
