generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDReaction
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        tree_level:
            label:          Niveau
        tree_left:
            label:          Arbre / Gauche
        tree_right:
            label:          Arbre / Droite
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
        p_d_debate_id:
            label:          ID Sujet associé
        p_d_debate:
            label:          Sujet associé
        parent_reaction_id:
            label:          ID Réponse associée
        parent_reaction:
            label:          Réponse associée
        parent:
            label:          Réponse associée
        p_l_city_id:
            label:          Ville
        p_l_city:
            label:          Ville
        p_l_department_id:
            label:          Dép
        p_l_department:
            label:          Dép
        p_l_region_id:
            label:          Région
        p_l_region:
            label:          Région
        p_l_country_id:
            label:          Pays
        p_l_country:
            label:          Pays
        p_c_topic_id:
            label:          Discussion
        p_c_topic:
            label:          Discussion
        fb_ad_id:
            label:          Identifiant Facebook
        file_name:
            label:          Image
        copyright:
            label:          Copyright
        title:
            label:          Titre
        description:
            label:          Description
        nb_views:
            label:          Nombre de vues
        want_boost:
            label:          Boost demandé
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Publicateur
        online:
            label:          En ligne
        homepage:
            label:          Accueil
        moderated:
            label:          Modéré
        moderated_partial:
            label:          Modéré partiellement
        moderated_at:
            label:          Mis à jour
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
        indexed_at:
            label:          Indexé le
        # active / aggregration of online + published + moderated
        active:
            label:          Actif
            sortable:       false
            dbType:         BOOLEAN
        localizations:
            label:          Zonage géographique
            sortable:       false
            dbType:         VARCHAR
            addFormOptions:
                mapped:     false
                disabled:   true
                read_only:  true
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des réponses
            max_per_page:                       50
            sort:                               [ published_at, DESC ]
            scopes:
                group_1: 
                group_1: 
                    "Actifs":
                        default:                1
                        filters:                [ active ]
                    "Modérés":
                        filters:                [ moderated ]
                    "Brouillons":
                        filters:                [ draft ]
                    "Inactifs":
                        filters:                [ inactive ]
            display:                            [ title, p_user_id, p_d_debate_id, parent_reaction_id, p_c_topic, active, published_at, created_at ]
            filtersMode:                        modal
            filters:                            [ id, uuid, p_user_id, p_d_debate_id, parent_reaction_id, p_c_topic, p_l_department, p_l_region, title, active, published_at, created_at ]
            object_actions:
                show:                           ~
                edit:                           ~
                moderation:
                    label:                      Modération
                    icon:                       fa-ban
                localization:
                    label:                      Localisation
                    icon:                       fa-map-marker
                delete:                         ~
            actions:
                new:                            ~
                excel:                          ~
    excel:
        params:
            display:                            [ title, p_user, slug, published_at ]
            filename:                           politizr-reactions
            filetype: ~
            datetime_format: ~
            fields: ~
            export: ~
    new:
        params:
            title:                              "Création d'une réaction"
            display:
                "Champs principaux":            [ [ title, p_user ], [ p_c_topic, p_d_debate, parent_reaction ] ]
                "Champs secondaires":           [ [ description ] ]
            fields:
                p_user:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->online()->orderByName()
                p_c_topic:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PCTopic
                        query:                  \Politizr\Model\PCTopicQuery::create()->orderByPCircleId()->orderByRank()
                p_d_debate:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        mapped:                 false
                        multiple:               false
                        required:               true
                        class:                  Politizr\Model\PDDebate
                        query:                  \Politizr\Model\PDDebateQuery::create()->online()->orderByTitle()
                parent_reaction:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        mapped:                 false
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PDReaction
                        query:                  \Politizr\Model\PDReactionQuery::create()->online()->orderByTitle()
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du contenu réponse '{{ PDReaction.getTitle }}'"
            tabs:
                "Contenu":
                    "Auteur":                   [ [ p_user, published_by ] ]
                    "Texte":                    [ title, description ]
                "Contexte":
                    "Liste des thématiques":    [ block_tags ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "État":                     [ online, published, moderated ]
                    "Popularité":               [ nb_views, [ note_pos, note_neg ] ]
                    "Notification":             [ block_notifications ]
                    "Branchement avec Facebook":    [ [ want_boost, fb_ad_id ] ]
                    "Dates":                    [ [ created_at, updated_at, published_at ], [ indexed_at ] ]
            fields:
                block_file_name:
                    label:                      "Image"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                block_tags:
                    label:                      "Tags"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_loc:
                    label:                      "Tags"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_notifications:
                    label:                      "Génération des notifications"
                    grid_class:                 "col-md-12"
                    formType:                   checkbox
                    dbType:                     INTEGER
                    addFormOptions:
                        mapped:                 false
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                copyright:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                      widget:                   single_text
                want_boost:
                    credentials:                ROLE_SYSTEM
                    formType:                   Symfony\Component\Form\Extension\Core\Type\ChoiceType
                    addFormOptions:
                        multiple:               false
                        required:               true
                        choices:                { 'Non répondu': 0, 'Oui': 1, 'Non': 2 }
                        choices_as_values:      true
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                archive:
                    credentials:                ROLE_SYSTEM
                    label:                      Archiver
                    icon:                       fa-archive
                    params:
                        pk:                     "{{ PDReaction.id }}"
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du contenu réponse '{{ PDReaction.getTitle }}'"
            tabs:
                "Contenu":
                    "Auteur":                   [ [ block_p_user, published_by ] ]
                    "Texte":                    [ title, description ]
                    "Médias":                   [ block_p_d_medias ]
                "Contexte":
                    "Publications":             [ [ block_p_c_topic, block_p_d_debate, block_parent ] ]
                    "Liste des thématiques":    [ block_tags ]
                    "Réponses":                [ block_reactions ]
                    "Commentaires":             [ block_comments ]
                "Modération":
                    "Situation":                [ moderated, moderated_partial ]
                    "Historique de l utilisateur":  [ block_moderation_alert_listing ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "État":                     [ online, published ]
                    "Localisation":             [ localizations ]
                    "Popularité":               [ nb_views, [ note_pos, note_neg ] ]
                    "Branchement avec Facebook":    [ [ block_want_boost, fb_ad_id ] ]
                    "Dates":                    [ [ created_at, updated_at, published_at ], [ indexed_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                block_want_boost:
                    credentials:                ROLE_SYSTEM
                    label:                      "Boost demandé"
                block_p_d_medias:
                    label:                      "Images"
                block_file_name:
                    label:                      "Image"
                block_p_user:
                    label:                      "Auteur"
                block_p_d_debate:
                    label:                      "Sujet"
                block_parent:
                    label:                      "Réponse parente"
                block_reactions:
                    label:                      "Réponses"
                block_comments:
                    label:                      "Commentaires"
                block_p_c_topic:
                    label:                      "Discussions"
                block_tags:
                    label:                      "Tags"
                block_moderation_alert_new:
                    label:                      "Alerte"
                block_moderation_alert_listing:
                    label:                      "Historique de l'utilisateur"
                block_front:
                    label:                      "Rendu front"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moderation:                     ~
                localization:                   ~
                delete: ~
            batch_actions:
                delete: ~
