generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDReaction
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        tree_level:
            label:          Arbre / Niveau
        tree_left:
            label:          Arbre / Gauche
        tree_right:
            label:          Arbre / Droite
        p_d_debate_id:
            label:          Débat associé
        p_d_debate:
            label:          Débat associé
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
        title:
            label:          Titre
        summary:
            label:          Résumé
        description:
            label:          Description
        more_info:
            label:          Encart
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des réactions
            # colonnes tableaux > MAJ manuelle dans Fragment/DebateReactions
            display:                            [ id, tree_level, parent, p_user, title, summary, note_pos, note_neg, online, published, published_at ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
#                 new_node:
#                     label:                      Nouvelle réaction
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display:                            [ id, p_user, p_d_debate, published, published_at, online, created_at ]
            fields:
                p_user:
                    addFormOptions:
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
    new:
        params:
            title:                              "Création d'un contenu réaction"
            display:
                "Champs principaux":            [ p_user_id, parent_node, p_d_debate_id, title ]
                "Champs complémentaires":       [ summary ]
            fields:
                p_d_debate_id:
                    formType:                   hidden
                p_user_id:
                    label:                      Utilisateur
                    formType:                   choice
                    dbType:                     VARCHAR
                    addFormOptions:
                        choices:                \Politizr\Model\PUserQuery::create()->orderByName()->find()->toKeyValue()
                parent_node:
                    label:                      Réaction
                    formType:                   choice
                    dbType:                     collection
                    addFormOptions:
                        mapped:                 false
                        choices:                \Politizr\Model\PDReactionQuery::create()->find()->toKeyValue()
                summary:
                    addFormOptions:
                        attr:                   { class : tinymce }
            actions:
                save:                           ~
                list:
                    label:                      Retour au débat
    edit:
        params:
            title:                              "Edition du contenu réaction '{{ PDReaction.getTitle }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ p_d_debate_id, title, summary, description, more_info ]
                "Objets":
                    "Utilisateur":              [ [ p_user_id ] ]
                "Statut":
                    "Publication":              [ [ published ], [ published_by ], [ published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                p_d_debate_id:
                    formType:                   hidden
                p_user_id:
                    label:                      Utilisateur
                    formType:                   choice
                    dbType:                     VARCHAR
                    addFormOptions:
                        choices:                \Politizr\Model\PUserQuery::create()->orderByName()->find()->toKeyValue()
                summary:
                    addFormOptions:
                        attr:                   { class : tinymce }
                description:
                    addFormOptions:
                        attr:                   { class : tinymce }
                more_info:
                    addFormOptions:
                        attr:                   { class : tinymce }
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                      widget:                   single_text
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                show:                           ~
                list:
                    label:                      Retour au débat
    show:
        params:
            title:                              "Visualisation du contenu réaction '{{ PDReaction.getTitle }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ title, summary, description, more_info ]
                "Objets":
                    "Utilisateur":              [ [ p_user ] ]
                    "Débat":                    [ [ p_d_debate ] ]
                "Commentaires":
                    "Commentaires associés":    [ block_comments ]
                "Statut":
                    "Publication":              [ [ published ], [ published_by ], [ published_at ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                block_comments:
                    label:                      "Commentaires"
            actions:
                list:
                    label:                      Retour au débat
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete:                         ~
            batch_actions:
                delete:                         ~
#                 new_node:                       ~
