generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDReaction
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_user_id:
            label:          Utilisateur
        p_user:
            label:          Utilisateur
        p_d_debate_id:
            label:          Débat associé
        p_d_debate:
            label:          Débat associé
        p_d_reaction_related_by_p_d_reaction_id:
            label:          Réaction associée
        p_d_reaction_id:
            label:          Réaction associée
        p_d_reaction:
            label:          Réaction associée
        title:
            label:          Titre
        summary:
            label:          Résumé
        description:
            label:          Description
        more_info:
            label:          Encart
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des réactions
            max_per_page:                       50
            sort:                               [ published_at, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Publiés":
                        default:                true
                        filters:
                            filterByPublished:  true
                    "Brouillons":
                        filters:
                            filterByPublished:  false
            # colonnes tableaux > MAJ manuelle dans Fragment/DebateReactions
            display:                            [ id, p_user, p_d_reaction_id, title, summary, note_pos, note_neg, online, published, published_at ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display:                            [ id, p_user, p_d_debate, published, published_at, online, created_at ]
            fields:
                p_user:
                    addFormOptions:
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
    new:
        params:
            title:                              "Création d'un contenu réaction"
            display:
                "Champs principaux":            [ p_user, p_d_debate_id, title ]
                "Champs complémentaires":       [ summary ]
            fields:
                p_d_debate_id:
                    formType:                   hidden
                p_user:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                p_d_debate:
                    addFormOptions:
                        empty_value:            ""
                        query:                  \Politizr\Model\PDDebateQuery::create()->filterByPublished(true)->orderByPublishedAt(\Criteria::DESC) 
                summary:
                    addFormOptions:
                        attr:                   { class : tinymce }
            actions:
                save:                           ~
                list:
                    label:                      Retour au débat
    edit:
        params:
            title:                              "Edition du contenu réaction '{{ PDReaction.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ p_d_debate_id, title, summary, description, more_info ]
                "Objets":
                    "Utilisateur":              [ [ p_user ] ]
                    "Réaction":                 [ [ p_d_reaction_related_by_p_d_reaction_id ] ]
                "Statut":
                    "Publication":              [ [ published ], [ published_by ], [ published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                p_d_debate_id:
                    formType:                   hidden
                p_user:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                p_d_reaction_related_by_p_d_reaction_id:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                summary:
                    addFormOptions:
                        attr:                   { class : tinymce }
                description:
                    addFormOptions:
                        attr:                   { class : tinymce }
                more_info:
                    addFormOptions:
                        attr:                   { class : tinymce }
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                      widget:                   single_text
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                show:                           ~
                list:
                    label:                      Retour au débat
    show:
        params:
            title:                              "Visualisation du contenu réaction '{{ PDReaction.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ title, summary, description, more_info ]
                "Objets":
                    "Utilisateur":              [ [ p_user ] ]
                    "Débat":                    [ [ p_d_debate ] ]
                    "Réaction":                 [ [ p_d_reaction_related_by_p_d_reaction_id ] ]
                "Commentaires":
                    "Commentaires associés":    [ block_comments ]
                "Statut":
                    "Publication":              [ [ published ], [ published_by ], [ published_at ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                block_comments:
                    label:                      "Commentaires"
                    formType:                   hidden
                    dbType:                     VARCHAR
            actions:
                list:
                    label:                      Retour au débat
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
