generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PDReaction
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        tree_level:
            label:          Arbre / Niveau
        tree_left:
            label:          Arbre / Gauche
        tree_right:
            label:          Arbre / Droite
        p_user_id:
            label:          ID Utilisateur
        p_user:
            label:          Utilisateur
        p_d_debate_id:
            label:          ID Débat associé
        p_d_debate:
            label:          Débat associé
        parent_reaction_id:
            label:          ID Réaction associé
        parent:
            label:          Débat associé
        file_name:
            label:          Image
        title:
            label:          Titre
        description:
            label:          Description
        note_pos:
            label:          Notes +
        note_neg:
            label:          Notes -
        published:
            label:          Publié
        published_at:
            label:          Publication
        published_by:
            label:          Auteur
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des réactions
            max_per_page:                       50
            sort:                               [ published_at, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Publiés":
                        default:                1
                        filters:
                            published:          1
                    "Brouillons":
                        filters:
                            published:          0
            display:                            [ id, p_user_id, p_d_debate_id, tree_level, parent, title, note_pos, note_neg, online, published, published_at ]
            # filtersMode:                        top
            filters:                            [ id, p_user_id, p_d_debate_id, published, published_at, online, created_at ]
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    edit:
        params:
            title:                              "Edition du contenu réaction '{{ PDReaction.getTitle }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ uploadedFileName, title, description ]
                "Objets":
                    "Utilisateur":              [ p_user ]
                    "Débat":                    [ p_d_debate ]
                    # "Réaction parente":         [ parent ]
                "Statut":
                    "Publication":              [ [ published, published_by, published_at ] ]
                    "Notes":                    [ [ note_pos, note_neg ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                uploadedFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   file
                    addFormOptions:
                        # deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                p_d_debate:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                published_at:
                    # formType:                   afe_datetime_picker
                    addFormOptions:
                      widget:                   single_text
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du contenu réaction '{{ PDReaction.getTitle }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ file_name, title, description ]
                "Objets":
                    "Utilisateur":              [ block_p_user ]
                    "Document":                 [ block_p_d_debate, block_parent ]
                "Commentaires":
                    "Commentaires associés":    [ block_comments ]
                "Statut":
                    "Publication":              [ [ published ], [ published_by ], [ published_at ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                block_p_user:
                    label:                      "Auteur"
                block_p_d_debate:
                    label:                      "Débat"
                block_parent:
                    label:                      "Réaction parente"
                block_comments:
                    label:                      "Commentaires"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete:                         ~
            batch_actions:
                delete:                         ~
#                 new_node:                       ~
