generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PMAbuseReporting
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_user_id:
            label:          Utilisateur
        p_user:
            label:          Utilisateur
        p_object_name:
            label:          Objet associé
        p_object_uuid:
            label:          UUID objet associé
        message:
            label:          Message
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des reports des abus
            max_per_page:                       50
            sort:                               [ id, DESC ]
            display:                            [ p_user_id, message, created_at ]
            object_actions:
                show:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    show:
        params:
            title:                              "Visualisation report des abus {{ PMAbuseReporting.id }}"
            tabs:
                "Contenu":
                    "Texte":                    [ message ]
                "Contexte":
                    "Utilisateur":              [ p_user ]
                    "Objet associé":            [ block_p_object ]
                "Attributs":
                    "Dates":                 [ [ created_at, updated_at ] ]
            fields:
                block_p_object:
                    label:                      "Objet"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
