generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PMCgu
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        title:
            label:          Titre
        summary:
            label:          Résumé
        description:
            label:          Description
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:                              Liste des CGU
            max_per_page:                       50
            sort:                               [ online, DESC ]
            display:                            [ created_at, online ]
            object_actions:
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création CGU"
            display:
                "Champs principal":             [ title ]
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition CGU"
            tabs:
                "Résumé":
                    "Général":                  [ [ title  ], [ summary ] ]
                "Contenu":
                    "Texte":                    [ description ]
                "Attributs":
                    "Dates":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                summary:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                list:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
