generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PMCharte
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_circle:
            label:          Groupe
        p_circle_id:
            label:          ID Groupe
        title:
            label:          Titre
        summary:
            label:          Résumé
        description:
            label:          Description
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:                              Liste des chartes
            max_per_page:                       50
            sort:                               [ online, DESC ]
            display:                            [ title, p_circle, created_at, online ]
            object_actions:
                edit:                           ~
                delete:                         ~
            actions:
                new:                            ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création charte"
            display:
                "Champs principal":             [ title, p_circle ]
            fields:
                p_circle:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PCircle
                        query:                  \Politizr\Model\PCircleQuery::create()->orderByTitle()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition charte"
            tabs:
                "Résumé":
                    "Général":                  [ [ title  ], [ summary ] ]
                "Contexte":
                    "Utilisateur":              [ p_circle ]
                "Contenu":
                    "Texte":                    [ description ]
                "Attributs":
                    "État":                 [ online ]
                    "Dates":                 [ [ created_at, updated_at ] ]
            fields:
                summary:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                description:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                p_circle:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                list:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
