generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PMDebateHistoric
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_d_debate_id:
            label:          ID Debat
        p_user_id:
            label:          ID User
        title:
            label:          Titre
        description:
            label:          Description
        copyright:
            label:          Copyright
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des archives débat
            max_per_page:                       50
            sort:                               [ id, DESC ]
            display:                            [ p_user_id, p_d_debate_id, title, created_at ]
            filters:                            [ p_user_id, p_d_debate_id ]
            object_actions:
                show:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    show:
        params:
            title:                              "Visualisation archive {{ PMDebateHistoric.id }}"
            tabs:
                "Contenu":
                    "Images":                   [ block_file_name ]
                    "Texte":                    [ title, description, copyright ]
                "Objets":
                    "Débat":                    [ block_p_d_debate ]
                    "Utilisateur":              [ block_p_user ]
                "Attributs":
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_file_name:
                    label:                      "Image"
                block_p_d_debate:
                    label:                      "Débat"
                block_p_user:
                    label:                      "Auteur"
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
