generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PMEmailing
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_n_email_id:
            label:          ID Notif Mail
        p_n_email:
            label:          Notif Mail
            addFormOptions:
                query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
        p_user_id:
            label:          ID User
        p_user:
            label:          Utilisateur
            addFormOptions:
                query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
        title:
            label:          Titre
        html_body:
            label:          Body
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des notifications email
            max_per_page:                       50
            sort:                               [ id, DESC ]
            display:                            [ p_user_id, p_n_email_id, title, created_at ]
            filters:                            [ title, p_user_id, p_n_email_id ]
            object_actions:
                show:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    show:
        params:
            title:                              "Visualisation notification email {{ PMEmailing.id }}"
            tabs:
                "Contenu":
                    "Texte":                    [ title, html_body ]
                "Objets":
                    "Utilisateur":              [ block_p_user ]
                    "Type notif":               [ p_n_email_id ]
                "Attributs":
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_p_user:
                    label:                      "Utilisateur impacté"
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
