generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PMReactionHistoric
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_user_id:
            label:          ID User
        p_d_reaction_id:
            label:          ID Reaction
        p_object_id:
            label:          ID Reaction
        title:
            label:          Titre
        description:
            label:          Description
        copyright:
            label:          Copyright
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des archives réaction
            max_per_page:                       50
            sort:                               [ id, DESC ]
            display:                            [ p_user_id, p_d_reaction_id, title, created_at ]
            filters:                            [ p_user_id, p_d_reaction_id ]
            object_actions:
                show:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    show:
        params:
            title:                              "Visualisation archive {{ PMReactionHistoric.id }}"
            tabs:
                "Contenu":
                    "Images":                   [ block_file_name ]
                    "Texte":                    [ title, description, copyright ]
                "Objets":
                    "Réaction":                 [ block_p_d_reaction ]
                    "Utilisateur":              [ block_p_user ]
                "Attributs":
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_file_name:
                    label:                      "Image"
                block_p_d_reaction:
                    label:                      "Réaction"
                block_p_user:
                    label:                      "Auteur"
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
