generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\POPaymentType
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        title:
            label:          Titre
        description:
            label:          Description
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des types de paiement
            max_per_page:                       50
            sort:                               [ sortable_rank, ASC ]
            display:                            [ title, description, online ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
                moveUp:                         ~
                moveDown:                       ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'un type de paiement"
            display:
                "Champs principaux":            [ [ title ] ]
                "Champs complémentaires":       [ [ description ] ]
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du type de paiement '{{ POPaymentType.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ], [ description ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save: ~
                list: ~
    show:
        params:
            title:                              "Visualisation du type de paiement '{{ POPaymentType.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ], [ description ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                moveUp:                         ~
                moveDown:                       ~
                delete:                         ~
            batch_actions:
                delete:                         ~