generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\POrder
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_user_id:
            label:          Utilisateur
        p_user:
            dbType:         model
            label:          Utilisateur
        p_o_payment_state_id:
            label:          Paiement
        p_o_payment_state:
            dbType:         model
            label:          Paiement
        p_o_order_state_id:
            label:          Etat
        p_o_order_state:
            dbType:         model
            label:          Etat
        p_o_payment_type_id:
            label:          Mode paiement
        p_o_payment_type:
            dbType:         model
            label:          Mode paiement
        p_o_subscription_id:
            label:          Formule
        p_o_subscription:
            dbType:         model
            label:          Formule
        subscription_title:
            label:          Titre
        subscription_description:
            label:          Description
        subscription_begin_at:
            label:          Début
        subscription_end_at:
            label:          Fin
        information:
            label:          Information
        price:
            label:          Prix initial
        promotion:
            label:          Promotion
        total:
            label:          Prix final
        gender:
            label:          Genre
        name:
            label:          Nom
        firstname:
            label:          Prénom
        phone:
            label:          Téléphone
        email:
            label:          Email
        invoice_ref:
            label:          Réf. facture
        invoice_at:
            label:          Date facture
        invoice_filename:
            label:          Nom du fichier
        elective_mandates:
            label:          Mandats électifs
        supporting_document:
            label:          Justificatif
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des commandes
            max_per_page:                       50
            sort:                               [ id, DESC ]
            scopes:
                group_1: 
                    "Toutes":                   ~
                    "Ouvertes":
                        default:                1
                        filters:
                            p_o_order_state_id: 1
                    "Traitées":
                        filters:
                            p_o_order_state_id: 2
                    "Annulées":
                        filters:
                            p_o_order_state_id: 3
            display:                            [ id, p_o_order_state, p_o_payment_state, p_o_subscription, p_o_payment_type, p_user_id, price, promotion, total ]
            # filtersMode:                        top
            filters:                            [ id, p_o_order_state_id, p_o_order_state, p_o_payment_state, p_o_subscription, p_o_payment_type, p_user_id, created_at ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params:                                 ~
        filename:                               ~
        filetype:                               ~
    new:
        params:
            title:                              "Création d'une commande"
            display:
                "Champs principaux":            [ [ p_user_id ], [ p_o_subscription ], [ subscription_begin_at, subscription_end_at ], [ p_o_order_state ], [ p_o_payment_state, p_o_payment_type ], [ price, promotion, total ] ]
                "Champs complémentaires":       [ [ information ], [ gender, firstname, name ], [ phone, email ], [ elective_mandates ] ]
            fields:
                p_user_id:
                    label:                      Utilisateur
                    formType:                   choice
                    dbType:                     VARCHAR
                    addFormOptions:
                        choices:                \Politizr\Model\PUserQuery::create()->orderByName()->find()->toKeyValue()
                price:
                    formType:                   money
                promotion:
                    formType:                   money
                total:
                    formType:                   money
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de la commande n°{{ POrder.id }}"
            tabs:
                "Commande":
                    "Type":                     [ [ p_o_subscription ], [ price, promotion, total ], [ subscription_title, subscription_description ], [ subscription_begin_at, subscription_end_at ], [ information ] ]
                "Objets":
                    "Utilisateur":              [ p_user ]
                "Utilisateur":
                    "Coordonnées":              [ [ gender, firstname, name ], [ phone, email ] ]
                    "Justificatifs":            [ uploadedSupportingDocument, elective_mandates ]
                # "Facture":
                #     "Facture":                  [ invoice_ref, block_invoice ]
                # "Emails":
                #     "Emails":                   [ block_mail ]
                "Paiement":
                    "Informations":             [ [ p_o_payment_state, p_o_payment_type ] ]
                "Statut":
                    "Actuel":                   [ [ p_o_order_state ] ]
                "Attributs":
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                uploadedSupportingDocument:
                    dbType:                     VARCHAR
                    label:                      Justificatif
                    formType:                   file
                    addFormOptions:
                        # deleteable:             supportingDocument
                        data_class:             Symfony\Component\HttpFoundation\File\File            
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                price:
                    formType:                   money
                promotion:
                    formType:                   money
                total:
                    formType:                   money
                block_invoice:
                    label:                      " "
                    formType:                   hidden
                    dbType:                     VARCHAR
                block_mail:
                    label:                      " "
                    formType:                   hidden
                    dbType:                     VARCHAR
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de la commande n°{{ POrder.id }}"
            tabs:
                "Commande":
                    "Type":                     [ [ p_o_subscription ], [ price, promotion, total ], [ subscription_title, subscription_description ], [ subscription_begin_at, subscription_end_at ], [ information ] ]
                "Objets":
                    "Utilisateur":              [ block_p_user ]
                "Utilisateur":
                    "Coordonnées":              [ [ gender, firstname, name ], [ phone, email ] ]
                    "Justificatifs":            [ supporting_document, elective_mandates ]
                "Paiement":
                    "Informations":             [ [ p_o_payment_state, p_o_payment_type ] ]
                "Statut":
                    "Actuel":                   [ [ p_o_order_state ] ]
                "Attributs":
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_p_user:
                    label:                      "Auteur"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
