generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PQMandate
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    credentials:            ROLE_SYSTEM
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_q_type_id:
            label:          ID Type de mandat
        p_q_type:
            label:          Type de mandat
        title:
            label:          Titre
        select_title:
            label:          Famille
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des types de mandat
            max_per_page:                       50
            sort:                               [ sortable_rank, ASC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Mandat électif":
                        default:                1
                        filters: 
                            p_q_type_id:        1
            display:                            [ select_title, title, online ]
            filters:                            [ p_q_type_id, p_q_type, select_title, title, online ]
            actions:
                new:                            ~
            object_actions:
                edit:                           ~
                delete:                         ~
                moveUp:                         ~
                moveDown:                       ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'un type de mandat"
            display:
                "Champs principaux":            [ p_q_type, title ]
                "Champs complémentaires":       [ select_title ]
            fields:
                p_q_type:
                    dbType:                     model
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PQType
                        query:                  \Politizr\Model\PQTypeQuery::create()->orderById()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du type de mandat '{{ PQMandate.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ title, select_title ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Type":                     [ p_q_type ]
                    "État":                 [ online ]
                    "Dates":                 [ [ created_at, updated_at ] ]
            fields:
                p_q_type:
                    dbType:                     model
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PQType
                        query:                  \Politizr\Model\PQTypeQuery::create()->orderById()
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    formType:                   datetime
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    formType:                   datetime
                    addFormOptions:
                      widget:                   single_text
            actions:
                save: ~
                list: ~
    actions:
        params:
            object_actions:
                moveUp:                         ~
                moveDown:                       ~
                delete:                         ~
            batch_actions:
                delete:                         ~