generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PRBadge
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_r_badge_family_id:
            label:          Famille
        p_r_badge_family:
            label:          Famille
        title:
            label:          Titre
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des badges
            max_per_page:                       50
            sort:                               [ title, ASC ]
            display:                            [ title, p_r_badge_family, nb_users, online ]
            # filtersMode:                        top
            filters:                            [ title, p_r_badge_family, online, created_at ]
            actions:
                new:                            ~
            object_actions:
                edit:                           ~
                delete:                         ~
            fields:
                nb_users:
                    label:                      Badgés
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'un badge"
            display:
                "Champs principaux":            [ [ p_r_badge_family ], [ title ] ]
            fields:
                p_r_badge_family:
                    addFormOptions:
                        query:                  \Politizr\Model\PRBadgeFamilyQuery::create()->orderByRank() 
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du badge '{{ PRBadge.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ p_r_badge_family  ], [ title ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                p_r_badge_family:
                    addFormOptions:
                        query:                  \Politizr\Model\PRBadgeFamilyQuery::create()->orderByRank() 
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save: ~
                list: ~
#     show:
#         params:
#             title:                              "Visualisation du badge '{{ PRBadge.title }}'"
#             tabs:
#                 "Contenu":
#                     "Texte":                    [ [ p_r_badge_family ], [ title ] ]
#                 "Utilisation":
#                     "Utilisateurs badgés":      [ block_users ]
#                 "Attributs":
#                     "Création":                 [ [ online ], [ created_at, updated_at ] ]
#             fields:
#                 block_users:
#                     label:                      "Utilisateurs"
#                     formType:                   hidden
#                     dbType:                     VARCHAR
#             actions:
#               list:                             ~
#               delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
