generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PRBadgeMetal
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        title:
            label:          Titre
        description:
            label:          Description
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des metaux de badge
            max_per_page:                       50
            sort:                               [ id, ASC ]
            display:                            [ title, description ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'un métal de badge"
            display:
                "Champs principaux":            [ [ title ] ]
                "Champs complémentaires":       [ [ description ] ]
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du métal de badge '{{ PRBadgeMetal.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ], [ description ] ]
                "Attributs":
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save: ~
                list: ~
    show:
        params:
            title:                              "Visualisation du métal de badge '{{ PRBadgeMetal.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ], [ description ] ]
                "Badges":
                    "Badges associés":          [ ]
                "Attributs":
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_badges:
                    label:                      "Badges"
                    formType:                   hidden
                    dbType:                     VARCHAR
            actions:
              list:                             ~
              delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
