generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PTag
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_t_tag_type_id:
            label:          ID Type
        p_t_tag_type:
            label:          Type
        PTagRelatedByPTParentId:
            label:              Tag parent
            addFormOptions:
                empty_value:    ""
                query:          \Politizr\Model\PTagQuery::create()->filterByPTTagTypeId(1)->where("p_tag.id > ?", 35)->where("p_tag.id < ?", 137)->orderByTitle() 
        title:
            label:          Titre
        moderated:
            label:          Modéré
        moderated_at:
            label:          Mis à jour
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des tags
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Géographique":
                        filters:
                            p_t_tag_type_id:    1
                    "Thématique":
                        default:                true
                        filters:
                            p_t_tag_type_id:    2
            display:                            [ title, p_t_tag_type, PTagRelatedByPTParentId, countDebates, countUsers, created_at, online ]
            # filtersMode:                        top
            filters:                            [ title, p_t_tag_type_id, PTagRelatedByPTParentId, p_t_tag_type, online, created_at ]
            fields:
                countDebates:
                    label:                      Nb débats
                countUsers:
                    label:                      Nb profils
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        # TODO: contrôle d'univité du champs titre sur le type donné
        params:
            title:                              "Création d'un tag"
            display:
                "Champs principaux":            [ p_t_tag_type, p_t_parent, title ]
            fields:
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle() 
                p_t_parent:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagQuery::create()->filterByPTTagTypeId(1)->orderByTitle() 
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du tag '{{ PTag.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ] ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_at ] ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Création":                 [ [ p_t_tag_type ], [ PTagRelatedByPTParentId ], [ online ], [ created_at, updated_at ] ]
            fields:
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle()
                PTagRelatedByPTParentId:
                    addFormOptions:
                        required:               false
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du tag {{ PTag.title }}"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ] ]
                "Publication":
                    "Débats":                   [ block_debates ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_at ] ]
                "Utilisateurs":
                    "Profils":                  [ block_users ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Création":                 [ [ p_t_tag_type ], [ PTagRelatedByPTParentId ], [ online ], [ created_at, updated_at ] ]
            fields:
                block_debates:
                    label:                      "Taggés"
                block_users:
                    label:                      "Taggés"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
