generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PTag
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_t_tag_type_id:
            label:          Type
        p_t_tag_type:
            label:          Type
        title:
            label:          Titre
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des tags
            max_per_page:                       50
            sort:                               [ title, ASC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Zonage":
                        filters:
                            p_t_tag_type_id:    1
                    "Thèmes":
                        default:                true
                        filters:
                            p_t_tag_type_id:    2
            display:                            [ title, p_t_tag_type, countPDDebates, countPUsers, online ]
            # filtersMode:                        top
            filters:                            [ title, p_t_tag_type_id, p_t_tag_type, online, created_at ]
            fields:
                countPDDebates:
                    label:                      Débats taggés
                countPUsers:
                    label:                      Users taggés
            actions:
                new:                            ~
            object_actions:
#                 show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        # TODO: contrôle d'univité du champs titre sur le type donné
        params:
            title:                              "Création d'un tag"
            display:
                "Champs principaux":            [ [ p_t_tag_type_id ], [ title ] ]
            fields:
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle() 
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du tag '{{ PTag.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ p_t_tag_type_id ], [ title ] ]
                "Attributs":
                    "Création":                 [ [ online ], [ created_at, updated_at ] ]
            fields:
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle() 
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                save_and_list:                  ~
                list:                           ~
#     show:
#         params:
#             title:                              "Visualisation du tag '{{ PTag.title }}'"
#             tabs:
#                 "Contenu":
#                     "Texte":                    [ [ p_t_tag_type ], [ title ] ]]
#                 "Attributs":
#                     "Création":                 [ [ online ], [ created_at, updated_at ] ]
#             actions:
#               list:                             ~
#               delete:                           ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
