generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PTag
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_t_tag_type_id:
            label:          ID Type
        p_t_tag_type:
            label:          Type
        # not used anymore
        # PTagRelatedByPTParentId:
        #     label:              Tag parent
        #     addFormOptions:
        #         empty_value:    ""
        #         query:          \Politizr\Model\PTagQuery::create()->filterByPTTagTypeId(1)->where("p_tag.id > ?", 22)->where("p_tag.id < ?", 129)->orderById() 
        #         # group_by:       p_t_parent_id
        #         # property:       title
        p_user_id:
            label:          ID Créé par
        p_user:
            label:          Créé par
        p_owner_id:
            label:          ID propriétaire
        p_owner:
            label:          Propriétaire
        title:
            label:          Titre
        moderated:
            label:          Modéré
        moderated_at:
            label:          Mis à jour
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des tags
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            scopes:
                group_1: 
                    "Type":
                        filters:
                            p_t_tag_type_id:    3
                    "Famille":
                        filters:
                            p_t_tag_type_id:    4
                    "Thématique":
                        default:                true
                        filters:
                            p_t_tag_type_id:    2
                    "Privé":
                        filters:
                            p_t_tag_type_id:    5
            display:                            [ title, p_t_tag_type, countDebates, countReactions, countUsers, created_at, online ]
            filtersMode:                        modal
            filters:                            [ title, p_t_tag_type_id, p_t_tag_type, online, created_at ]
            fields:
                countDebates:
                    label:                      Débats
                countReactions:
                    label:                      Réactions
                countUsers:
                    label:                      Profils
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        # TODO: contrôle d'univité du champs titre sur le type donné
        params:
            title:                              "Création d'un tag"
            display:
                "Champs principaux":            [ p_t_tag_type, p_owner, title ]
            fields:
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle() 
                p_owner:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition du tag '{{ PTag.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ] ]
                "Objets":
                    "Auteur":                   [ p_user ]
                    "Propriétaire":             [ p_owner ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_at ] ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Type":                     [ p_t_tag_type ]
                    "En ligne":                 [ online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                p_user:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                p_owner:
                    addFormOptions:
                        disabled:               true
                        read_only:              true
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle()
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation du tag {{ PTag.title }}"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ] ]
                "Objets":
                    "Utilisateur":              [ block_p_user ]
                    "Propriétaire":             [ block_p_owner ]
                "Publication":
                    "Débats":                   [ block_debates ]
                    "Réactions":                [ block_reactions ]
                "Modération":
                    "Portée":                   [ [ moderated, moderated_at ] ]
                "Utilisateurs":
                    "Profils":                  [ block_users ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Type":                     [ p_t_tag_type ]
                    "En ligne":                 [ online ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_p_user:
                    label:                      "Auteur"
                block_p_owner:
                    label:                      "Propriétaire"
                block_debates:
                    label:                      "Taggés"
                block_reactions:
                    label:                      "Taggés"
                block_users:
                    label:                      "Taggés"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
