generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PTag
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_t_tag_type_id:
            label:          ID Type
        p_t_tag_type:
            label:          Type
        p_user_id:
            label:          ID Créé par
        p_user:
            label:          Créé par
        p_owner_id:
            label:          ID propriétaire
        p_owner:
            label:          Propriétaire
        title:
            label:          Titre
        moderated:
            label:          Modéré
        moderated_at:
            label:          Mis à jour
        online:
            label:          En ligne
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des thématiques
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            scopes:
                group_1: 
                    "Type":
                        filters:
                            p_t_tag_type_id:    3
                    "Famille":
                        filters:
                            p_t_tag_type_id:    4
                    "Thème":
                        default:                true
                        filters:
                            p_t_tag_type_id:    2
                    "Privé":
                        filters:
                            p_t_tag_type_id:    5
            display:                            [ title, p_t_tag_type, countDebates, countReactions, countUsers, online, moderated, created_at ]
            filtersMode:                        modal
            filters:                            [ title, p_t_tag_type_id, p_t_tag_type, online ]
            fields:
                countDebates:
                    label:                      Sujets
                countReactions:
                    label:                      Réponses
                countUsers:
                    label:                      Profils
            object_actions:
                show:                           ~
                edit:                           ~
                moderation:
                    label:                      Modération
                    icon:                       fa-ban
                delete:                         ~
            actions:
                new:                            ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title:                              "Création d'une thématique"
            display:
                "Champs principaux":            [ p_t_tag_type, p_owner, title ]
            fields:
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle() 
                p_owner:
                    dbType:                     model
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de la thématique '{{ PTag.title }}'"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ] ]
                "Contexte":
                    "Auteur":                   [ p_user ]
                    "Propriétaire":             [ p_owner ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Type":                     [ p_t_tag_type ]
                    "État":                     [ online, moderated ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            fields:
                p_user:
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName()
                p_owner:
                    formType:                   Admingenerator\FormExtensionsBundle\Form\Type\Select2ModelType
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName()
                p_t_tag_type:
                    addFormOptions:
                        query:                  \Politizr\Model\PTTagTypeQuery::create()->orderByTitle()
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    formType:                   datetime
                    addFormOptions:
                      widget:                   single_text
                updated_at:
                    formType:                   datetime
                    addFormOptions:
                      widget:                   single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de la thématique {{ PTag.title }}"
            tabs:
                "Contenu":
                    "Texte":                    [ [ title ] ]
                "Contexte":
                    "Auteur":                   [ block_p_user ]
                    "Propriétaire":             [ block_p_owner ]
                    "Sujets":                   [ block_debates ]
                    "Réponses":                 [ block_reactions ]
                    "Profils":                  [ block_users ]
                "Modération":
                    "Situation":                [ moderated ]
                    "Historique de l utilisateur":  [ block_moderation_alert_listing ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Type":                     [ p_t_tag_type ]
                    "État":                     [ online ]
                    "Dates":                    [ [ created_at, updated_at ] ]
            fields:
                block_p_user:
                    label:                      "Auteur"
                block_p_owner:
                    label:                      "Propriétaire"
                block_debates:
                    label:                      "Taggés"
                block_reactions:
                    label:                      "Taggés"
                block_users:
                    label:                      "Taggés"
                block_moderation_alert_listing:
                    label:                      "Historique de l'utilisateur"
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moderation:                     ~
                delete:                         ~
            batch_actions:
                delete:                         ~
