generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PUQualification
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    i18n_catalog:           PUQualification

    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_u_political_party:
            label:          Parti Politique
        p_u_political_party_id:
            label:          Parti Politique
        p_u_mandate_type:
            label:          Type de mandat
        p_u_mandate_type_id:
            label:          Type de mandat
        description:
            label:          Description
        begin_at:
            label:          Début
        end_at:
            label:          Fin
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    edit:
        params:
            display:                
                NONE:               [ [ p_u_mandate_type, p_u_political_party, begin_at, end_at ] ]
            title:                  "Nouvelle qualification"  # title has to be defined to avoid errors, but is not used
            fields:
                begin_at:
                    formType:       afe_date_picker
                end_at:
                    formType:       afe_date_picker
                p_u_political_party:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                        query:                  \Politizr\Model\PUPoliticalPartyQuery::create()->orderByRank() 
                p_u_mandate_type:
                    addFormOptions:
                        empty_value:            ""
                        required:               false
                        query:                  \Politizr\Model\PUMandateTypeQuery::create()->orderByRank() 
