# TODO
# - gestion username + password
generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PUser
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
    embed_types:
        # qualification
        - "PUQualification-generator.yml"
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_u_type_id:
            label:          Type
        p_u_status_id:
            label:          Statut
        p_u_type:
            label:          Type
        p_u_status:
            label:          Statut
        file_name:
            label:          Image
        gender:
            label:          Genre
        firstname:
            label:          Prénom
        name:
            label:          Nom
        biography:
            label:          Biographie
        website:
            label:          Site web
        twitter:
            label:          Twitter
        facebook:
            label:          Facebook
        email:
            label:          Email
        phone:
            label:          Téléphone
        last_connect:
            label:          Dernière connexion
        p_u_qualifications:
            label:          Qualifications
        p_r_badges:
            label:          Badges
        online:
            label:          En ligne
        validated:
            label:          Profil validé
        roles:
            label:          Liste des rôles de l'utilisateur
            formType:                   choice
            addFormOptions:
                expanded:               true
                multiple:               true
                choices:                
                    ROLE_OAUTH_USER:            'Connexion OpenID'
                    ROLE_CITIZEN_INSCRIPTION:   'Inscription Citoyen en cours'
                    ROLE_ELECTED_INSCRIPTION:   'Inscription Débatteur en cours'
                    ROLE_CITIZEN:               'Citoyen'
                    ROLE_ELECTED:               'Débatteur'
                    ROLE_PROFILE_COMPLETED:     'Inscription terminée'                                                 
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des utilisateurs
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Qualifiés":
                        default:                true
                        filters: 
                            filterByPUTypeId:   2
                    "Citoyens":
                        filters: 
                            filterByPUTypeId:   1
            display:                            [ file_name, name, firstname, p_u_type, p_u_status, online, last_connect ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params:                                 ~
        filename:                               ~
        filetype:                               ~
    filters:
        params:
            display:                            [ name, firstname, p_u_type, p_u_status, online, last_connect ]
    new:
        params:
            title:                              "Création d'un utilisateur"
            display:
                "Champs principaux":            [ [ p_u_type, p_u_status ], [ gender ], [ firstname, name ] ]
                "Champs complémentaires":       [ biography ]
            fields:
                biography:
                    addFormOptions:
                        attr:                   { class : tinymce }
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Type":                     [ p_u_type ]
                    "Civilité":                 [ [ gender ], [ firstname, name ], [ uploadedFileName ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                "Descriptif":
                    "Informations":             [ biography ]
                "Qualification":
                    "Qualifications":           [ p_u_qualifications ]
                "Tag":
                    "Tags du profil":           [ block_tags_geo ]
                "Réputation":
                    "Badges":                   [ badges ]
                "Statut":
                    "Actuel":                   [ [ p_u_status ] ]
                    "Connexion":                [ last_connect ]
                "Attributs":
                    "En ligne":                 [ [ online ] ]
                    "Validé":                   [ [ validated ] ]
                    "Rôles":                    [ roles ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                uploadedFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   afe_single_upload
                    addFormOptions:
                        # nameable:               fileName
                        deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                p_u_qualifications:
                    dbType:                     collection
                    formType:                   afe_collection_table
                    label:                      Liste des postes de qualification de l'utilisateur
                    addFormOptions:
                        # widget:                 fieldset
                        # editable:               [ title, begin_at, end_at ]
                        type:                   \Politizr\AdminBundle\Form\Type\PUQualification\EditType
                        allow_add:              true
                        allow_delete:           true
                        by_reference:           false
                        new_label:              " - Nouvelle qualification"
                        options:
                            # label:              Poste
                            data_class:         Politizr\Model\PUQualification
                badges:
                    dbType:                     model
                    formType:                   model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PRBadge
                        query:                  \Politizr\Model\PRBadgeQuery::create()->orderByTitle() 
                block_tags_geo:
                    label:                      "Tags géo"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                biography:
                    addFormOptions:
                        attr:                   { class : tinymce }
                last_connect:
                    label:                      Date de dernière connexion
                    addFormOptions:
                        widget:                 single_text
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Type":                     [ p_u_type ]
                    "Civilité":                 [ [ file_name, gender, firstname, name ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                "Descriptif":
                    "Informations":             [ biography ]
                "Qualification":
                    "Qualifications":           [ p_u_qualifications ]
                "Tag":
                    "Tags du profil":           [ block_tags_geo ]
                "Réputation":
                    "Badges":                   [ block_badges_debat, block_badges_comment, block_badges_participation, block_badges_moderation, block_badges_autre ]
                "Publication":
                    "Débats":                   [ block_debates ]
                    "Réactions":                [ block_reactions ]
                    "Commentaires":             [ block_comments ]
                "Abonnement":
                    "Followers":                [ block_followers_q, block_followers_c ]
                    "Suivis":                   [ block_subscribers_q, block_subscribers_c ]
                "Affinité":
                    "Partis Politiques":        [ block_affinities ]
                "Statut":
                    "Actuel":                   [ [ p_u_status ] ]
                    "Connexion":                [ last_connect ]
                "Attributs":
                    "En ligne":                 [ [ online ] ]
                    "Validé":                   [ [ validated ] ]
                    "Rôles":                    [ roles ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                p_u_qualifications:
                    dbType:                     collection
                    formType:                   afe_collection_table
                    label:                      Liste des postes de qualification de l'utilisateur
                    addFormOptions:
                        # widget:                 fieldset
                        # editable:               [ title, begin_at, end_at ]
                        type:                   \Politizr\AdminBundle\Form\Type\PUQualification\EditType
                        allow_add:              true
                        allow_delete:           true
                        by_reference:           false
                        new_label:              " - Nouvelle qualification"
                        options:
                            # label:              Poste
                            data_class:         Politizr\Model\PUQualification
                block_tags_geo:
                    label:                      "Tags géo"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_debates:
                    label:                      "Débats"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_debat:
                    label:                      "Débat"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_comment:
                    label:                      "Commentaire"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_participation:
                    label:                      "Participation"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_moderation:
                    label:                      "Modération"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_autre:
                    label:                      "Autres"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_reactions:
                    label:                      "Réactions"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_comments:
                    label:                      "Commentaires"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_followers_q:
                    label:                      "Qualifiés"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_followers_c:
                    label:                      "Citoyens"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_subscribers_q:
                    label:                      "Qualifiés"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_subscribers_c:
                    label:                      "Citoyens"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_affinities:
                    label:                      "Partis Politiques"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                last_connect:
                    label:                      Date de dernière connexion
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
