# TODO
# - gestion username + password
generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PUser
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
#     embed_types:
#         # qualification
#         - "PUQualification-generator.yml"
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_u_status_id:
            label:          Statut
        p_u_status:
            label:          Statut
        file_name:
            label:          Image
        copyright:
            label:          Copyright
        gender:
            label:          Genre
        firstname:
            label:          Prénom
        name:
            label:          Nom
        birthday:
            label:          Date de naissance
        subtitle:
            label:          En quelques mots
        biography:
            label:          Biographie
        website:
            label:          Site web
        twitter:
            label:          Twitter
        facebook:
            label:          Facebook
        email:
            label:          Email
        phone:
            label:          Téléphone
        username:          
            label:          Identifiant
        plainPassword:          
            label:          Mot de passe
        last_login:
            label:          Dernière connexion
        last_activity:
            label:          Dernière activité
        p_r_badges:
            label:          Badges
        qualified:
            label:          Profil élu
        validated:
            label:          Profil validé
        nb_id_check:
            label:          Essai(s)
        online:
            label:          En ligne
        homepage:
            label:          Accueil
        banned:
            label:          Banni
        banned_nb_days_left:
            label:          Nombre de jours restants
        banned_nb_total:
            label:          Nombre total de bannissement
        abuse_level:
            label:          Niveau d'abus
        roles:
            label:                              Liste des rôles de l'utilisateur
            formType:                           choice
            addFormOptions:
                expanded:                       true
                multiple:                       true
                choices:                
                    ROLE_OAUTH_USER:            'Connexion OpenID'
                    ROLE_CITIZEN_INSCRIPTION:   'Inscription Citoyen en cours'
                    ROLE_ELECTED_INSCRIPTION:   'Inscription Élu en cours'
                    ROLE_CITIZEN:               'Citoyen'
                    ROLE_ELECTED:               'Élu'
                    ROLE_PROFILE_COMPLETED:     'Inscription terminée'
        created_at:
            label:      Création
            # addFilterOptions:
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des utilisateurs
            max_per_page:                       50
            sort:                               [ last_activity, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Élus":
                        default:                1
                        filters: 
                            qualified:          1
                    "Citoyens":
                        filters: 
                            qualified:          0
            display:                            [ file_name, gender, name, firstname, qualified, validated, nb_id_check, p_u_status, reputation_score, online, homepage, last_activity, created_at ]
            fields:
                reputation_score:
                    label:                      Score
            filtersMode:                        modal
            filters:                            [ id, uuid, email, name, qualified, validated, p_u_status, online, homepage, last_activity, created_at ]
            object_actions:
                homepage:
                    label:    En page d'accueil
                    icon:     fa-star-o
                show:                           ~
                edit:                           ~
                delete:                         ~
            actions:
                new:                            ~
                excel:                          ~
            batch_actions:
                homepage:
                    label:    En page d'accueil
    excel:
        params:
            display:                            [ gender, name, first_name, email, phone, email, website, twitter, facebook, reputation_score, stringifiedGeoTags ]
            filename:                           politizr-users
            filetype: ~
            datetime_format: ~
            fields: ~
            export: ~
    new:
        params:
            title:                              "Création d'un utilisateur"
            display:
                "Champs principaux":            [ [ qualified, p_u_status, email ], [ gender, firstname, name ], [ username ], [ plainPassword ], [ roles ] ]
            fields:
                p_u_status:
                    dbType:                     model
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PUStatus
                #         query:                  \Politizr\Model\PUStatusQuery::create()->orderById()
                plainPassword:          
                    dbType:                             VARCHAR
                    formType:                           repeated
                    addFormOptions:         
                        first_options:          
                            label:                      Mot de passe
                        second_options:         
                            label:                      Confirmation
                        type:                           password
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Civilité":                 [ [ block_file_name ], [ gender ], [ firstname, name ], [ birthday ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                "Connexion":
                    "Connexion":                [ username, plainPassword ]
                "Descriptif":
                    "Informations":             [ subtitle, biography ]
                "Tag":
                    "Tags associés":            [ block_tags_public ]
                "Réputation":
                    "Score":                    [ block_reputation ]
                    "Badges":                   [ badges ]
                "Abonnement":
                    "Followers":                [ followers ]
                    "Abonnements":              [ subscribers ]
                "Modération":
                    "Bannissement":             [ [ banned, banned_nb_days_left ] ]
                    "Risque user":              [ abuse_level ]
                "Statut":
                    "Actuel":                   [ p_u_status ]
                    "Activité":                 [ last_login, last_activity ]
                "Rôles":
                    "Rôles":                    [ roles ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "Type":                     [ qualified ]
                    "En ligne":                 [ online ]
                    "Mise en avant":            [ homepage ]
                    "Validé":                   [ validated, nb_id_check ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_back_file_name:
                    label:                      "Image de fond"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                copyright:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                block_file_name:
                    label:                      "Image"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                followers:
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PUser
                #         query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                subscribers:
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PUser
                #         query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                uploadedFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   file
                    addFormOptions:
                        # deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                plainPassword:          
                    dbType:                             VARCHAR
                    formType:                           repeated
                    addFormOptions:         
                        first_options:          
                            label:                      Mot de passe
                        second_options:         
                            label:                      Confirmation
                        type:                           password
                p_u_status:
                    dbType:                     model
                    addFormOptions:
                        multiple:               false
                        required:               false
                        class:                  Politizr\Model\PUStatus
                #         query:                  \Politizr\Model\PUStatusQuery::create()->orderById()
                subtitle:
                    grid_class:                 "col-md-12"
                biography:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                block_tags_public:
                    label:                      "Tags publiques"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                badges:
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PRBadge
                        # query:                  \Politizr\Model\PRBadgeQuery::create()->orderById() 
                block_reputation:
                    label:                      "Réputation"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                last_login:
                    label:                      Date de dernière connexion
                    addFormOptions:
                        widget:                 single_text
                last_activity:
                    label:                      Date de dernière activité
                    addFormOptions:
                        widget:                 single_text
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                archive:
                    label:                      Archiver
                    icon:                       fa-archive
                    params:
                        pk:                     "{{ PUser.id }}"
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Type":                     [ qualified ]
                    "Civilité":                 [ [ block_file_name ], [ gender, firstname, name ], [ birthday ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                    "Validation IdCheck":       [ block_id_check ]
                "Descriptif":
                    "Informations":             [ biography ]
                "Tag":
                    "Tags associés":            [ block_tags_public ]
                "Réputation":
                    "Score":                    [ reputationScore ]
                    "Badges":                   [ block_badges_debat, block_badges_comment, block_badges_participation, block_badges_moderation, block_badges_autre ]
                "Publication":
                    "Débats":                   [ block_debates ]
                    "Réactions":                [ block_reactions ]
                    "Commentaires":             [ block_d_comments, block_r_comments ]
                "Abonnement":
                    "Followers":                [ block_followers ]
                    "Abonnements":              [ block_subscribers ]
                "Mandats":
                    "Mandats":                  [ block_mandates ]
                "Statut":
                    "Actuel":                   [ [ p_u_status ] ]
                    "Connexion":                [ last_login, last_activity ]
                "Modération":
                    "Bannissement":             [ [ banned, banned_nb_days_left, banned_nb_total ], [ block_moderation_banned ] ]
                    "Niveau de risque user":    [ abuse_level ]
                    "Notification":             [ block_moderation_alert_new  ]
                    "Précédentes notifications": [ block_moderation_alert_listing  ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "En ligne":                 [ online ]
                    "Mise en avant":            [ homepage ]
                    "Validé":                   [ validated, nb_id_check ]
                    "Rôles":                    [ roles ]
                    "Création":                 [ [ created_at, updated_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                block_back_file_name:
                    label:                      "Image de fond"
                block_file_name:
                    label:                      "Image"
                block_tags_public:
                    label:                      "Tags publiques"
                reputationScore:
                    label:                      "Score"
                block_badges_debat:
                    label:                      "Débat"
                block_badges_comment:
                    label:                      "Commentaire"
                block_badges_participation:
                    label:                      "Participation"
                block_badges_moderation:
                    label:                      "Communautaire"
                block_badges_autre:
                    label:                      "Autres"
                block_debates:
                    label:                      "Débats"
                block_reactions:
                    label:                      "Réactions"
                block_d_comments:
                    label:                      "Commentaires de débat"
                block_r_comments:
                    label:                      "Commentaires de réaction"
                block_followers:
                    label:                      "Followers"
                block_subscribers:
                    label:                      "Abonnements"
                block_mandates:
                    label:                      "Mandats"
                block_id_check:
                    label:                      "Vérification de l'identité"
                block_moderation_banned:
                    label:                      "Bannissement"
                block_moderation_alert_new:
                    label:                      "Nouvelle alerte"
                block_moderation_alert_listing:
                    label:                      "Historique de l'utilisateur"
                block_front:
                    label:                      "Rendu front"
                last_login:
                    label:                      Date de dernière connexion
                last_activity:
                    label:                      Date de dernière activité
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                homepage:                       ~
                delete: ~
            batch_actions:
                homepage:                       ~
                delete: ~
