# TODO
# - gestion username + password
generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PUser
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
#     embed_types:
#         # qualification
#         - "PUQualification-generator.yml"
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_u_status_id:
            label:          Statut
        p_u_status:
            label:          Statut
        file_name:
            label:          Image
        gender:
            label:          Genre
        firstname:
            label:          Prénom
        name:
            label:          Nom
        subtitle:
            label:          En quelques mots
        biography:
            label:          Biographie
        website:
            label:          Site web
        twitter:
            label:          Twitter
        facebook:
            label:          Facebook
        email:
            label:          Email
        phone:
            label:          Téléphone
        username:          
            label:          Identifiant
        plainPassword:          
            label:          Mot de passe
        last_login:
            label:          Dernière connexion
        last_activity:
            label:          Dernière activité
        p_r_badges:
            label:          Badges
        qualified:
            label:          Profil qualifié
        validated:
            label:          Profil validé
        online:
            label:          En ligne
        roles:
            label:          Liste des rôles de l'utilisateur
            formType:                   choice
            addFormOptions:
                expanded:               true
                multiple:               true
                choices:                
                    ROLE_OAUTH_USER:            'Connexion OpenID'
                    ROLE_CITIZEN_INSCRIPTION:   'Inscription Citoyen en cours'
                    ROLE_ELECTED_INSCRIPTION:   'Inscription Débatteur en cours'
                    ROLE_CITIZEN:               'Citoyen'
                    ROLE_ELECTED:               'Débatteur'
                    ROLE_PROFILE_COMPLETED:     'Inscription terminée'
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des utilisateurs
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Qualifiés":
                        default:                1
                        filters: 
                            qualified:          1
                    "Citoyens":
                        filters: 
                            qualified:          0
            display:                            [ file_name, name, firstname, qualified, p_u_status, reputation_score, online, last_activity ]
            fields:
                reputation_score:
                    label:                      Score
            # filtersMode:                        top
            filters:                            [ id, email, name, firstname, qualified, p_u_status, online, last_activity ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params:                                 ~
        filename:                               ~
        filetype:                               ~
    new:
        params:
            title:                              "Création d'un utilisateur"
            display:
                "Champs principaux":            [ [ qualified, p_u_status_id, email ], [ gender, firstname, name ], [ username ], [ plainPassword ], [ roles ] ]
            fields:
                p_u_status_id:
                    label:          Statut
                    formType:       choice
                    addFormOptions:
                        choices:    \Politizr\Model\PUStatusQuery::create()->orderById()->find()->toKeyValue()
                plainPassword:          
                    dbType:                             VARCHAR
                    formType:                           repeated
                    addFormOptions:         
                        first_options:          
                            label:                      Mot de passe
                        second_options:         
                            label:                      Confirmation
                        type:                           password
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Civilité":                 [ [ gender ], [ firstname, name ], [ uploadedFileName ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                "Identifiant":
                    "Connexion":                [ username, plainPassword ]
                    "Rôles":                    [ roles ]
                "Descriptif":
                    "Informations":             [ subtitle, biography ]
                "Tag":
                    "Tags associés - public":   [ block_tags_public ]
                    "Tags suivis - privé":      [ block_tags_private ]
                "Réputation":
                    "Score":                    [ block_reputation ]
                    "Badges":                   [ badges ]
                "Abonnement":
                    "Followers":                [ followers ]
                    "Abonnements":              [ subscribers ]
                "Statut":
                    "Actuel":                   [ p_u_status_id ]
                    "Activité":                 [ last_login, last_activity ]
                "Attributs":
                    "Type":                     [ qualified ]
                    "En ligne":                 [ online ]
                    "Validé":                   [ validated ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                followers:
                    dbType:                     model
                    formType:                   model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                subscribers:
                    dbType:                     model
                    formType:                   model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PUser
                        query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                uploadedFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   file
                    addFormOptions:
                        # deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                plainPassword:          
                    dbType:                             VARCHAR
                    formType:                           repeated
                    addFormOptions:         
                        first_options:          
                            label:                      Mot de passe
                        second_options:         
                            label:                      Confirmation
                        type:                           password
                p_u_status_id:
                    label:          Statut
                    formType:       choice
                    addFormOptions:
                        choices:    \Politizr\Model\PUStatusQuery::create()->orderById()->find()->toKeyValue()
                subtitle:
                    grid_class:                 "col-md-12"
                biography:
                    grid_class:                 "col-md-12"
                    addFormOptions:
                        attr:                   { class : tinymce }
                block_tags_public:
                    label:                      "Tags publiques"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_tags_private:
                    label:                      "Tags privés"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                badges:
                    dbType:                     model
                    formType:                   model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PRBadge
                        query:                  \Politizr\Model\PRBadgeQuery::create()->orderByTitle() 
                block_reputation:
                    label:                      "Réputation"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                last_login:
                    label:                      Date de dernière connexion
                    addFormOptions:
                        widget:                 single_text
                last_activity:
                    label:                      Date de dernière activité
                    addFormOptions:
                        widget:                 single_text
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Type":                     [ qualified ]
                    "Civilité":                 [ [ file_name, gender, firstname, name ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                "Descriptif":
                    "Informations":             [ biography ]
                "Tag":
                    "Tags associés - public":   [ block_tags_public ]
                    "Tags suivis - privé":      [ block_tags_private ]
                "Réputation":
                    "Score":                    [ reputationScore ]
                    "Badges":                   [ block_badges_debat, block_badges_comment, block_badges_participation, block_badges_moderation, block_badges_autre ]
                "Publication":
                    "Débats":                   [ block_debates ]
                    "Réactions":                [ block_reactions ]
                    "Commentaires":             [ block_d_comments, block_r_comments ]
                "Abonnement":
                    "Followers":                [ block_followers ]
                    "Abonnements":              [ block_subscribers ]
                "Statut":
                    "Actuel":                   [ [ p_u_status ] ]
                    "Connexion":                [ last_login, last_activity ]
                "Attributs":
                    "En ligne":                 [ [ online ] ]
                    "Validé":                   [ [ validated ] ]
                    "Rôles":                    [ roles ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_tags_public:
                    label:                      "Tags publiques"
                block_tags_private:
                    label:                      "Tags privés"
                reputationScore:
                    label:                      "Score"
                block_debates:
                    label:                      "Débats"
                block_badges_debat:
                    label:                      "Débat"
                block_badges_comment:
                    label:                      "Commentaire"
                block_badges_participation:
                    label:                      "Participation"
                block_badges_moderation:
                    label:                      "Modération"
                block_badges_autre:
                    label:                      "Autres"
                block_reactions:
                    label:                      "Réactions"
                block_d_comments:
                    label:                      "Commentaires de débat"
                block_r_comments:
                    label:                      "Commentaires de réaction"
                block_followers:
                    label:                      "Followers"
                block_subscribers:
                    label:                      "Abonnements"
                block_affinities:
                    label:                      "Partis Politiques"
                last_login:
                    label:                      Date de dernière connexion
                last_activity:
                    label:                      Date de dernière activité
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
