# TODO
# - gestion username + password
generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PUser
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
#     embed_types:
#         # qualification
#         - "PUQualification-generator.yml"
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        uuid:
            label:          UUID
        slug:
            label:          Slug
        p_u_status_id:
            label:          Statut
        p_u_status:
            label:          Statut
        p_l_city_id:
            label:          Ville
        p_l_city:
            label:          Ville
        p_l_department:
            label:          Département
        p_l_region:
            label:          Région
        file_name:
            label:          Image
        copyright:
            label:          Copyright
        gender:
            label:          Genre
        firstname:
            label:          Prénom
        name:
            label:          Nom
        birthday:
            label:          Date de naissance
        subtitle:
            label:          En quelques mots
        biography:
            label:          Biographie
        website:
            label:          Site web
        twitter:
            label:          Twitter
        facebook:
            label:          Facebook
        email:
            label:          Email
        phone:
            label:          Téléphone
        username:          
            label:          Identifiant
        plainPassword:          
            label:          Mot de passe
        last_login:
            label:          Dernière connexion
        last_activity:
            label:          Dernière activité
        p_r_badges:
            label:          Badges
        organization:
            label:          Compte Collectivité
        qualified:
            label:          Profil élu
        validated:
            label:          Profil validé
        nb_id_check:
            label:          Essai(s)
        online:
            label:          En ligne
        homepage:
            label:          Accueil
        support_group:
            label:          Supporte la création d'un groupe pour ses collectivités
        banned:
            label:          Banni
        banned_nb_days_left:
            label:          Nombre de jours restants
        banned_nb_total:
            label:          Nombre total de bannissement
        abuse_level:
            label:          Niveau d'abus
        roles:
            label:                              Rôles
            formType:                           choice
            addFormOptions:
                expanded:                       true
                multiple:                       true
        created_at:
            label:      Création
            # addFilterOptions:
        updated_at:
            label:          Mis à jour
        indexed_at:
            label:          Indexé le
        # active / aggregration of online + banned + status
        active:
            label:                      Actif
            sortable:                   false
            dbType:                     BOOLEAN
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des utilisateurs
            max_per_page:                       50
            sort:                               [ last_activity, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Élus":
                        default:                1
                        filters: 
                            qualified:          1
                    "Citoyens":
                        filters: 
                            qualified:          0
            display:                            [ file_name, name, firstname, p_l_city, qualified, reputation_score, active, last_activity, created_at ]
            filters:                            [ id, uuid, email, name, qualified, validated, active, created_at, last_login ]
            filtersMode:                        modal
            fields:
                p_l_city:
                    label:                      Localisation
                    sortOn:                     PLCity.name
                reputation_score:
                    label:                      Score
                    sortable:                   false
            object_actions:
                show:                           ~
                edit:                           ~
                moderation:
                    label:                      Modération
                    icon:                       fa-ban
                localization:
                    label:                      Localisation
                    icon:                       fa-map-marker
                mandate:
                    credentials:                ROLE_SYSTEM
                    label:                      Mandats
                    icon:                       fa-graduation-cap
                idcheck:
                    credentials:                ROLE_SYSTEM
                    label:                      Identité
                    icon:                       fa-user
                delete:                         ~
            actions:
                new:                            ~
                excel:                          ~
            batch_actions:
                delete:                         ~
    excel:
        params:
            display:                            [ qualified, gender, name, first_name, cityStr, departmentStr, birthday, email, phone, email, website, twitter, facebook, reputation_score, provider, provider_id ]
            filename:                           politizr-users
            filetype: ~
            datetime_format: ~
            fields: ~
            export: ~
    new:
        params:
            title:                              "Création d'un utilisateur"
            display:
                "Champs principaux":            [ [ qualified ], [ gender, firstname, name ], [ email ], [ username , plainPassword ], [ roles, p_u_status_id ] ]
            fields:
                p_u_status_id:
                    dbType:                     VARCHAR
                    formType:                   hidden
                    addFormOptions:
                        data:                   1
                plainPassword:          
                    dbType:                     VARCHAR
                    formType:                   repeated
                    addFormOptions:         
                        first_options:          
                            label:              Mot de passe
                        second_options:         
                            label:              Confirmation
                        type:                   password
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Civilité":                 [ [ block_file_name ], [ gender, firstname, name ], [ birthday ] ]
                    "Contact":                  [ email ]
                    "Informations":             [ [ biography ], [ website, twitter, facebook ] ]
                "Connexion":
                    "Connexion":                [ [ username, plainPassword ] ]
                "Thématiques":
                    "Liste des thématiques associées":            [ block_tags_public ]
                "Réputation":
                    "Score":                    [ block_reputation ]
                    "Badges":                   [ badges ]
                "Listes":
                    "Liste des personnes qui suivent":  [ followers ]
                    "Liste des personnes suivies":      [ subscribers ]
                    "Liste des organisations":          [ current_organizations ]
                    "Liste des rôles":                  [ roles ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "État":                     [ online, banned, p_u_status, abuse_level ]
                    "Type":                     [ qualified, organization, validated, nb_id_check, support_group ]
                    "Abonnements notifications": [ p_n_emails ]
                    "Dates":                    [ [ created_at, updated_at ], [ last_activity, indexed_at ] ]
            fields:
                block_file_name:
                    label:                      "Image"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                followers:
                    credentials:                ROLE_SYSTEM
                    label:                      Abonnés
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PUser
                #         query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                subscribers:
                    credentials:                ROLE_SYSTEM
                    label:                      Abonnements
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PUser
                #         query:                  \Politizr\Model\PUserQuery::create()->orderByName() 
                current_organizations:
                    label:                      Organisations
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        property:               title
                        class:                  Politizr\Model\PQOrganization
                p_n_emails:
                    label:                      Notifications mail
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        expanded:               true
                        required:               false
                        property:               title
                        class:                  Politizr\Model\PNEmail
                uploadedFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   file
                    addFormOptions:
                        # deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                plainPassword:          
                    dbType:                             VARCHAR
                    formType:                           repeated
                    addFormOptions:         
                        first_options:          
                            label:                      Mot de passe
                        second_options:         
                            label:                      Confirmation
                        type:                           password
                biography:
                    grid_class:                 "col-md-9"
                block_tags_public:
                    credentials:                ROLE_SYSTEM
                    label:                      "Tags publiques"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                badges:
                    credentials:                ROLE_SYSTEM
                    dbType:                     model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PRBadge
                        # query:                  \Politizr\Model\PRBadgeQuery::create()->orderById() 
                block_reputation:
                    label:                      "Réputation"
                    grid_class:                 "col-md-12"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                last_activity:
                    label:                      Date de dernière activité
                    addFormOptions:
                        widget:                 single_text
                support_group:
                    credentials:                ROLE_SYSTEM
                id:
                    addFormOptions:
                        read_only:              true
                uuid:
                    addFormOptions:
                        read_only:              true
                nb_id_check:
                    credentials:                ROLE_SYSTEM
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                archive:
                    credentials:                ROLE_SYSTEM
                    label:                      Archiver
                    icon:                       fa-archive
                    params:
                        pk:                     "{{ PUser.id }}"
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Civilité":                 [ [ block_file_name ], [ gender, firstname, name ], [ birthday ], [ block_localization ] ]
                    "Réputation":               [ reputationScore ]
                    "Contact":                  [ email ]
                    "Informations":             [ [ biography ], [ website, twitter, facebook ] ]
                "Modération":
                    "Situation":                [ banned, abuse_level ]
                    "Historique de l utilisateur":  [ block_moderation_alert_listing ]
                "Listes":
                    "Liste des personnes qui suivent":  [ followers ]
                    "Liste des personnes suivies":      [ subscribers ]
                    "Liste des organisations":          [ current_organizations ]
                    "Liste des rôles":                  [ roles ]
                "Attributs":
                    "Identifiants":             [ [ id, uuid, slug ] ]
                    "État":                     [ active, p_u_status ]
                    "Type":                     [ qualified, organization, validated, nb_id_check, support_group ]
                    "Dates":                    [ [ created_at, updated_at ], [ last_activity, indexed_at ] ]
                "Front":
                    "Rendu":                    [ block_front ]
            fields:
                followers:
                    credentials:                ROLE_SYSTEM
                    label:                      Abonnés
                subscribers:
                    credentials:                ROLE_SYSTEM
                    label:                      Abonnements
                current_organizations:
                    label:                      Organisations
                p_n_emails:
                    label:                      Notifications mail
                block_file_name:
                    label:                      "Image"
                block_localization:
                    label:                      "Localisation"
                reputationScore:
                    label:                      "Score"
                block_moderation_alert_listing:
                    label:                      " "
                block_front:
                    label:                      "Rendu front"
                nb_id_check:
                    credentials:                ROLE_SYSTEM
                last_activity:
                    label:                      Date de dernière activité
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                moderation:                     ~
                localization:                   ~
                mandate:                        ~
                idcheck:                        ~
                delete:                         ~
            batch_actions:
                delete:                         ~
