# TODO
# - gestion username + password
generator:                  admingenerator.generator.propel
params:
    model:                  Politizr\Model\PUser
    namespace_prefix:       Politizr
    concurrency_lock:       ~
    bundle_name:            AdminBundle
#     embed_types:
#         # qualification
#         - "PUQualification-generator.yml"
    pk_requirement:         ~
    fields:
        id:
            label:          ID
        p_u_status_id:
            label:          Statut
        p_u_status:
            label:          Statut
        file_name:
            label:          Image
        gender:
            label:          Genre
        firstname:
            label:          Prénom
        name:
            label:          Nom
        subtitle:
            label:          En quelques mots
        biography:
            label:          Biographie
        website:
            label:          Site web
        twitter:
            label:          Twitter
        facebook:
            label:          Facebook
        email:
            label:          Email
        phone:
            label:          Téléphone
        last_connect:
            label:          Dernière connexion
        p_r_badges:
            label:          Badges
        qualified:
            label:          Profil qualifié
        validated:
            label:          Profil validé
        online:
            label:          En ligne
        roles:
            label:          Liste des rôles de l'utilisateur
            formType:                   choice
            addFormOptions:
                expanded:               true
                multiple:               true
                choices:                
                    ROLE_OAUTH_USER:            'Connexion OpenID'
                    ROLE_CITIZEN_INSCRIPTION:   'Inscription Citoyen en cours'
                    ROLE_ELECTED_INSCRIPTION:   'Inscription Débatteur en cours'
                    ROLE_CITIZEN:               'Citoyen'
                    ROLE_ELECTED:               'Débatteur'
                    ROLE_PROFILE_COMPLETED:     'Inscription terminée'                                                 
        created_at:
            label:          Création
        updated_at:
            label:          Mis à jour
    object_actions:
        delete:             ~
    batch_actions:
        delete:             ~
builders:
    list:
        params:
            title:                              Liste des utilisateurs
            max_per_page:                       50
            sort:                               [ created_at, DESC ]
            scopes:
                group_1: 
                    "Tous":                     ~
                    "Qualifiés":
                        default:                true
                        filters: 
                            filterByQualified:  true
                    "Citoyens":
                        filters: 
                            filterByQualified:  false
            display:                            [ file_name, name, firstname, qualified, p_u_status_id, online, last_connect ]
            # filtersMode:                        top
            filters:                            [ name, firstname, qualified, p_u_status_id, online, last_connect ]
            actions:
                new:                            ~
            object_actions:
                show:                           ~
                edit:                           ~
                delete:                         ~
    excel:
        params:                                 ~
        filename:                               ~
        filetype:                               ~
    new:
        params:
            title:                              "Création d'un utilisateur"
            display:
                "Champs principaux":            [ [ qualified, p_u_status_id ], [ gender ], [ firstname, name ] ]
                "Champs complémentaires":       [ biography ]
            fields:
                biography:
                    addFormOptions:
                        attr:                   { class : tinymce }
                p_u_status_id:
                    label:          Statut
                    formType:       choice
                    addFormOptions:
                        choices:    \Politizr\Model\PUStatusQuery::create()->orderById()->find()->toKeyValue()
            actions:
              save:                             ~
              list:                             ~
    edit:
        params:
            title:                              "Edition de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Type":                     [ qualified ]
                    "Civilité":                 [ [ gender ], [ firstname, name ], [ uploadedFileName ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                "Descriptif":
                    "Informations":             [ subtitle, biography ]
                "Tag":
                    "Tags du profil":           [ block_tags_geo ]
                "Réputation":
                    "Badges":                   [ badges ]
                "Statut":
                    "Actuel":                   [ [ p_u_status_id ] ]
                    "Connexion":                [ last_connect ]
                "Attributs":
                    "En ligne":                 [ [ online ] ]
                    "Validé":                   [ [ validated ] ]
                    "Rôles":                    [ roles ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                uploadedFileName:
                    dbType:                     VARCHAR
                    label:                      Photo
                    formType:                   file
                    addFormOptions:
                        # deleteable:             fileName
                        data_class:             Symfony\Component\HttpFoundation\File\File
                p_u_status_id:
                    label:          Statut
                    formType:       choice
                    addFormOptions:
                        choices:    \Politizr\Model\PUStatusQuery::create()->orderById()->find()->toKeyValue()
                badges:
                    dbType:                     model
                    formType:                   model
                    addFormOptions:
                        multiple:               true
                        required:               false
                        class:                  Politizr\Model\PRBadge
                        query:                  \Politizr\Model\PRBadgeQuery::create()->orderByTitle() 
                block_tags_geo:
                    label:                      "Tags géo"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                biography:
                    addFormOptions:
                        attr:                   { class : tinymce }
                last_connect:
                    label:                      Date de dernière connexion
                    addFormOptions:
                        widget:                 single_text
                created_at:
                    addFormOptions:
                        widget:                 single_text
                updated_at:
                    addFormOptions:
                        widget:                 single_text
            actions:
                save:                           ~
                show:                           ~
                list:                           ~
                delete:                         ~
    show:
        params:
            title:                              "Visualisation de l'utilisateur {{ PUser.firstname }} {{ PUser.name }}"
            tabs:
                "Identité":
                    "Type":                     [ qualified ]
                    "Civilité":                 [ [ file_name, gender, firstname, name ] ]
                    "Contacts":                 [ [ phone, email ], [ website ], [ twitter, facebook ] ]
                "Descriptif":
                    "Informations":             [ biography ]
                "Tag":
                    "Tags du profil":           [ block_tags_geo ]
                "Réputation":
                    "Badges":                   [ block_badges_debat, block_badges_comment, block_badges_participation, block_badges_moderation, block_badges_autre ]
                "Publication":
                    "Débats":                   [ block_debates ]
                    "Réactions":                [ block_reactions ]
                    "Commentaires":             [ block_comments ]
                "Abonnement":
                    "Followers":                [ block_followers_q, block_followers_c ]
                    "Suivis":                   [ block_subscribers_q, block_subscribers_c ]
                "Statut":
                    "Actuel":                   [ [ p_u_status_id ] ]
                    "Connexion":                [ last_connect ]
                "Attributs":
                    "En ligne":                 [ [ online ] ]
                    "Validé":                   [ [ validated ] ]
                    "Rôles":                    [ roles ]
                    "Création":                 [ [ created_at, updated_at ] ]
            fields:
                block_tags_geo:
                    label:                      "Tags géo"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_debates:
                    label:                      "Débats"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_debat:
                    label:                      "Débat"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_comment:
                    label:                      "Commentaire"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_participation:
                    label:                      "Participation"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_moderation:
                    label:                      "Modération"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_badges_autre:
                    label:                      "Autres"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_reactions:
                    label:                      "Réactions"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_comments:
                    label:                      "Commentaires"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_followers_q:
                    label:                      "Qualifiés"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_followers_c:
                    label:                      "Citoyens"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_subscribers_q:
                    label:                      "Qualifiés"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_subscribers_c:
                    label:                      "Citoyens"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                block_affinities:
                    label:                      "Partis Politiques"
                    formType:                   hidden
                    dbType:                     VARCHAR
                    addFormOptions:
                        mapped:                 false
                last_connect:
                    label:                      Date de dernière connexion
            actions:
                list:                           ~
                edit:                           ~
                delete:                         ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
