# FOS user routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

################################################################################
#               CUSTOM ROUTES
################################################################################
# ADMIN GENERIC XHR
AdminXhrGeneric:
    pattern:  /adminxhr/{xhrRoute}/{xhrService}/{xhrMethod}.{xhrType}.json
    defaults: { _controller: PolitizrFrontBundle:Xhr\XhrGeneric:xhr }
    requirements:
        _method:        POST
        xhrRoute:       ".+"
        xhrType:        \d

# ADMIN DEDICATED XHR
Politizr_AdminBundle_New_UpdPDDebate:
    pattern:  /PDReaction/xhr/updatePDDebate.json
    defaults: { _controller: PolitizrAdminBundle:PDReaction\Actions:updatePDReaction }
    requirements:
        _method:        POST

# Accueil
PolitizrAdminHomepage:
    pattern:  /
    defaults: { _controller: PolitizrAdminBundle:Homepage\AdminHomepage:index }

# Commandes
Politizr_AdminBundle_POrder_invoice:
    pattern:  /POrder/{pk}/invoice
    defaults: { _controller: PolitizrAdminBundle:POrder/Actions:invoice }

Politizr_AdminBundle_POrder_mail:
    pattern:  /POrder/{pk}/mail
    defaults: { _controller: PolitizrAdminBundle:POrder/Actions:mail }


# Débats
Politizr_AdminBundle_PDDebate_Comments:
    pattern:  /PDDebate/{pk}/comments
    defaults: { _controller: PolitizrAdminBundle:PDDebate/Actions:comments }


# Réactions
# Politizr_AdminBundle_PDReaction_NewNode:
#     pattern:  /PDReaction/{pk}/new_node
#     defaults: { _controller: PolitizrAdminBundle:PDReaction/Actions:newNode }

Politizr_AdminBundle_PDReaction_Comments:
    pattern:  /PDReaction/{pk}/comments
    defaults: { _controller: PolitizrAdminBundle:PDReaction/Actions:comments }

# Archivage
Politizr_AdminBundle_PDDComment_archive:
    pattern:  /PDDComment/{pk}/archive
    defaults: { _controller: PolitizrAdminBundle:PDDComment/Actions:archive }

Politizr_AdminBundle_PDRComment_archive:
    pattern:  /PDRComment/{pk}/archive
    defaults: { _controller: PolitizrAdminBundle:PDRComment/Actions:archive }

Politizr_AdminBundle_PDDebate_archive:
    pattern:  /PDDebate/{pk}/archive
    defaults: { _controller: PolitizrAdminBundle:PDDebate/Actions:archive }

Politizr_AdminBundle_PDReaction_archive:
    pattern:  /PDReaction/{pk}/archive
    defaults: { _controller: PolitizrAdminBundle:PDReaction/Actions:archive }

Politizr_AdminBundle_PUser_archive:
    pattern:  /PUser/{pk}/archive
    defaults: { _controller: PolitizrAdminBundle:PUser/Actions:archive }


# Circles
Politizr_AdminBundle_PCircle_addUsersToCircle:
    pattern:  /PCircle/addUsersToCircle
    defaults: { _controller: PolitizrAdminBundle:PCircle/Actions:addUsersToCircle }

Politizr_AdminBundle_PCircle_removeUsersFromCircle:
    pattern:  /PCircle/removeUsersFromCircle
    defaults: { _controller: PolitizrAdminBundle:PCircle/Actions:removeUsersFromCircle }

Politizr_AdminBundle_PCircle_addUsersIsAuthorizedReactionToCircle:
    pattern:  /PCircle/addUsersIsAuthorizedReactionToCircle
    defaults: { _controller: PolitizrAdminBundle:PCircle/Actions:addUsersIsAuthorizedReactionToCircle }

Politizr_AdminBundle_PCircle_removeUsersIsAuthorizedReactionToCircle:
    pattern:  /PCircle/removeUsersIsAuthorizedReactionToCircle
    defaults: { _controller: PolitizrAdminBundle:PCircle/Actions:removeUsersIsAuthorizedReactionToCircle }


################################################################################
#               ADMIN GENERATED ROUTES
################################################################################

# FOSUser (admin)
Politizr_AdminBundle_User:
    resource: "@PolitizrAdminBundle/Controller/User/"
    type:     admingenerator
    prefix:   /User



# Commandes
Politizr_AdminBundle_PEOperation:
    resource: "@PolitizrAdminBundle/Controller/PEOperation/"
    type:     admingenerator
    prefix:   /PEOperation

Politizr_AdminBundle_POrder:
    resource: "@PolitizrAdminBundle/Controller/POrder/"
    type:     admingenerator
    prefix:   /POrder



# Utilisateurs
Politizr_AdminBundle_PUser:
    resource: "@PolitizrAdminBundle/Controller/PUser/"
    type:     admingenerator
    prefix:   /PUser


# Contenus / Documents
Politizr_AdminBundle_PDDebate:
    resource: "@PolitizrAdminBundle/Controller/PDDebate/"
    type:     admingenerator
    prefix:   /PDDebate

Politizr_AdminBundle_PDReaction:
    resource: "@PolitizrAdminBundle/Controller/PDReaction/"
    type:     admingenerator_nested
    prefix:   /PDReaction

Politizr_AdminBundle_PDDComment:
    resource: "@PolitizrAdminBundle/Controller/PDDComment/"
    type:     admingenerator
    prefix:   /PDDComment

Politizr_AdminBundle_PDRComment:
    resource: "@PolitizrAdminBundle/Controller/PDRComment/"
    type:     admingenerator
    prefix:   /PDRComment

Politizr_AdminBundle_PDDirect:
    resource: "@PolitizrAdminBundle/Controller/PDDirect/"
    type:     admingenerator
    prefix:   /PDDirect

# Groupes
Politizr_AdminBundle_PCOwner:
    resource: "@PolitizrAdminBundle/Controller/PCOwner/"
    type:     admingenerator
    prefix:   /PCOwner

Politizr_AdminBundle_PCircle:
    resource: "@PolitizrAdminBundle/Controller/PCircle/"
    type:     admingenerator
    prefix:   /PCircle

Politizr_AdminBundle_PCTopic:
    resource: "@PolitizrAdminBundle/Controller/PCTopic/"
    type:     admingenerator
    prefix:   /PCTopic


# Tags
Politizr_AdminBundle_PTag:
    resource: "@PolitizrAdminBundle/Controller/PTag/"
    type:     admingenerator
    prefix:   /PTag


# Réputation
Politizr_AdminBundle_PRBadge:
    resource: "@PolitizrAdminBundle/Controller/PRBadge/"
    type:     admingenerator
    prefix:   /PRBadge

Politizr_AdminBundle_PRAction:
    resource: "@PolitizrAdminBundle/Controller/PRAction/"
    type:     admingenerator
    prefix:   /PRAction


# Réglages des types
Politizr_AdminBundle_PTTagType:
    resource: "@PolitizrAdminBundle/Controller/PTTagType/"
    type:     admingenerator
    prefix:   /PTTagType

Politizr_AdminBundle_PRBadgeFamily:
    resource: "@PolitizrAdminBundle/Controller/PRBadgeFamily/"
    type:     admingenerator
    prefix:   /PRBadgeFamily

Politizr_AdminBundle_PRBadgeType:
    resource: "@PolitizrAdminBundle/Controller/PRBadgeType/"
    type:     admingenerator
    prefix:   /PRBadgeType

Politizr_AdminBundle_PQOrganization:
    resource: "@PolitizrAdminBundle/Controller/PQOrganization/"
    type:     admingenerator
    prefix:   /PQOrganization

Politizr_AdminBundle_PQMandate:
    resource: "@PolitizrAdminBundle/Controller/PQMandate/"
    type:     admingenerator
    prefix:   /PQMandate

Politizr_AdminBundle_PMModerationType:
    resource: "@PolitizrAdminBundle/Controller/PMModerationType/"
    type:     admingenerator
    prefix:   /PMModerationType

Politizr_AdminBundle_PNotification:
    resource: "@PolitizrAdminBundle/Controller/PNotification/"
    type:     admingenerator
    prefix:   /PNotification

Politizr_AdminBundle_POSubscription:
    resource: "@PolitizrAdminBundle/Controller/POSubscription/"
    type:     admingenerator
    prefix:   /POSubscription

Politizr_AdminBundle_POPaymentType:
    resource: "@PolitizrAdminBundle/Controller/POPaymentType/"
    type:     admingenerator
    prefix:   /POPaymentType

Politizr_AdminBundle_POPaymentState:
    resource: "@PolitizrAdminBundle/Controller/POPaymentState/"
    type:     admingenerator
    prefix:   /POPaymentState

Politizr_AdminBundle_POOrderState:
    resource: "@PolitizrAdminBundle/Controller/POOrderState/"
    type:     admingenerator
    prefix:   /POOrderState

# Monitoring
Politizr_AdminBundle_PMAbuseReporting:
    resource: "@PolitizrAdminBundle/Controller/PMAbuseReporting/"
    type:     admingenerator
    prefix:   /PMAbuseReporting

Politizr_AdminBundle_PMAskForUpdate:
    resource: "@PolitizrAdminBundle/Controller/PMAskForUpdate/"
    type:     admingenerator
    prefix:   /PMAskForUpdate

Politizr_AdminBundle_PMEmailing:
    resource: "@PolitizrAdminBundle/Controller/PMEmailing/"
    type:     admingenerator
    prefix:   /PMEmailing

Politizr_AdminBundle_PMAppException:
    resource: "@PolitizrAdminBundle/Controller/PMAppException/"
    type:     admingenerator
    prefix:   /PMAppException

# Monitoring / Archives
Politizr_AdminBundle_PMUserHistoric:
    resource: "@PolitizrAdminBundle/Controller/PMUserHistoric/"
    type:     admingenerator
    prefix:   /PMUserHistoric

Politizr_AdminBundle_PMDebateHistoric:
    resource: "@PolitizrAdminBundle/Controller/PMDebateHistoric/"
    type:     admingenerator
    prefix:   /PMDebateHistoric

Politizr_AdminBundle_PMReactionHistoric:
    resource: "@PolitizrAdminBundle/Controller/PMReactionHistoric/"
    type:     admingenerator
    prefix:   /PMReactionHistoric

Politizr_AdminBundle_PMDCommentHistoric:
    resource: "@PolitizrAdminBundle/Controller/PMDCommentHistoric/"
    type:     admingenerator
    prefix:   /PMDCommentHistoric

Politizr_AdminBundle_PMRCommentHistoric:
    resource: "@PolitizrAdminBundle/Controller/PMRCommentHistoric/"
    type:     admingenerator
    prefix:   /PMRCommentHistoric

# Monitoring / Juridique
Politizr_AdminBundle_PMCgu:
    resource: "@PolitizrAdminBundle/Controller/PMCgu/"
    type:     admingenerator
    prefix:   /PMCgu

Politizr_AdminBundle_PMCgv:
    resource: "@PolitizrAdminBundle/Controller/PMCgv/"
    type:     admingenerator
    prefix:   /PMCgv

Politizr_AdminBundle_PMCharte:
    resource: "@PolitizrAdminBundle/Controller/PMCharte/"
    type:     admingenerator
    prefix:   /PMCharte

