services:

    # LISTENERS
    politzr.listener.email:
        class:      Politizr\AdminBundle\Listener\EmailListener
        arguments:  [ @mailer, @templating, @logger, "%contact_email%" ]
        tags:
            - { name: kernel.event_listener, event: order_email }

    politzr.listener.pdf:
        class:      Politizr\AdminBundle\Listener\PDFListener
        arguments:  [ @kernel, @mailer, @templating, @html2pdf, @logger ]
        tags:
            - { name: kernel.event_listener, event: order_pdf }



    # EXTENSIONS TWIG
    politzr.twig.admin_ajax_extension:
        class:                              Politizr\AdminBundle\Twig\AdminAjaxExtension
        arguments:                          [ @service_container ]
        tags:
                                            - { name: twig.extension }
