services:

    # LISTENERS
    politzr_admin.listener.email:
        class:      Politizr\AdminBundle\Listener\EmailListener
        arguments:  
            - @mailer
            - @templating
            - @logger
            - "%contact_email%"
            - "%support_email%"
        tags:
            - { name: kernel.event_listener, event: order_email }
            - { name: kernel.event_listener, event: moderation_notification }
            - { name: kernel.event_listener, event: moderation_banned }

    politzr_admin.listener.pdf:
        class:      Politizr\AdminBundle\Listener\PDFListener
        arguments:  [ @kernel, @mailer, @templating, @html2pdf_factory, @logger ]
        tags:
            - { name: kernel.event_listener, event: order_pdf }

    # XHR
    politizr.xhr.admin:
        class: Politizr\AdminBundle\Lib\Xhr\XhrAdmin
        arguments:
            - @security.token_storage
            - @kernel
            - @router
            - @event_dispatcher
            - @templating
            - @form.factory
            - @politizr.manager.tag
            - @politizr.tools.global
            - @logger


    # EXTENSIONS TWIG
    politzr_admin.twig.admin_ajax_extension:
        class: Politizr\AdminBundle\Twig\PolitizrAdminExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }
