services:
    # ADMIN MENU
    admingen.menu.default_builder:
        class: Politizr\AdminBundle\Menu\AdminMenu
        arguments:
            - @knp_menu.factory
            - @request_stack
            - PolitizrAdminHomepage
            - @security.token_storage
        tags:
            - { name: knp_menu.menu_builder, method: sidebarMenu, alias: admingen_mysidebar }

    # LISTENERS
    politzr_admin.listener.email:
        class:      Politizr\AdminBundle\Listener\EmailListener
        arguments:  
            - @mailer
            - @templating
            - @logger
            - "%contact_email%"
            - "%support_email%"
        tags:
            - { name: kernel.event_listener, event: order_email }
            - { name: kernel.event_listener, event: moderation_notification }
            - { name: kernel.event_listener, event: moderation_banned }

    politzr_admin.listener.pdf:
        class:      Politizr\AdminBundle\Listener\PDFListener
        arguments:  [ @kernel, @mailer, @templating, @html2pdf_factory, @logger ]
        tags:
            - { name: kernel.event_listener, event: order_pdf }

    # XHR
    politizr.xhr.admin:
        class: Politizr\AdminBundle\Lib\Xhr\XhrAdmin
        arguments:
            - @kernel
            - @event_dispatcher
            - @templating
            - @form.factory
            - @politizr.functional.localization
            - @politizr.functional.circle
            - @politizr.manager.tag
            - @politizr.manager.user
            - @politizr.manager.localization
            - @politizr.manager.event
            - @politizr.form.type.document_localization
            - @politizr.tools.global
            - @logger

    politizr.xhr.dashboard:
        class: Politizr\AdminBundle\Lib\Xhr\XhrDashboard
        arguments:
            - @kernel
            - @event_dispatcher
            - @templating
            - @form.factory
            - @politizr.tools.global
            - @logger


    # EXTENSIONS TWIG
    politzr_admin.twig.generic:
        class: Politizr\AdminBundle\Twig\PolitizrAdminExtension
        arguments:
            - @politizr.functional.document
            - @form.factory
            - @router
            - @logger
        tags:
            - { name: twig.extension }
    politzr_admin.twig.tag:
        class: Politizr\AdminBundle\Twig\PolitizrAdminTagExtension
        arguments:
            - @politizr.functional.document
            - @form.factory
            - @router
            - @logger
        tags:
            - { name: twig.extension }
    politzr_admin.twig.document:
        class: Politizr\AdminBundle\Twig\PolitizrAdminDocumentExtension
        arguments:
            - @kernel
            - @politizr.functional.document
            - @form.factory
            - @router
            - @logger
        tags:
            - { name: twig.extension }
    politzr_admin.twig.user:
        class: Politizr\AdminBundle\Twig\PolitizrAdminUserExtension
        arguments:
            - @kernel
            - @politizr.functional.document
            - @politizr.tools.global
            - @form.factory
            - @router
            - @logger
        tags:
            - { name: twig.extension }
    politzr_admin.twig.moderation:
        class: Politizr\AdminBundle\Twig\PolitizrAdminModerationExtension
        arguments:
            - @politizr.functional.document
            - @form.factory
            - @router
            - @logger
        tags:
            - { name: twig.extension }
    politzr_admin.twig.localization:
        class: Politizr\AdminBundle\Twig\PolitizrAdminLocalizationExtension
        arguments:
            - @politizr.functional.document
            - @politizr.form.type.document_localization
            - @form.factory
            - @router
            - @logger
        tags:
            - { name: twig.extension }
    politzr_admin.twig.circle:
        class: Politizr\AdminBundle\Twig\PolitizrAdminCircleExtension
        arguments:
            - @kernel
            - @politizr.tools.global
            - @router
            - @logger
        tags:
            - { name: twig.extension }


    # FORM TYPE
    politizr_admin.form.type.date_range:
        class: Politizr\AdminBundle\Form\Type\DateRangeType
        tags:
            - { name: form.type, alias: date_range }
