##################################################################################
#                   PROPEL VALIDATOR RULES / ADMIN
##################################################################################

####################################### CMS #####################################

Politizr\Model\CmsCategory:
    properties:
        title:
            - NotBlank:     ~

Politizr\Model\CmsPage:
    properties:
        title:
            - NotBlank:     ~



####################################### USER #####################################

Politizr\Model\PUser:
    properties:
#         p_u_status_id:
#             - Type:
#                 type:       integer 
#                 message:    "La valeur {{ value }} n'est pas un type {{ type }} valide."
#             - NotBlank:     ~
        username:
            - NotBlank:     ~


####################################### ORDER #####################################

Politizr\Model\POrder:
    properties:
        price:
            - NotBlank:     ~
        total:
            - NotBlank:     ~

##################################### DOCUMENT #####################################

# Politizr\Model\PDDebate:
#     properties:
#         p_user_id:
#             - NotBlank:     ~
#         title:
#             - NotBlank:     ~

# Politizr\Model\PDReaction:
#     properties:
#         p_d_debate_id:
#             - NotBlank:     ~
#         p_user_id:
#             - NotBlank:     ~
#         title:
#             - NotBlank:     ~

Politizr\Model\PDDComment:
    properties:
        p_d_debate_id:
            - NotBlank:     ~
        p_user_id:
            - NotBlank:     ~
        description:
            - NotBlank:     ~

Politizr\Model\PDRComment:
    properties:
        p_d_reaction_id:
            - NotBlank:     ~
        p_user_id:
            - NotBlank:     ~
        description:
            - NotBlank:     ~


##################################### TAGS #####################################

Politizr\Model\PTag:
    properties:
        p_t_tag_type_id:
            - NotBlank:     ~
        title:
            - NotBlank:     ~

##################################  RÉPUTATION  ################################

Politizr\Model\PRBadge:
    properties:
        title:
            - NotBlank:     ~

Politizr\Model\PRAction:
    properties:
        title:
            - NotBlank:     ~
        score_evolution:
            - NotBlank:     ~
            - Type:
                type:       integer 
                message:    "La valeur {{ value }} n'est pas un type {{ type }} valide."


##################################### TYPES #####################################

Politizr\Model\PTTagType:
    properties:
        title:
            - NotBlank:     ~

Politizr\Model\PRBadgeFamily:
    properties:
        title:
            - NotBlank:     ~

Politizr\Model\PRBadgeType:
    properties:
        title:
            - NotBlank:     ~

Politizr\Model\PQOrganization:
    properties:
        title:
            - NotBlank:     ~
        initials:
            - NotBlank:     ~

Politizr\Model\POSubscription:
    properties:
        title:
            - NotBlank:     ~
        price:
            - NotBlank:     ~
            - Type:
                type:       numeric 
                message:    "La valeur {{ value }} n'est pas un type {{ type }} valide."


Politizr\Model\POPaymentType:
    properties:
        title:
            - NotBlank:     ~

Politizr\Model\POPaymentState:
    properties:
        title:
            - NotBlank:     ~

Politizr\Model\POOrderState:
    properties:
        title:
            - NotBlank:     ~
