# Insertion de sujets tests

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (2, 18, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-1', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (3, 18, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-2', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (4, 18, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-3', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (5, 18, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-4', NOW(), NOW(), NOW());


INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`)
VALUES (6, 19, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-5', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (7, 19, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-6', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (8, 19, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-7', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (9, 19, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-8', NOW(), NOW(), NOW());


INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (10, 20, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-9', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (11, 20, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-10', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (13, 20, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-1', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (14, 20, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-12', NOW(), NOW(), NOW());



INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (15, 21, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-13', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (21, 21, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-14', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (17, 21, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-15', NOW(), NOW(), NOW());

INSERT INTO `p_d_debate` (`p_user_id`, `p_c_topic_id`, `title`, `description`, `published`, `published_by`, `online`, `slug`, `published_at`, `created_at`, `updated_at`) 
VALUES (18, 21, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac placerat dui, in efficitur ligula.</p><p>Aliquam felis ligula, ultricies mattis sodales ut, dapibus sed tellus. Mauris cursus cursus arcu, quis tempor magna sagittis eu.</p><p>Fusce at magna sed nibh varius convallis. Ut semper est at leo tempus eleifend. Sed dignissim purus at tellus tempor, quis facilisis risus mattis. Curabitur fermentum finibus erat nec hendrerit. Fusce tempus vitae elit vitae feugiat. Pellentesque blandit, tortor vel porttitor dictum, magna tortor venenatis augue, vitae vulputate mauris orci id nisi. Mauris sodales tellus sed dapibus feugiat. Sed semper arcu vel lorem ultrices, at suscipit magna mattis. Cras ultricies molestie nisl, vel accumsan elit tempus sed. Proin fermentum aliquet magna, ut dictum urna rhoncus ut. Maecenas metus ipsum, auctor a maximus et, sollicitudin et eros. Quisque id aliquet felis. Nam eget fringilla augue.</p>', 1, 'Lionel Bouzonville', 1, 'lorem-ipsum-16', NOW(), NOW(), NOW());

# app/console politizr:uuids:populate PDDebate
